// Do not edit. This file is machine generated by the Resource DLL Wizard.

library PrUpdate;

{ITE} {LCID:00000416:00000416} {}
{ITE} {RCFileType} {PrUpdate_DRC.rc}

{$R 'PrUpdate_DRC.res' 'PrUpdate_DRC.rc'}

{$E PTB}

begin
end.