// Do not edit. This file is machine generated by the Resource DLL Wizard.

library PrSenhas;

{ITE} {LCID:00000416:00000416} {}
{ITE} {DFMFileType} {Unit1.dfm}
{ITE} {RCFileType} {PrSenhas_DRC.rc}

{$R 'Unit1.dfm' Form1:TForm}
{$R 'PrSenhas_DRC.res' 'PrSenhas_DRC.rc'}

{$E PTB}

begin
end.