unit UDMServerImpr;

{$WARN SYMBOL_PLATFORM OFF}

interface

uses
  Windows, Messages, SysUtils, Classes, ComServ, ComObj, VCLCom, DataBkr,
  DBClient, PrServer_TLB, StdVcl, Provider, DB, IBDatabase,
  IBCustomDataSet, IBQuery, Registry, Dialogs, DBTables;

type
  TServerImpr = class(TRemoteDataModule, IServerImpr)
    dsImprHistClientes1: TDataSource;
    dsImprHistClientes2: TDataSource;
    dspImprPed: TDataSetProvider;
    dspImprNfDups: TDataSetProvider;
    dspImprNfItem: TDataSetProvider;
    dspImprNf: TDataSetProvider;
    dspImprPedItem: TDataSetProvider;
    dspImprEst: TDataSetProvider;
    dspImprHistClientes1: TDataSetProvider;
    dspImprHistClientes2: TDataSetProvider;
    dspImprHistClientes3: TDataSetProvider;
    dspImprClientesUF: TDataSetProvider;
    dspImprDemPrev: TDataSetProvider;
    dspImprNfVend: TDataSetProvider;
    dspImprNfSerie: TDataSetProvider;
    qrImprPed: TQuery;
    qrImprPedItem: TQuery;
    qrImprNfItem: TQuery;
    qrImprNf: TQuery;
    qrImprNfVend: TQuery;
    qrImprNfDups: TQuery;
    qrImprEst: TQuery;
    qrImprHistClientes1: TQuery;
    qrImprHistClientes3: TQuery;
    qrImprHistClientes2: TQuery;
    qrImprDemPrev: TQuery;
    qrImprClientesUF: TQuery;
    qrImprNfSerie: TQuery;
    Session1: TSession;
    DBConn: TDatabase;
    dspImprNfFech: TDataSetProvider;
    qrImprNfFech: TQuery;
    dspImprAssist: TDataSetProvider;
    dspImprAssistItem: TDataSetProvider;
    dspImprAssistEquip: TDataSetProvider;
    qrImprAssist: TQuery;
    qrImprAssistEquip: TQuery;
    qrAssistItem: TQuery;
    dspImprNFServicos: TDataSetProvider;
    qrImprNFServicos: TQuery;
    qrImprPedItemNR_SERIE_ITEM: TMemoField;
    qrImprPedItemCODIGO_PECA: TStringField;
    qrImprPedItemDESCRICAO_PECA: TStringField;
    qrImprPedItemQTDE_PEDIDO_ITEM: TIntegerField;
    qrImprPedItemCODIGO_NBM: TStringField;
    qrImprPedItemPRECO_UNIT: TBCDField;
    qrImprPedItemVLR_DESC: TBCDField;
    qrImprPedItemVLR_IPI_ITEM: TBCDField;
    qrImprPedItemALIQ_ICMS_ITEM: TBCDField;
    qrImprPedItemALIQ_IPI_ITEM: TBCDField;
    qrImprPedItemVLR_TOTAL_ITEM: TBCDField;
    qrImprNFServicosNF_SERVICO_SQ: TIntegerField;
    qrImprNFServicosNUMERO_NF_SERVICO: TIntegerField;
    qrImprNFServicosDATA_NF_SERVICO: TDateTimeField;
    qrImprNFServicosCLIENTE_SQ: TIntegerField;
    qrImprNFServicosTTL_NF_SERVICO: TBCDField;
    qrImprNFServicosALIQ_ISS_NF_SERVICO: TBCDField;
    qrImprNFServicosVLR_ISS_NF_SERVICO: TBCDField;
    qrImprNFServicosNOME_CLIENTE: TStringField;
    qrAssistItemASSISTENCIA_ITEM_SQ: TIntegerField;
    qrAssistItemASSISTENCIA_SQ: TIntegerField;
    qrAssistItemPECA_SQ: TIntegerField;
    qrAssistItemQTDE_ASSISTENCIA_ITEM: TIntegerField;
    qrAssistItemPRECO_UNIT: TBCDField;
    qrAssistItemCODIGO_PECA: TStringField;
    qrAssistItemDESCRICAO_PECA: TStringField;
    qrAssistItemCODIGO_NBM: TStringField;
    qrImprAssistEquipASSISTENCIA_EQUIP_SQ: TIntegerField;
    qrImprAssistEquipASSISTENCIA_SQ: TIntegerField;
    qrImprAssistEquipMODELO_SQ: TIntegerField;
    qrImprAssistEquipNR_SERIE_EQUIP: TMemoField;
    qrImprAssistEquipDEFEITO: TBlobField;
    qrImprAssistEquipCODIGO_MODELO: TStringField;
    qrImprAssistEquipDESCRICAO_MODELO: TStringField;
    qrImprAssistEquipCODIGO_NBM: TStringField;
    qrImprAssistASSISTENCIA_SQ: TIntegerField;
    qrImprAssistNUMERO_ASSISTENCIA: TIntegerField;
    qrImprAssistDATA_CHAMADO: TDateTimeField;
    qrImprAssistDATA_ASSISTENCIA: TDateTimeField;
    qrImprAssistCOTACAO_DOLAR: TBCDField;
    qrImprAssistCLIENTE_SQ: TIntegerField;
    qrImprAssistCOND_PAGTO_SQ: TIntegerField;
    qrImprAssistDESP_CHAMADO: TBCDField;
    qrImprAssistDESP_HTEC_AD: TBCDField;
    qrImprAssistDESP_DESLOC: TBCDField;
    qrImprAssistVLR_PECAS: TBCDField;
    qrImprAssistVLR_TOTAL: TBCDField;
    qrImprAssistHORA_INICIO: TTimeField;
    qrImprAssistHORA_FIM: TTimeField;
    qrImprAssistGARANTIA: TStringField;
    qrImprAssistCONTRATO: TStringField;
    qrImprAssistSERVICOS: TMemoField;
    qrImprAssistDDD_FONE1: TStringField;
    qrImprAssistNUMERO_FONE1: TStringField;
    qrImprAssistCOMPL_FONE1: TStringField;
    qrImprAssistDDD_CELULAR: TStringField;
    qrImprAssistNUMERO_CELULAR: TStringField;
    qrImprAssistCOMPL_CELULAR: TStringField;
    qrImprAssistENDERECO: TStringField;
    qrImprAssistNUMERO: TStringField;
    qrImprAssistCOMPL_ENDERECO: TStringField;
    qrImprAssistDDD_FONE2: TStringField;
    qrImprAssistNUMERO_FONE2: TStringField;
    qrImprAssistCOMPL_FONE2: TStringField;
    qrImprAssistDDD_FONE3: TStringField;
    qrImprAssistNUMERO_FONE3: TStringField;
    qrImprAssistCOMPL_FONE3: TStringField;
    qrImprAssistDDD_FAX: TStringField;
    qrImprAssistNUMERO_FAX: TStringField;
    qrImprAssistCOMPL_FAX: TStringField;
    qrImprAssistCODIGO_CLIENTE: TStringField;
    qrImprAssistNOME_CLIENTE: TStringField;
    qrImprAssistCONTATO: TStringField;
    qrImprAssistINSCR_ESTADUAL: TStringField;
    qrImprAssistBAIRRO: TStringField;
    qrImprAssistCIDADE: TStringField;
    qrImprAssistESTADO: TStringField;
    qrImprAssistPAIS: TStringField;
    qrImprAssistCEP: TStringField;
    qrImprAssistD00: TIntegerField;
    qrImprAssistD01: TIntegerField;
    qrImprAssistD02: TIntegerField;
    qrImprAssistD03: TIntegerField;
    qrImprAssistD04: TIntegerField;
    qrImprAssistD05: TIntegerField;
    qrImprAssistD06: TIntegerField;
    qrImprAssistD07: TIntegerField;
    qrImprAssistD08: TIntegerField;
    qrImprAssistD09: TIntegerField;
    qrImprAssistPARCELAS: TIntegerField;
    qrImprAssistDESCRICAO_COND_PAGTO: TStringField;
    qrImprNfSerieNR_SERIE_ITEM: TMemoField;
    qrImprNfSerieNFISCAL_SQ: TIntegerField;
    qrImprNfSerieNUMERO_NFISCAL: TIntegerField;
    qrImprNfSerieDTEMISSAO_NFISCAL: TDateTimeField;
    qrImprNfSerieDTSAIDA_NFISCAL: TDateTimeField;
    qrImprNfSeriePEDIDO_SQ: TIntegerField;
    qrImprNfSerieCLIENTE_SQ: TIntegerField;
    qrImprNfSerieCOND_PAGTO_SQ: TIntegerField;
    qrImprNfSerieNATUREZA_SQ: TIntegerField;
    qrImprNfSerieTRANSPORTADORA_SQ: TIntegerField;
    qrImprNfSerieBASE_ICMS: TBCDField;
    qrImprNfSerieVLR_ICMS: TBCDField;
    qrImprNfSerieBASE_ICMS_SUBST: TBCDField;
    qrImprNfSerieVLR_ICMS_SUBST: TBCDField;
    qrImprNfSerieVLR_PRODUTOS: TBCDField;
    qrImprNfSerieVLR_FRETE: TBCDField;
    qrImprNfSerieVLR_SEGURO: TBCDField;
    qrImprNfSerieVLR_DESP_ACESS: TBCDField;
    qrImprNfSerieVLR_IPI: TBCDField;
    qrImprNfSerieVLR_TOTAL: TBCDField;
    qrImprNfSerieFRETE_TRANSP: TStringField;
    qrImprNfSeriePLACA_TRANSP: TStringField;
    qrImprNfSerieUF_PLACA_TRANSP: TStringField;
    qrImprNfSerieQTDE_TRANSP: TIntegerField;
    qrImprNfSerieESPECIE_TRANSP: TStringField;
    qrImprNfSerieMARCA_TRANSP: TStringField;
    qrImprNfSerieNUMERO_TRANSP: TStringField;
    qrImprNfSeriePBRUTO_TRANSP: TStringField;
    qrImprNfSeriePLIQUIDO_TRANSP: TStringField;
    qrImprNfSerieCLASS_FISCAL1: TIntegerField;
    qrImprNfSerieCLASS_FISCAL2: TIntegerField;
    qrImprNfSerieCLASS_FISCAL3: TIntegerField;
    qrImprNfSerieCLASS_FISCAL4: TIntegerField;
    qrImprNfSerieCLASS_FISCAL5: TIntegerField;
    qrImprNfSerieCLASS_FISCAL6: TIntegerField;
    qrImprNfSerieCLASS_FISCAL7: TIntegerField;
    qrImprNfSerieMENSAGEM: TMemoField;
    qrImprNfSerieCANCELADA: TStringField;
    qrImprNfSerieDIAS_DEMONSTRACAO: TIntegerField;
    qrImprNfSerieCOTACAO_DOLAR: TBCDField;
    qrImprNfSerieNR_NFISCAL_RETORNO: TIntegerField;
    qrImprNfSerieDT_NFISCAL_RETORNO: TDateTimeField;
    qrImprNfSerieCONCLUIDA: TStringField;
    qrImprNfSerieVENDEDOR_SQ: TIntegerField;
    qrImprNfSerieNF_MANUAL: TStringField;
    qrImprNfSerieRETORNO_PRODUTO: TStringField;
    qrImprNfSerieRETORNO_OBSERVACAO: TMemoField;
    qrImprNfSerieNOME_CLIENTE: TStringField;
    qrImprNfSerieDESCRICAO_COND_PAGTO: TStringField;
    qrImprNfSerieDESCRICAO_NATUREZA: TStringField;
    qrImprNfSerieNOME_VENDEDOR: TStringField;
    qrImprDemPrevNUMERO_NFISCAL: TIntegerField;
    qrImprDemPrevNOME_CLIENTE: TStringField;
    qrImprDemPrevDTEMISSAO_NFISCAL: TDateTimeField;
    qrImprDemPrevDIAS_DEMONSTRACAO: TIntegerField;
    qrImprDemPrevDT_NFISCAL_RETORNO: TDateTimeField;
    qrImprClientesUFCLIENTE_SQ: TIntegerField;
    qrImprClientesUFCODIGO_CLIENTE: TStringField;
    qrImprClientesUFNOME_CLIENTE: TStringField;
    qrImprClientesUFINSCR_ESTADUAL: TStringField;
    qrImprClientesUFENDERECO: TStringField;
    qrImprClientesUFNUMERO: TStringField;
    qrImprClientesUFBAIRRO: TStringField;
    qrImprClientesUFCOMPL_ENDERECO: TStringField;
    qrImprClientesUFCIDADE: TStringField;
    qrImprClientesUFESTADO: TStringField;
    qrImprClientesUFCEP: TStringField;
    qrImprClientesUFDDD_FONE1: TStringField;
    qrImprClientesUFNUMERO_FONE1: TStringField;
    qrImprClientesUFCOMPL_FONE1: TStringField;
    qrImprClientesUFDDD_FONE2: TStringField;
    qrImprClientesUFNUMERO_FONE2: TStringField;
    qrImprClientesUFCOMPL_FONE2: TStringField;
    qrImprClientesUFDDD_FONE3: TStringField;
    qrImprClientesUFNUMERO_FONE3: TStringField;
    qrImprClientesUFCOMPL_FONE3: TStringField;
    qrImprClientesUFDDD_CELULAR: TStringField;
    qrImprClientesUFNUMERO_CELULAR: TStringField;
    qrImprClientesUFCOMPL_CELULAR: TStringField;
    qrImprClientesUFDDD_FAX: TStringField;
    qrImprClientesUFNUMERO_FAX: TStringField;
    qrImprClientesUFCOMPL_FAX: TStringField;
    qrImprClientesUFE_MAIL: TStringField;
    qrImprClientesUFWEB_SITE: TStringField;
    qrImprClientesUFCONTATO: TStringField;
    qrImprClientesUFPAIS: TStringField;
    qrImprClientesUFREVENDA: TStringField;
    qrImprClientesUFBIRO: TStringField;
    qrImprClientesUFQTDE: TBCDField;
    qrImprClientesUFVALOR: TBCDField;
    qrImprClientesUFDATA: TDateTimeField;
    qrImprHistClientes3NFISCAL_ITEM_SQ: TIntegerField;
    qrImprHistClientes3NFISCAL_SQ: TIntegerField;
    qrImprHistClientes3ITEM: TIntegerField;
    qrImprHistClientes3TIPO_ITEM: TStringField;
    qrImprHistClientes3PECA_SQ: TIntegerField;
    qrImprHistClientes3MODELO_SQ: TIntegerField;
    qrImprHistClientes3NR_SERIE_ITEM: TMemoField;
    qrImprHistClientes3CLASS_FISCAL: TStringField;
    qrImprHistClientes3STRIBUT: TIntegerField;
    qrImprHistClientes3QTDE_ITEM: TIntegerField;
    qrImprHistClientes3VLR_UNIT_ITEM: TBCDField;
    qrImprHistClientes3VLR_TOTAL_ITEM: TBCDField;
    qrImprHistClientes3ALIQ_ICMS_ITEM: TBCDField;
    qrImprHistClientes3ALIQ_IPI_ITEM: TBCDField;
    qrImprHistClientes3VLR_ICMS_ITEM: TBCDField;
    qrImprHistClientes3VLR_IPI_ITEM: TBCDField;
    qrImprHistClientes3CODIGO_PECA: TStringField;
    qrImprHistClientes3DESCRICAO_PECA: TStringField;
    qrImprHistClientes3CODIGO_NBM: TStringField;
    qrImprHistClientes3DESCRICAO_MODELO: TStringField;
    qrImprHistClientes2NFISCAL_SQ: TIntegerField;
    qrImprHistClientes2NUMERO_NFISCAL: TIntegerField;
    qrImprHistClientes2DTEMISSAO_NFISCAL: TDateTimeField;
    qrImprHistClientes2COTACAO_DOLAR: TBCDField;
    qrImprHistClientes2VLR_ICMS: TBCDField;
    qrImprHistClientes2VLR_IPI: TBCDField;
    qrImprHistClientes2VLR_FRETE: TBCDField;
    qrImprHistClientes2FRETE_TRANSP: TStringField;
    qrImprHistClientes2VLR_PRODUTOS: TBCDField;
    qrImprHistClientes2VLR_TOTAL: TBCDField;
    qrImprHistClientes2DESCRICAO_COND_PAGTO: TStringField;
    qrImprHistClientes2DESCRICAO_NATUREZA: TStringField;
    qrImprHistClientes2CFO: TStringField;
    qrImprHistClientes2NOME_TRANSPORTADORA: TStringField;
    qrImprHistClientes2NOME_VENDEDOR: TStringField;
    qrImprHistClientes1CLIENTE_SQ: TIntegerField;
    qrImprHistClientes1CODIGO_CLIENTE: TStringField;
    qrImprHistClientes1NOME_CLIENTE: TStringField;
    qrImprHistClientes1INSCR_ESTADUAL: TStringField;
    qrImprHistClientes1ENDERECO: TStringField;
    qrImprHistClientes1NUMERO: TStringField;
    qrImprHistClientes1BAIRRO: TStringField;
    qrImprHistClientes1COMPL_ENDERECO: TStringField;
    qrImprHistClientes1CIDADE: TStringField;
    qrImprHistClientes1ESTADO: TStringField;
    qrImprHistClientes1CEP: TStringField;
    qrImprHistClientes1DDD_FONE1: TStringField;
    qrImprHistClientes1NUMERO_FONE1: TStringField;
    qrImprHistClientes1COMPL_FONE1: TStringField;
    qrImprHistClientes1DDD_FONE2: TStringField;
    qrImprHistClientes1NUMERO_FONE2: TStringField;
    qrImprHistClientes1COMPL_FONE2: TStringField;
    qrImprHistClientes1DDD_FONE3: TStringField;
    qrImprHistClientes1NUMERO_FONE3: TStringField;
    qrImprHistClientes1COMPL_FONE3: TStringField;
    qrImprHistClientes1DDD_CELULAR: TStringField;
    qrImprHistClientes1NUMERO_CELULAR: TStringField;
    qrImprHistClientes1COMPL_CELULAR: TStringField;
    qrImprHistClientes1DDD_FAX: TStringField;
    qrImprHistClientes1NUMERO_FAX: TStringField;
    qrImprHistClientes1COMPL_FAX: TStringField;
    qrImprHistClientes1E_MAIL: TStringField;
    qrImprHistClientes1WEB_SITE: TStringField;
    qrImprHistClientes1CONTATO: TStringField;
    qrImprHistClientes1PAIS: TStringField;
    qrImprHistClientes1REVENDA: TStringField;
    qrImprHistClientes1BIRO: TStringField;
    qrImprNfFechNUMERO_NFISCAL: TIntegerField;
    qrImprNfFechCFO: TStringField;
    qrImprNfFechDESCRICAO_NATUREZA_NFISCAL: TStringField;
    qrImprNfFechVLR_PRODUTOS: TBCDField;
    qrImprNfFechVLR_TOTAL: TBCDField;
    qrImprNfFechVLR_ICMS: TBCDField;
    qrImprNfFechVLR_IPI: TBCDField;
    qrImprNfFechNOME_CLIENTE: TStringField;
    qrImprNfFechENT_SAI: TStringField;
    qrImprNfFechTIPO_NFISCAL: TIntegerField;
    qrImprNfFechCANCELADA: TStringField;
    qrImprEstPECA_SQ: TIntegerField;
    qrImprEstCODIGO_PECA: TStringField;
    qrImprEstDESCRICAO_PECA: TStringField;
    qrImprEstQTDE_PECA_LOJA: TIntegerField;
    qrImprEstQTDE_PECA_ARMAZEM: TIntegerField;
    qrImprEstQTDE_PECA_DEMO: TIntegerField;
    qrImprEstQTDE_PECA_DEFEITO: TIntegerField;
    qrImprEstQTDE_PECA_EM_USO: TIntegerField;
    qrImprEstQTDE_PECA_BACKUP: TIntegerField;
    qrImprEstQTDE_PECA_DEMO_CLI: TIntegerField;
    qrImprEstQTDE_PECA_HLC: TIntegerField;
    qrImprEstNBM_SQ: TIntegerField;
    qrImprEstMODELO_SQ: TIntegerField;
    qrImprEstUN_PECA: TStringField;
    qrImprEstMARCA_PECA: TStringField;
    qrImprEstPRECO_UNIT_PECA: TBCDField;
    qrImprEstTIPO_PECA: TIntegerField;
    qrImprEstDESCRICAO_MODELO: TStringField;
    qrImprEstCODIGO_NBM: TStringField;
    qrImprNfVendnfiscal_sq: TIntegerField;
    qrImprNfVendnumero_nfiscal: TIntegerField;
    qrImprNfVenddtemissao_nfiscal: TDateTimeField;
    qrImprNfVendvlr_total: TBCDField;
    qrImprNfVenddup1: TIntegerField;
    qrImprNfVendit1: TIntegerField;
    qrImprNfVendvlr1: TBCDField;
    qrImprNfVendvct1: TDateTimeField;
    qrImprNfVenddup2: TIntegerField;
    qrImprNfVendit2: TIntegerField;
    qrImprNfVendvlr2: TBCDField;
    qrImprNfVendvct2: TDateTimeField;
    qrImprNfVenddup3: TIntegerField;
    qrImprNfVendit3: TIntegerField;
    qrImprNfVendvlr3: TBCDField;
    qrImprNfVendvct3: TDateTimeField;
    qrImprNfVenddup4: TIntegerField;
    qrImprNfVendit4: TIntegerField;
    qrImprNfVendvlr4: TBCDField;
    qrImprNfVendvct4: TDateTimeField;
    qrImprNfVenddup5: TIntegerField;
    qrImprNfVendit5: TIntegerField;
    qrImprNfVendvlr5: TBCDField;
    qrImprNfVendvct5: TDateTimeField;
    qrImprNfVendvendedor_sq: TIntegerField;
    qrImprNfVendnome_vendedor: TStringField;
    qrImprNfVendcodigo_cliente: TStringField;
    qrImprNfVendnome_cliente: TStringField;
    qrImprNfDupsDUPLICATA_SQ: TIntegerField;
    qrImprNfDupsNUMERO_DUPLICATA: TIntegerField;
    qrImprNfDupsITEM_DUPLICATA: TIntegerField;
    qrImprNfDupsSEQ_DUPLICATA: TIntegerField;
    qrImprNfDupsNFISCAL_SQ: TIntegerField;
    qrImprNfDupsVALOR_DUPLICATA: TBCDField;
    qrImprNfDupsDTEMISSAO_DUPLICATA: TDateTimeField;
    qrImprNfDupsDTVENCTO_DUPLICATA: TDateTimeField;
    qrImprNfDupsDTPGTO_DUPLICATA: TDateTimeField;
    qrImprNfDupsVALORPG_DUPLICATA: TBCDField;
    qrImprNfItemPECA_SQ: TIntegerField;
    qrImprNfItemCODIGO_PECA: TStringField;
    qrImprNfItemDESCRICAO_PECA: TStringField;
    qrImprNfItemCLASS_FISCAL: TStringField;
    qrImprNfItemVLR_TOTAL_ITEM: TBCDField;
    qrImprNfItemVLR_UNIT_ITEM: TBCDField;
    qrImprNfItemQTDE_ITEM: TIntegerField;
    qrImprNfItemUN_PECA: TStringField;
    qrImprNfItemSTRIBUT: TIntegerField;
    qrImprNfItemVLR_IPI_ITEM: TBCDField;
    qrImprNfItemALIQ_IPI_ITEM: TBCDField;
    qrImprNfItemALIQ_ICMS_ITEM: TBCDField;
    qrImprNfItemNR_SERIE_ITEM: TMemoField;
    qrImprNfNFISCAL_SQ: TIntegerField;
    qrImprNfNOME_CLIENTE: TStringField;
    qrImprNfCODIGO_CLIENTE: TStringField;
    qrImprNfINSCR_ESTADUAL: TStringField;
    qrImprNfENDERECO: TStringField;
    qrImprNfCOMPL_ENDERECO: TStringField;
    qrImprNfNUMERO: TStringField;
    qrImprNfENT_SAI: TStringField;
    qrImprNfBAIRRO: TStringField;
    qrImprNfCIDADE: TStringField;
    qrImprNfESTADO: TStringField;
    qrImprNfCEP: TStringField;
    qrImprNfDTEMISSAO_NFISCAL: TDateTimeField;
    qrImprNfDTSAIDA_NFISCAL: TDateTimeField;
    qrImprNfDESCRICAO_NATUREZA_NFISCAL: TStringField;
    qrImprNfCFO: TStringField;
    qrImprNfMENSAGEM: TMemoField;
    qrImprNfBASE_ICMS: TBCDField;
    qrImprNfVLR_FRETE: TBCDField;
    qrImprNfVLR_ICMS: TBCDField;
    qrImprNfBASE_ICMS_SUBST: TBCDField;
    qrImprNfVLR_SEGURO: TBCDField;
    qrImprNfVLR_DESP_ACESS: TBCDField;
    qrImprNfVLR_ICMS_SUBST: TBCDField;
    qrImprNfVLR_TOTAL: TBCDField;
    qrImprNfVLR_PRODUTOS: TBCDField;
    qrImprNfVLR_IPI: TBCDField;
    qrImprNfNOME_TRANSPORTADORA: TStringField;
    qrImprNfENDERECO_TRANSPORTADORA: TStringField;
    qrImprNfINSCR_ESTADUAL_TRANSP: TStringField;
    qrImprNfQTDE_TRANSP: TIntegerField;
    qrImprNfESTADO_TRANSPORTADORA: TStringField;
    qrImprNfMUNICIPIO_TRANSPORTADORA: TStringField;
    qrImprNfPLIQUIDO_TRANSP: TStringField;
    qrImprNfPBRUTO_TRANSP: TStringField;
    qrImprNfNUMERO_TRANSP: TStringField;
    qrImprNfMARCA_TRANSP: TStringField;
    qrImprNfESPECIE_TRANSP: TStringField;
    qrImprNfCODIGO_TRANSPORTADORA: TStringField;
    qrImprNfUF_PLACA_TRANSP: TStringField;
    qrImprNfPLACA_TRANSP: TStringField;
    qrImprNfFRETE_TRANSP: TStringField;
    qrImprNfCLASS_FISCAL1: TIntegerField;
    qrImprNfCLASS_FISCAL2: TIntegerField;
    qrImprNfCLASS_FISCAL3: TIntegerField;
    qrImprNfCLASS_FISCAL4: TIntegerField;
    qrImprNfCLASS_FISCAL5: TIntegerField;
    qrImprNfCLASS_FISCAL6: TIntegerField;
    qrImprNfCLASS_FISCAL7: TIntegerField;
    qrImprNfDDD_FONE1: TStringField;
    qrImprNfNUMERO_FONE1: TStringField;
    qrImprNfCOMPL_FONE1: TStringField;
    qrImprNfNUMERO_NFISCAL: TIntegerField;
    qrImprNfPARCELAS: TIntegerField;
    qrImprNfCOND_PAGTO_SQ: TIntegerField;
    qrImprNfNATUREZA_SQ: TIntegerField;
    qrImprNfDIAS_DEMONSTRACAO: TIntegerField;
    qrImprPedPEDIDO_SQ: TIntegerField;
    qrImprPedDDD_FONE1: TStringField;
    qrImprPedNUMERO_FONE1: TStringField;
    qrImprPedCOMPL_FONE1: TStringField;
    qrImprPedDDD_CELULAR: TStringField;
    qrImprPedNUMERO_CELULAR: TStringField;
    qrImprPedCOMPL_CELULAR: TStringField;
    qrImprPedENDERECO: TStringField;
    qrImprPedNUMERO: TStringField;
    qrImprPedCOMPL_ENDERECO: TStringField;
    qrImprPedDDD_FONE2: TStringField;
    qrImprPedNUMERO_FONE2: TStringField;
    qrImprPedCOMPL_FONE2: TStringField;
    qrImprPedDDD_FONE3: TStringField;
    qrImprPedNUMERO_FONE3: TStringField;
    qrImprPedCOMPL_FONE3: TStringField;
    qrImprPedDDD_FAX: TStringField;
    qrImprPedNUMERO_FAX: TStringField;
    qrImprPedCOMPL_FAX: TStringField;
    qrImprPedCODIGO_CLIENTE: TStringField;
    qrImprPedNOME_CLIENTE: TStringField;
    qrImprPedCONTATO: TStringField;
    qrImprPedINSCR_ESTADUAL: TStringField;
    qrImprPedBAIRRO: TStringField;
    qrImprPedCIDADE: TStringField;
    qrImprPedESTADO: TStringField;
    qrImprPedPAIS: TStringField;
    qrImprPedCEP: TStringField;
    qrImprPedNOME_VENDEDOR: TStringField;
    qrImprPedCODIGO_VENDEDOR: TIntegerField;
    qrImprPedTIPO_NFISCAL: TIntegerField;
    qrImprPedDESCRICAO_NATUREZA: TStringField;
    qrImprPedCFO: TStringField;
    qrImprPedCODIGO_TRANSPORTADORA: TStringField;
    qrImprPedNOME_TRANSPORTADORA: TStringField;
    qrImprPedOBSERVACAO_NAT: TMemoField;
    qrImprPedVLR_FRETE: TBCDField;
    qrImprPedFRETE_TRANSP: TStringField;
    qrImprPedDIAS_DEMONSTRACAO: TIntegerField;
    qrImprPedDATA_PEDIDO: TDateTimeField;
    qrImprPedNUMERO_PEDIDO: TIntegerField;
    qrImprPedCOTACAO_DOLAR: TBCDField;
    qrImprPedOBSERVACAO_PED: TMemoField;
    qrImprPedOBSERVACAO_NF: TMemoField;
    qrImprPedVLR_PRODUTOS: TBCDField;
    qrImprPedVLR_IPI: TBCDField;
    qrImprPedVLR_ICMS: TBCDField;
    qrImprPedD00: TIntegerField;
    qrImprPedD01: TIntegerField;
    qrImprPedD02: TIntegerField;
    qrImprPedD03: TIntegerField;
    qrImprPedD04: TIntegerField;
    qrImprPedD05: TIntegerField;
    qrImprPedD06: TIntegerField;
    qrImprPedD07: TIntegerField;
    qrImprPedD08: TIntegerField;
    qrImprPedD09: TIntegerField;
    qrImprPedPARCELAS: TIntegerField;
    qrImprPedDESCRICAO_COND_PAGTO: TStringField;
    procedure RemoteDataModuleCreate(Sender: TObject);
    procedure qrImprNfSerieBeforeOpen(DataSet: TDataSet);
    procedure qrImprHistClientes2BeforeOpen(DataSet: TDataSet);
    procedure qrImprDemPrevBeforeOpen(DataSet: TDataSet);
    procedure qrImprNfVendBeforeOpen(DataSet: TDataSet);
    procedure qrImprNfFechBeforeOpen(DataSet: TDataSet);
  private
    { Private declarations }
  protected
    class procedure UpdateRegistry(Register: Boolean; const ClassID, ProgID: string); override;
  public
    { Public declarations }
  end;

implementation

uses uSetup;

{$R *.DFM}

class procedure TServerImpr.UpdateRegistry(Register: Boolean; const ClassID, ProgID: string);
begin
  if Register then
  begin
    inherited UpdateRegistry(Register, ClassID, ProgID);
    EnableSocketTransport(ClassID);
    EnableWebTransport(ClassID);
  end else
  begin
    DisableSocketTransport(ClassID);
    DisableWebTransport(ClassID);
    inherited UpdateRegistry(Register, ClassID, ProgID);
  end;
end;

procedure TServerImpr.RemoteDataModuleCreate(Sender: TObject);
var
  Reg: TRegistry;
  banco: string;
begin
  Reg := TRegistry.Create;
  try
    Reg.RootKey := HKEY_CURRENT_USER;
    if Reg.OpenKey('\Software\MSystem', True) then
    begin
      banco    := Reg.ReadString ('FBBanco');
    end;
  finally
    Reg.CloseKey;
    Reg.Free;
  end;
  try
    DBConn.Connected    := True;
  except
    Exception.Create('Nao foi possível conectar-se ao banco de dados!');
  end;
end;

procedure TServerImpr.qrImprNfSerieBeforeOpen(DataSet: TDataSet);
begin
 qrImprNfSerie.ParamByName('NR_SERIE_ITEM').AsString := '%' + qrImprNfSerie.ParamByName('NR_SERIE_ITEM').AsString + '%';
end;

procedure TServerImpr.qrImprHistClientes2BeforeOpen(DataSet: TDataSet);
begin
  qrImprHistClientes2.ParamByName('DT_INICIO').AsString  := FormatDateTime ('yyyy-mm-dd', qrImprHistClientes2.ParamByName('DT_INICIO').asDate);
  qrImprHistClientes2.ParamByName('DT_TERMINO').AsString := FormatDateTime ('yyyy-mm-dd', qrImprHistClientes2.ParamByName('DT_TERMINO').asDate);
end;

procedure TServerImpr.qrImprDemPrevBeforeOpen(DataSet: TDataSet);
begin
  qrImprDemPrev.ParamByName('INICIO').AsString := FormatDateTime ('yyyy-mm-dd', qrImprDemPrev.ParamByName('INICIO').asDate);
  qrImprDemPrev.ParamByName('FIM').AsString    := FormatDateTime ('yyyy-mm-dd', qrImprDemPrev.ParamByName('FIM').asDate);
end;

procedure TServerImpr.qrImprNfVendBeforeOpen(DataSet: TDataSet);
begin
  qrImprNfVend.ParamByName('DT_INICIO').AsString  := FormatDateTime ('yyyy-mm-dd', qrImprNfVend.ParamByName('DT_INICIO').asDate);
  qrImprNfVend.ParamByName('DT_TERMINO').AsString := FormatDateTime ('yyyy-mm-dd', qrImprNfVend.ParamByName('DT_TERMINO').asDate);
end;

procedure TServerImpr.qrImprNfFechBeforeOpen(DataSet: TDataSet);
begin
  qrImprNfFech.ParamByName('DT_INICIO').AsString  := FormatDateTime ('yyyy-mm-dd', qrImprNfFech.ParamByName('DT_INICIO').asDate);
  qrImprNfFech.ParamByName('DT_TERMINO').AsString := FormatDateTime ('yyyy-mm-dd', qrImprNfFech.ParamByName('DT_TERMINO').asDate);
end;

initialization
  TComponentFactory.Create(ComServer, TServerImpr,
    Class_ServerImpr, ciMultiInstance, tmApartment);
end.
