unit UDMServerLista;

{$WARN SYMBOL_PLATFORM OFF}

interface

uses
  Windows, Messages, SysUtils, Classes, ComServ, ComObj, VCLCom, DataBkr,
  DBClient, PrServer_TLB, StdVcl, DB, IBDatabase, IBCustomDataSet, IBQuery,
  Provider, IBStoredProc, Registry, Dialogs, DBTables, ScktComp, DBXpress,
  SqlExpr;

type
  TServerLista = class(TRemoteDataModule, IServerLista)
    dsListaPedidos: TDataSource;
    dsListaNfiscais: TDataSource;
    dspListaPecas: TDataSetProvider;
    dspListaClientes: TDataSetProvider;
    dspListaCondPagto: TDataSetProvider;
    dspListaNaturezas: TDataSetProvider;
    dspListaUsuarios: TDataSetProvider;
    dspListaNBM: TDataSetProvider;
    dspListaPedidos: TDataSetProvider;
    dspListaPedidosItens: TDataSetProvider;
    dspListaDuplicatas: TDataSetProvider;
    dspListaTransportadoras: TDataSetProvider;
    dspListaNfiscais: TDataSetProvider;
    dspListaNfiscaisItens: TDataSetProvider;
    dspLista: TDataSetProvider;
    dspCep: TDataSetProvider;
    dspBuscaPecas: TDataSetProvider;
    dspBuscaClientes: TDataSetProvider;
    dspListaKardexPecas: TDataSetProvider;
    dspListaModelos: TDataSetProvider;
    dspListaAssistencias: TDataSetProvider;
    dsListaAssistencias: TDataSource;
    dspListaAssistenciasEquip: TDataSetProvider;
    dspListaAssistenciasItens: TDataSetProvider;
    dspListaVendedores: TDataSetProvider;
    dspListaAcessos: TDataSetProvider;
    dspListaNfiscaisTotais: TDataSetProvider;
    Session1: TSession;
    DBConn: TDatabase;
    qrLista: TQuery;
    qrListaClientes: TQuery;
    qrListaCondPagto: TQuery;
    qrListaNaturezas: TQuery;
    qrListaPecas: TQuery;
    qrListaNBM: TQuery;
    qrListaPedidos: TQuery;
    qrListaPedidosItens: TQuery;
    qrListaUsuarios: TQuery;
    qrListaVendedores: TQuery;
    qrListaAcessos: TQuery;
    qrListaTransportadoras: TQuery;
    qrListaNfiscaisTotais: TQuery;
    qrListaNfiscais: TQuery;
    qrListaNfiscaisItens: TQuery;
    qrListaKardexPecas: TQuery;
    qrListaDuplicatas: TQuery;
    qrListaModelos: TQuery;
    qrListaAssistencias: TQuery;
    qrListaAssistenciasEquip: TQuery;
    qrListaAssistenciasItens: TQuery;
    qrBuscaPecas: TQuery;
    qrBuscaClientes: TQuery;
    qrBuscaClientescliente_sq: TIntegerField;
    qrBuscaClientesCODIGO_CLIENTE: TStringField;
    qrBuscaClientesNOME_CLIENTE: TStringField;
    qrBuscaClientesINSCR_ESTADUAL: TStringField;
    qrBuscaClientesENDERECO: TStringField;
    qrBuscaClientesNUMERO: TStringField;
    qrBuscaClientesBAIRRO: TStringField;
    qrBuscaClientesCOMPL_ENDERECO: TStringField;
    qrBuscaClientesCIDADE: TStringField;
    qrBuscaClientesESTADO: TStringField;
    qrBuscaClientesCEP: TStringField;
    qrBuscaClientesDDD_FONE1: TStringField;
    qrBuscaClientesNUMERO_FONE1: TStringField;
    qrBuscaClientesCOMPL_FONE1: TStringField;
    qrBuscaClientesDDD_FONE2: TStringField;
    qrBuscaClientesNUMERO_FONE2: TStringField;
    qrBuscaClientesCOMPL_FONE2: TStringField;
    qrBuscaClientesDDD_FONE3: TStringField;
    qrBuscaClientesNUMERO_FONE3: TStringField;
    qrBuscaClientesCOMPL_FONE3: TStringField;
    qrBuscaClientesDDD_CELULAR: TStringField;
    qrBuscaClientesNUMERO_CELULAR: TStringField;
    qrBuscaClientesCOMPL_CELULAR: TStringField;
    qrBuscaClientesDDD_FAX: TStringField;
    qrBuscaClientesNUMERO_FAX: TStringField;
    qrBuscaClientesCOMPL_FAX: TStringField;
    qrBuscaClientesE_MAIL: TStringField;
    qrBuscaClientesWEB_SITE: TStringField;
    qrBuscaClientesCONTATO: TStringField;
    qrBuscaClientesPAIS: TStringField;
    qrBuscaClientesREVENDA: TStringField;
    qrBuscaClientesBIRO: TStringField;
    qrBuscaClientesCAPITAL_ATUAL: TBCDField;
    qrBuscaClientesNOME_FANTASIA: TStringField;
    qrBuscaClientesRAMO_ATIVIDADE_SQ: TIntegerField;
    qrBuscaClientesFATURAMENTO_MENSAL: TBCDField;
    qrBuscaClientesDATA_FUNDACAO: TDateTimeField;
    qrBuscaClientesINSCR_MUNICIPAL: TStringField;
    qrBuscaClientesDATA_CADASTRO: TDateTimeField;
    qrBuscaClientesDATA_ALT: TDateTimeField;
    qrBuscaClientesUSUARIO_SQ_ALT: TIntegerField;
    Query1: TQuery;
    qrBuscaClientesTRANSPORTADORA_SQ: TIntegerField;
    DBCep: TDatabase;
    qrCep: TQuery;
    qrCepCEP: TStringField;
    qrCepLOGRADOURO: TStringField;
    qrCepBAIRRO: TStringField;
    qrCepCIDADE: TStringField;
    qrCepUF: TStringField;
    dspListaClassificacao: TDataSetProvider;
    qrListaClassificacao: TQuery;
    qrBuscaClientesOBSERVACAO: TMemoField;
    qrBuscaClientesCLASSIFICACAO_SQ: TIntegerField;
    dspListaNFServicos: TDataSetProvider;
    qrListaNFServicos: TQuery;
    dspListaKardexModelos: TDataSetProvider;
    qrListaKardexModelos: TQuery;
    qrBuscaPecasPECA_SQ: TIntegerField;
    qrBuscaPecasCODIGO_PECA: TStringField;
    qrBuscaPecasDESCRICAO_PECA: TStringField;
    qrBuscaPecasQTDE_PECA_LOJA: TIntegerField;
    qrBuscaPecasQTDE_PECA_ARMAZEM: TIntegerField;
    qrBuscaPecasQTDE_PECA_DEMO: TIntegerField;
    qrBuscaPecasQTDE_PECA_DEFEITO: TIntegerField;
    qrBuscaPecasQTDE_PECA_EM_USO: TIntegerField;
    qrBuscaPecasQTDE_PECA_BACKUP: TIntegerField;
    qrBuscaPecasQTDE_PECA_DEMO_CLI: TIntegerField;
    qrBuscaPecasQTDE_PECA_HLC: TIntegerField;
    qrBuscaPecasNBM_SQ: TIntegerField;
    qrBuscaPecasMODELO_SQ: TIntegerField;
    qrBuscaPecasUN_PECA: TStringField;
    qrBuscaPecasMARCA_PECA: TStringField;
    qrBuscaPecasPRECO_UNIT_PECA: TBCDField;
    qrBuscaPecasTIPO_PECA: TIntegerField;
    qrListaClientesCLIENTE_SQ: TIntegerField;
    qrListaClientesCODIGO_CLIENTE: TStringField;
    qrListaClientesNOME_CLIENTE: TStringField;
    qrListaClientesINSCR_ESTADUAL: TStringField;
    qrListaClientesENDERECO: TStringField;
    qrListaClientesNUMERO: TStringField;
    qrListaClientesBAIRRO: TStringField;
    qrListaClientesCOMPL_ENDERECO: TStringField;
    qrListaClientesCIDADE: TStringField;
    qrListaClientesESTADO: TStringField;
    qrListaClientesCEP: TStringField;
    qrListaClientesDDD_FONE1: TStringField;
    qrListaClientesNUMERO_FONE1: TStringField;
    qrListaClientesCOMPL_FONE1: TStringField;
    qrListaClientesDDD_FONE2: TStringField;
    qrListaClientesNUMERO_FONE2: TStringField;
    qrListaClientesCOMPL_FONE2: TStringField;
    qrListaClientesDDD_FONE3: TStringField;
    qrListaClientesNUMERO_FONE3: TStringField;
    qrListaClientesCOMPL_FONE3: TStringField;
    qrListaClientesDDD_CELULAR: TStringField;
    qrListaClientesNUMERO_CELULAR: TStringField;
    qrListaClientesCOMPL_CELULAR: TStringField;
    qrListaClientesDDD_FAX: TStringField;
    qrListaClientesNUMERO_FAX: TStringField;
    qrListaClientesCOMPL_FAX: TStringField;
    qrListaClientesE_MAIL: TStringField;
    qrListaClientesWEB_SITE: TStringField;
    qrListaClientesCONTATO: TStringField;
    qrListaClientesPAIS: TStringField;
    qrListaClientesOBSERVACAO: TMemoField;
    qrListaClientesREVENDA: TStringField;
    qrListaClientesBIRO: TStringField;
    qrListaClientesCAPITAL_ATUAL: TBCDField;
    qrListaClientesNOME_FANTASIA: TStringField;
    qrListaClientesRAMO_ATIVIDADE_SQ: TIntegerField;
    qrListaClientesFATURAMENTO_MENSAL: TBCDField;
    qrListaClientesDATA_FUNDACAO: TDateTimeField;
    qrListaClientesINSCR_MUNICIPAL: TStringField;
    qrListaClientesDATA_CADASTRO: TDateTimeField;
    qrListaClientesDATA_ALT: TDateTimeField;
    qrListaClientesUSUARIO_SQ_ALT: TIntegerField;
    qrListaClientesTRANSPORTADORA_SQ: TIntegerField;
    qrListaClientesCLASSIFICACAO_SQ: TIntegerField;
    qrListaNaturezasNATUREZA_SQ: TIntegerField;
    qrListaNaturezasCODIGO_NATUREZA: TIntegerField;
    qrListaNaturezasDESCRICAO_NATUREZA: TStringField;
    qrListaNaturezasCFO: TStringField;
    qrListaNaturezasALIQ_ICMS: TBCDField;
    qrListaNaturezasALIQ_IPI: TBCDField;
    qrListaNaturezasENT_SAI: TStringField;
    qrListaNaturezasOBSERVACAO: TMemoField;
    qrListaNaturezasUF01: TStringField;
    qrListaNaturezasUF02: TStringField;
    qrListaNaturezasUF03: TStringField;
    qrListaNaturezasUF04: TStringField;
    qrListaNaturezasUF05: TStringField;
    qrListaNaturezasUF06: TStringField;
    qrListaNaturezasUF07: TStringField;
    qrListaNaturezasUF08: TStringField;
    qrListaNaturezasUF09: TStringField;
    qrListaNaturezasUF10: TStringField;
    qrListaNaturezasUF11: TStringField;
    qrListaNaturezasUF12: TStringField;
    qrListaNaturezasUF13: TStringField;
    qrListaNaturezasUF14: TStringField;
    qrListaNaturezasUF15: TStringField;
    qrListaNaturezasUF16: TStringField;
    qrListaNaturezasUF17: TStringField;
    qrListaNaturezasUF18: TStringField;
    qrListaNaturezasUF19: TStringField;
    qrListaNaturezasUF20: TStringField;
    qrListaNaturezasUF21: TStringField;
    qrListaNaturezasUF22: TStringField;
    qrListaNaturezasUF23: TStringField;
    qrListaNaturezasUF24: TStringField;
    qrListaNaturezasUF25: TStringField;
    qrListaNaturezasUF26: TStringField;
    qrListaNaturezasUF27: TStringField;
    qrListaNaturezasUF28: TStringField;
    qrListaNaturezasUF29: TStringField;
    qrListaNaturezasUF30: TStringField;
    qrListaNaturezasISENCAO_IPI: TStringField;
    qrListaNaturezasISENCAO_ICMS: TStringField;
    qrListaNaturezasDESCRICAO_NATUREZA_NFISCAL: TStringField;
    qrListaNaturezasTIPO_NFISCAL: TIntegerField;
    qrListaCondPagtoCOND_PAGTO_SQ: TIntegerField;
    qrListaCondPagtoCODIGO_COND_PAGTO: TIntegerField;
    qrListaCondPagtoDESCRICAO_COND_PAGTO: TStringField;
    qrListaCondPagtoPARCELAS: TIntegerField;
    qrListaCondPagtoD00: TIntegerField;
    qrListaCondPagtoD01: TIntegerField;
    qrListaCondPagtoD02: TIntegerField;
    qrListaCondPagtoD03: TIntegerField;
    qrListaCondPagtoD04: TIntegerField;
    qrListaCondPagtoD05: TIntegerField;
    qrListaCondPagtoD06: TIntegerField;
    qrListaCondPagtoD07: TIntegerField;
    qrListaCondPagtoD08: TIntegerField;
    qrListaCondPagtoD09: TIntegerField;
    qrListaKardexModelosKARDEX_MOD_SQ: TIntegerField;
    qrListaKardexModelosMODELO_SQ: TIntegerField;
    qrListaKardexModelosTIPO_MOV: TStringField;
    qrListaKardexModelosQTDE: TIntegerField;
    qrListaKardexModelosVALOR: TBCDField;
    qrListaKardexModelosDATA: TDateTimeField;
    qrListaKardexModelosNFISCAL: TIntegerField;
    qrListaKardexModelosUSUARIO_SQ: TIntegerField;
    qrListaKardexModelosNR_SERIE: TMemoField;
    qrListaNFServicosNF_SERVICO_SQ: TIntegerField;
    qrListaNFServicosNUMERO_NF_SERVICO: TIntegerField;
    qrListaNFServicosDATA_NF_SERVICO: TDateTimeField;
    qrListaNFServicosCLIENTE_SQ: TIntegerField;
    qrListaNFServicosTTL_NF_SERVICO: TBCDField;
    qrListaNFServicosALIQ_ISS_NF_SERVICO: TBCDField;
    qrListaNFServicosVLR_ISS_NF_SERVICO: TBCDField;
    qrListaNFServicosNOME_CLIENTE: TStringField;
    qrListaClassificacaoCLASSIFICACAO_SQ: TIntegerField;
    qrListaClassificacaoCODIGO_CLASSIFICACAO: TStringField;
    qrListaClassificacaoLIMITE_MINIMO: TBCDField;
    qrListaClassificacaoLIMITE_MAXIMO: TBCDField;
    qrListaClassificacaoMESES_BONUS: TIntegerField;
    qrListaAssistenciasASSISTENCIA_SQ: TIntegerField;
    qrListaAssistenciasNUMERO_ASSISTENCIA: TIntegerField;
    qrListaAssistenciasDATA_CHAMADO: TDateTimeField;
    qrListaAssistenciasDATA_ASSISTENCIA: TDateTimeField;
    qrListaAssistenciasCOTACAO_DOLAR: TBCDField;
    qrListaAssistenciasCLIENTE_SQ: TIntegerField;
    qrListaAssistenciasCOND_PAGTO_SQ: TIntegerField;
    qrListaAssistenciasDESP_CHAMADO: TBCDField;
    qrListaAssistenciasDESP_HTEC_AD: TBCDField;
    qrListaAssistenciasDESP_DESLOC: TBCDField;
    qrListaAssistenciasVLR_PECAS: TBCDField;
    qrListaAssistenciasVLR_TOTAL: TBCDField;
    qrListaAssistenciasHORA_INICIO: TTimeField;
    qrListaAssistenciasHORA_FIM: TTimeField;
    qrListaAssistenciasGARANTIA: TStringField;
    qrListaAssistenciasCONTRATO: TStringField;
    qrListaAssistenciasSERVICOS: TMemoField;
    qrListaAssistenciasEquipASSISTENCIA_EQUIP_SQ: TIntegerField;
    qrListaAssistenciasEquipASSISTENCIA_SQ: TIntegerField;
    qrListaAssistenciasEquipMODELO_SQ: TIntegerField;
    qrListaAssistenciasEquipNR_SERIE_EQUIP: TMemoField;
    qrListaAssistenciasEquipDEFEITO: TBlobField;
    qrListaAssistenciasEquipDESCRICAO_MODELO: TStringField;
    qrListaAssistenciasItensASSISTENCIA_ITEM_SQ: TIntegerField;
    qrListaAssistenciasItensASSISTENCIA_SQ: TIntegerField;
    qrListaAssistenciasItensPECA_SQ: TIntegerField;
    qrListaAssistenciasItensQTDE_ASSISTENCIA_ITEM: TIntegerField;
    qrListaAssistenciasItensPRECO_UNIT: TBCDField;
    qrListaAssistenciasItensDESCRICAO_PECA: TStringField;
    qrListaModelosMODELO_SQ: TIntegerField;
    qrListaModelosCODIGO_MODELO: TStringField;
    qrListaModelosDESCRICAO_MODELO: TStringField;
    qrListaModelosNBM_SQ: TIntegerField;
    qrListaModelosUN_MODELO: TStringField;
    qrListaModelosMARCA_MODELO: TStringField;
    qrListaModelosPRECO_UNIT_MODELO: TBCDField;
    qrListaDuplicatasDUPLICATA_SQ: TIntegerField;
    qrListaDuplicatasNUMERO_DUPLICATA: TIntegerField;
    qrListaDuplicatasITEM_DUPLICATA: TIntegerField;
    qrListaDuplicatasSEQ_DUPLICATA: TIntegerField;
    qrListaDuplicatasNFISCAL_SQ: TIntegerField;
    qrListaDuplicatasVALOR_DUPLICATA: TBCDField;
    qrListaDuplicatasDTEMISSAO_DUPLICATA: TDateTimeField;
    qrListaDuplicatasDTVENCTO_DUPLICATA: TDateTimeField;
    qrListaDuplicatasDTPGTO_DUPLICATA: TDateTimeField;
    qrListaDuplicatasVALORPG_DUPLICATA: TBCDField;
    qrListaKardexPecasKARDEX_PECA_SQ: TIntegerField;
    qrListaKardexPecasPECA_SQ: TIntegerField;
    qrListaKardexPecasTIPO_MOV: TStringField;
    qrListaKardexPecasQTDE: TIntegerField;
    qrListaKardexPecasVALOR: TBCDField;
    qrListaKardexPecasDATA: TDateTimeField;
    qrListaKardexPecasNFISCAL: TIntegerField;
    qrListaKardexPecasUSUARIO_SQ: TIntegerField;
    qrListaKardexPecasNR_SERIE: TMemoField;
    qrListaNfiscaisNFISCAL_SQ: TIntegerField;
    qrListaNfiscaisNUMERO_NFISCAL: TIntegerField;
    qrListaNfiscaisDTEMISSAO_NFISCAL: TDateTimeField;
    qrListaNfiscaisDTSAIDA_NFISCAL: TDateTimeField;
    qrListaNfiscaisPEDIDO_SQ: TIntegerField;
    qrListaNfiscaisCLIENTE_SQ: TIntegerField;
    qrListaNfiscaisCOND_PAGTO_SQ: TIntegerField;
    qrListaNfiscaisNATUREZA_SQ: TIntegerField;
    qrListaNfiscaisTRANSPORTADORA_SQ: TIntegerField;
    qrListaNfiscaisBASE_ICMS: TBCDField;
    qrListaNfiscaisVLR_ICMS: TBCDField;
    qrListaNfiscaisBASE_ICMS_SUBST: TBCDField;
    qrListaNfiscaisVLR_ICMS_SUBST: TBCDField;
    qrListaNfiscaisVLR_PRODUTOS: TBCDField;
    qrListaNfiscaisVLR_FRETE: TBCDField;
    qrListaNfiscaisVLR_SEGURO: TBCDField;
    qrListaNfiscaisVLR_DESP_ACESS: TBCDField;
    qrListaNfiscaisVLR_IPI: TBCDField;
    qrListaNfiscaisVLR_TOTAL: TBCDField;
    qrListaNfiscaisFRETE_TRANSP: TStringField;
    qrListaNfiscaisPLACA_TRANSP: TStringField;
    qrListaNfiscaisUF_PLACA_TRANSP: TStringField;
    qrListaNfiscaisQTDE_TRANSP: TIntegerField;
    qrListaNfiscaisESPECIE_TRANSP: TStringField;
    qrListaNfiscaisMARCA_TRANSP: TStringField;
    qrListaNfiscaisNUMERO_TRANSP: TStringField;
    qrListaNfiscaisPBRUTO_TRANSP: TStringField;
    qrListaNfiscaisPLIQUIDO_TRANSP: TStringField;
    qrListaNfiscaisCLASS_FISCAL1: TIntegerField;
    qrListaNfiscaisCLASS_FISCAL2: TIntegerField;
    qrListaNfiscaisCLASS_FISCAL3: TIntegerField;
    qrListaNfiscaisCLASS_FISCAL4: TIntegerField;
    qrListaNfiscaisCLASS_FISCAL5: TIntegerField;
    qrListaNfiscaisCLASS_FISCAL6: TIntegerField;
    qrListaNfiscaisCLASS_FISCAL7: TIntegerField;
    qrListaNfiscaisMENSAGEM: TMemoField;
    qrListaNfiscaisCANCELADA: TStringField;
    qrListaNfiscaisDIAS_DEMONSTRACAO: TIntegerField;
    qrListaNfiscaisCOTACAO_DOLAR: TBCDField;
    qrListaNfiscaisNR_NFISCAL_RETORNO: TIntegerField;
    qrListaNfiscaisDT_NFISCAL_RETORNO: TDateTimeField;
    qrListaNfiscaisCONCLUIDA: TStringField;
    qrListaNfiscaisVENDEDOR_SQ: TIntegerField;
    qrListaNfiscaisNF_MANUAL: TStringField;
    qrListaNfiscaisRETORNO_PRODUTO: TStringField;
    qrListaNfiscaisRETORNO_OBSERVACAO: TMemoField;
    qrListaNfiscaisItensNFISCAL_ITEM_SQ: TIntegerField;
    qrListaNfiscaisItensNFISCAL_SQ: TIntegerField;
    qrListaNfiscaisItensITEM: TIntegerField;
    qrListaNfiscaisItensTIPO_ITEM: TStringField;
    qrListaNfiscaisItensPECA_SQ: TIntegerField;
    qrListaNfiscaisItensMODELO_SQ: TIntegerField;
    qrListaNfiscaisItensNR_SERIE_ITEM: TMemoField;
    qrListaNfiscaisItensCLASS_FISCAL: TStringField;
    qrListaNfiscaisItensSTRIBUT: TIntegerField;
    qrListaNfiscaisItensQTDE_ITEM: TIntegerField;
    qrListaNfiscaisItensVLR_UNIT_ITEM: TBCDField;
    qrListaNfiscaisItensVLR_TOTAL_ITEM: TBCDField;
    qrListaNfiscaisItensALIQ_ICMS_ITEM: TBCDField;
    qrListaNfiscaisItensALIQ_IPI_ITEM: TBCDField;
    qrListaNfiscaisItensVLR_ICMS_ITEM: TBCDField;
    qrListaNfiscaisItensVLR_IPI_ITEM: TBCDField;
    qrListaNfiscaisItensCODIGO_PECA: TStringField;
    qrListaNfiscaisItensDESCRICAO_PECA: TStringField;
    qrListaNfiscaisItensQTDE_PECA_LOJA: TIntegerField;
    qrListaNfiscaisItensQTDE_PECA_ARMAZEM: TIntegerField;
    qrListaNfiscaisItensCODIGO_NBM: TStringField;
    qrListaNfiscaisTotaisULTIMA_VENDA: TDateTimeField;
    qrListaNfiscaisTotaisPRIMEIRA_VENDA: TDateTimeField;
    qrListaNfiscaisTotaisMAIOR_VENDA: TBCDField;
    qrListaNfiscaisTotaisMENOR_VENDA: TBCDField;
    qrListaNfiscaisTotaisTOTAL_VENDA: TBCDField;
    qrListaTransportadorasTRANSPORTADORA_SQ: TIntegerField;
    qrListaTransportadorasCODIGO_TRANSPORTADORA: TStringField;
    qrListaTransportadorasNOME_TRANSPORTADORA: TStringField;
    qrListaTransportadorasENDERECO_TRANSPORTADORA: TStringField;
    qrListaTransportadorasMUNICIPIO_TRANSPORTADORA: TStringField;
    qrListaTransportadorasESTADO_TRANSPORTADORA: TStringField;
    qrListaTransportadorasINSCR_ESTADUAL: TStringField;
    qrListaTransportadorasDDD_FONE: TStringField;
    qrListaTransportadorasNUMERO_FONE: TStringField;
    qrListaTransportadorasCOMPL_FONE: TStringField;
    qrListaAcessosACESSO_SQ: TIntegerField;
    qrListaAcessosNOME_PROGRAMA: TStringField;
    qrListaAcessosUSUARIO_SQ: TIntegerField;
    qrListaAcessosVISUALIZAR: TStringField;
    qrListaAcessosCRIAR: TStringField;
    qrListaAcessosEDITAR: TStringField;
    qrListaAcessosAPAGAR: TStringField;
    qrListaVendedoresVENDEDOR_SQ: TIntegerField;
    qrListaVendedoresCODIGO_VENDEDOR: TIntegerField;
    qrListaVendedoresNOME_VENDEDOR: TStringField;
    qrListaUsuariosUSUARIO_SQ: TIntegerField;
    qrListaUsuariosCODIGO_USUARIO: TStringField;
    qrListaUsuariosNOME_USUARIO: TStringField;
    qrListaUsuariosSENHA_USUARIO: TStringField;
    qrListaUsuariosERRO_EMAIL_FROM: TStringField;
    qrListaUsuariosERRO_NOME_FROM: TStringField;
    qrListaUsuariosERRO_EMAIL_TO: TStringField;
    qrListaUsuariosERRO_NOME_TO: TStringField;
    qrListaUsuariosERRO_SMTP: TStringField;
    qrListaUsuariosERRO_USERNAME: TStringField;
    qrListaUsuariosERRO_PASSWORD: TStringField;
    qrListaPedidosPEDIDO_SQ: TIntegerField;
    qrListaPedidosCLIENTE_SQ: TIntegerField;
    qrListaPedidosDATA_PEDIDO: TDateTimeField;
    qrListaPedidosCOND_PAGTO_SQ: TIntegerField;
    qrListaPedidosNATUREZA_SQ: TIntegerField;
    qrListaPedidosCOTACAO_DOLAR: TBCDField;
    qrListaPedidosOBSERVACAO_PED: TMemoField;
    qrListaPedidosOBSERVACAO_NF: TMemoField;
    qrListaPedidosTRANSPORTADORA_SQ: TIntegerField;
    qrListaPedidosVLR_FRETE: TBCDField;
    qrListaPedidosFRETE_TRANSP: TStringField;
    qrListaPedidosNFISCAL_SQ: TIntegerField;
    qrListaPedidosVLR_DESC: TBCDField;
    qrListaPedidosPCT_DESC: TBCDField;
    qrListaPedidosVLR_ICMS: TBCDField;
    qrListaPedidosVLR_IPI: TBCDField;
    qrListaPedidosVLR_PRODUTOS: TBCDField;
    qrListaPedidosBASE_ICMS: TBCDField;
    qrListaPedidosNUMERO_PEDIDO: TIntegerField;
    qrListaPedidosDIAS_DEMONSTRACAO: TIntegerField;
    qrListaPedidosPCT_JUROS: TBCDField;
    qrListaPedidosVLR_JUROS: TBCDField;
    qrListaPedidosVENDEDOR_SQ: TIntegerField;
    qrListaPedidosNUMERO_NFISCAL: TIntegerField;
    qrListaPedidosItensPEDIDO_ITEM_SQ: TIntegerField;
    qrListaPedidosItensPEDIDO_SQ: TIntegerField;
    qrListaPedidosItensTIPO_ITEM: TStringField;
    qrListaPedidosItensPECA_SQ: TIntegerField;
    qrListaPedidosItensMODELO_SQ: TIntegerField;
    qrListaPedidosItensQTDE_PEDIDO_ITEM: TIntegerField;
    qrListaPedidosItensNR_SERIE_ITEM: TMemoField;
    qrListaPedidosItensPRECO_UNIT: TBCDField;
    qrListaPedidosItensVLR_DESC: TBCDField;
    qrListaPedidosItensPCT_DESC: TBCDField;
    qrListaPedidosItensALIQ_ICMS_ITEM: TBCDField;
    qrListaPedidosItensALIQ_IPI_ITEM: TBCDField;
    qrListaPedidosItensVLR_ICMS_ITEM: TBCDField;
    qrListaPedidosItensVLR_IPI_ITEM: TBCDField;
    qrListaPedidosItensVLR_TOTAL_ITEM: TBCDField;
    qrListaPedidosItensCODIGO_PECA: TStringField;
    qrListaPedidosItensDESCRICAO_PECA: TStringField;
    qrListaPedidosItensQTDE_PECA_LOJA: TIntegerField;
    qrListaPedidosItensQTDE_PECA_ARMAZEM: TIntegerField;
    qrListaPedidosItensCODIGO_NBM: TStringField;
    qrListaNBMNBM_SQ: TIntegerField;
    qrListaNBMCODIGO_NBM: TStringField;
    qrListaNBMALIQ_ICMS: TBCDField;
    qrListaNBMALIQ_IPI: TBCDField;
    qrListaPecasPECA_SQ: TIntegerField;
    qrListaPecasCODIGO_PECA: TStringField;
    qrListaPecasDESCRICAO_PECA: TStringField;
    qrListaPecasQTDE_PECA_LOJA: TIntegerField;
    qrListaPecasQTDE_PECA_ARMAZEM: TIntegerField;
    qrListaPecasQTDE_PECA_DEMO: TIntegerField;
    qrListaPecasQTDE_PECA_DEFEITO: TIntegerField;
    qrListaPecasQTDE_PECA_EM_USO: TIntegerField;
    qrListaPecasQTDE_PECA_BACKUP: TIntegerField;
    qrListaPecasQTDE_PECA_DEMO_CLI: TIntegerField;
    qrListaPecasQTDE_PECA_HLC: TIntegerField;
    qrListaPecasNBM_SQ: TIntegerField;
    qrListaPecasMODELO_SQ: TIntegerField;
    qrListaPecasUN_PECA: TStringField;
    qrListaPecasMARCA_PECA: TStringField;
    qrListaPecasPRECO_UNIT_PECA: TBCDField;
    qrListaPecasTIPO_PECA: TIntegerField;
    qrListaPecasDESCRICAO_MODELO: TStringField;
    qrListaPecasCODIGO_NBM: TStringField;
    qrListaPecasALIQ_ICMS: TBCDField;
    qrListaPecasALIQ_IPI: TBCDField;
    procedure RemoteDataModuleCreate(Sender: TObject);
  private
    { Private declarations }
  protected
    class procedure UpdateRegistry(Register: Boolean; const ClassID, ProgID: string); override;
    procedure CriaLista(const Sql: WideString); safecall;
    function Maximo(const Tabela: WideString; const Campo: WideString): Integer; safecall;
    procedure BuscaPecas(const Sql: WideString); safecall;
    procedure BuscaClientes(const Sql: WideString); safecall;
  public
    { Public declarations }
  end;

implementation

uses uSetup;

{$R *.DFM}

class procedure TServerLista.UpdateRegistry(Register: Boolean; const ClassID, ProgID: string);
begin
  if Register then
  begin
    inherited UpdateRegistry(Register, ClassID, ProgID);
    EnableSocketTransport(ClassID);
    EnableWebTransport(ClassID);
  end else
  begin
    DisableSocketTransport(ClassID);
    DisableWebTransport(ClassID);
    inherited UpdateRegistry(Register, ClassID, ProgID);
  end;
end;

procedure TServerLista.CriaLista(const Sql: WideString);
var
  S: String;
begin
  S := Sql;
  tag := Pos ('first 1', Sql);
  if tag <> 0 then
    Delete (S, 7, tag);

  qrLista.SQL.Clear;
  qrLista.SQL.Add(S);
end;

procedure TServerLista.BuscaPecas(const Sql: WideString);
begin
  qrBuscaPecas.SQL.Clear;
  qrBuscaPecas.SQL.Add(Sql);
end;

procedure TServerLista.BuscaClientes(const Sql: WideString);
begin
  qrBuscaClientes.SQL.Clear;
  qrBuscaClientes.SQL.Add(Sql);
end;

function TServerLista.Maximo(const Tabela: WideString; const Campo: WideString): Integer;
begin
  Query1.SQL.Clear;
  Query1.SQL.Add('SELECT MAX(' + Campo + ') as MAXIMO FROM ' + TABELA);
  Query1.Open;
  Result := Query1.FieldByName ('MAXIMO').AsInteger;
end;

procedure TServerLista.RemoteDataModuleCreate(Sender: TObject);
var
  Reg: TRegistry;
  banco, bancocep: string;
begin
  Reg := TRegistry.Create;
  try
    Reg.RootKey := HKEY_CURRENT_USER;
    if Reg.OpenKey('\Software\MSystem', True) then
    begin
      banco    := Reg.ReadString ('FBBanco');
      bancocep := Reg.ReadString ('FBBancoCep');
    end;
  finally
    Reg.CloseKey;
    Reg.Free;
  end;
  try
    DBConn.Connected := True;
    DBCep.Connected  := True;
  except
    Exception.Create('Nao foi possível conectar-se ao banco de dados!');
  end;
end;

initialization
  TComponentFactory.Create(ComServer, TServerLista,
    Class_ServerLista, ciMultiInstance, tmApartment);
end.
