package br.com.msystem.vo;
// Generated 12/03/2013 13:33:49 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AssistenciasEquips generated by hbm2java
 */
@Entity
@Table(name="assistencias_equips"
    ,catalog="handy"
)
public class AssistenciasEquips  implements java.io.Serializable {


     private int assistenciaEquipSq;
     private Produtos produtos;
     private Assistencias assistencias;
     private String nrSerieEquip;
     private String defeito;
     private String servicos;
     private Set<AssistenciasItens> assistenciasItenses = new HashSet<AssistenciasItens>(0);

    public AssistenciasEquips() {
    }

	
    public AssistenciasEquips(Produtos produtos, Assistencias assistencias) {
        this.produtos = produtos;
        this.assistencias = assistencias;
    }
    public AssistenciasEquips(Produtos produtos, Assistencias assistencias, String nrSerieEquip, String defeito, String servicos, Set<AssistenciasItens> assistenciasItenses) {
       this.produtos = produtos;
       this.assistencias = assistencias;
       this.nrSerieEquip = nrSerieEquip;
       this.defeito = defeito;
       this.servicos = servicos;
       this.assistenciasItenses = assistenciasItenses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ASSISTENCIA_EQUIP_SQ", unique=true, nullable=false)
    public int getAssistenciaEquipSq() {
        return this.assistenciaEquipSq;
    }
    
    public void setAssistenciaEquipSq(int assistenciaEquipSq) {
        this.assistenciaEquipSq = assistenciaEquipSq;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PRODUTO_SQ", nullable=false)
    public Produtos getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Produtos produtos) {
        this.produtos = produtos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ASSISTENCIA_SQ", nullable=false)
    public Assistencias getAssistencias() {
        return this.assistencias;
    }
    
    public void setAssistencias(Assistencias assistencias) {
        this.assistencias = assistencias;
    }

    
    @Column(name="NR_SERIE_EQUIP", length=65535)
    public String getNrSerieEquip() {
        return this.nrSerieEquip;
    }
    
    public void setNrSerieEquip(String nrSerieEquip) {
        this.nrSerieEquip = nrSerieEquip;
    }

    
    @Column(name="defeito", length=65535)
    public String getDefeito() {
        return this.defeito;
    }
    
    public void setDefeito(String defeito) {
        this.defeito = defeito;
    }

    
    @Column(name="servicos", length=65535)
    public String getServicos() {
        return this.servicos;
    }
    
    public void setServicos(String servicos) {
        this.servicos = servicos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="assistenciasEquips")
    public Set<AssistenciasItens> getAssistenciasItenses() {
        return this.assistenciasItenses;
    }
    
    public void setAssistenciasItenses(Set<AssistenciasItens> assistenciasItenses) {
        this.assistenciasItenses = assistenciasItenses;
    }




}


