package br.com.msystem.vo;
// Generated 12/03/2013 13:33:49 by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Assistencias generated by hbm2java
 */
@Entity
@Table(name="assistencias"
    ,catalog="handy"
    , uniqueConstraints = @UniqueConstraint(columnNames="NUMERO_ASSISTENCIA") 
)
public class Assistencias  implements java.io.Serializable {


     private int assistenciaSq;
     private CondPagto condPagto;
     private Clientes clientes;
     private Vendedores vendedores;
     private int numeroAssistencia;
     private Date dataChamado;
     private Date dataAssistencia;
     private BigDecimal cotacaoDolar;
     private BigDecimal despChamado;
     private BigDecimal despHtecAd;
     private BigDecimal despDesloc;
     private BigDecimal vlrPecas;
     private BigDecimal vlrTotal;
     private Date horaInicio;
     private Date horaFim;
     private String garantia;
     private String contrato;
     private String frete;
     private Set<AssistenciasEquips> assistenciasEquipses = new HashSet<AssistenciasEquips>(0);

    public Assistencias() {
    }

	
    public Assistencias(Clientes clientes, Vendedores vendedores, int numeroAssistencia, Date dataChamado, Date dataAssistencia, Date horaInicio) {
        this.clientes = clientes;
        this.vendedores = vendedores;
        this.numeroAssistencia = numeroAssistencia;
        this.dataChamado = dataChamado;
        this.dataAssistencia = dataAssistencia;
        this.horaInicio = horaInicio;
    }
    public Assistencias(CondPagto condPagto, Clientes clientes, Vendedores vendedores, int numeroAssistencia, Date dataChamado, Date dataAssistencia, BigDecimal cotacaoDolar, BigDecimal despChamado, BigDecimal despHtecAd, BigDecimal despDesloc, BigDecimal vlrPecas, BigDecimal vlrTotal, Date horaInicio, Date horaFim, String garantia, String contrato, String frete, Set<AssistenciasEquips> assistenciasEquipses) {
       this.condPagto = condPagto;
       this.clientes = clientes;
       this.vendedores = vendedores;
       this.numeroAssistencia = numeroAssistencia;
       this.dataChamado = dataChamado;
       this.dataAssistencia = dataAssistencia;
       this.cotacaoDolar = cotacaoDolar;
       this.despChamado = despChamado;
       this.despHtecAd = despHtecAd;
       this.despDesloc = despDesloc;
       this.vlrPecas = vlrPecas;
       this.vlrTotal = vlrTotal;
       this.horaInicio = horaInicio;
       this.horaFim = horaFim;
       this.garantia = garantia;
       this.contrato = contrato;
       this.frete = frete;
       this.assistenciasEquipses = assistenciasEquipses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ASSISTENCIA_SQ", unique=true, nullable=false)
    public int getAssistenciaSq() {
        return this.assistenciaSq;
    }
    
    public void setAssistenciaSq(int assistenciaSq) {
        this.assistenciaSq = assistenciaSq;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COND_PAGTO_SQ")
    public CondPagto getCondPagto() {
        return this.condPagto;
    }
    
    public void setCondPagto(CondPagto condPagto) {
        this.condPagto = condPagto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENTE_SQ", nullable=false)
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vendedor_sq", nullable=false)
    public Vendedores getVendedores() {
        return this.vendedores;
    }
    
    public void setVendedores(Vendedores vendedores) {
        this.vendedores = vendedores;
    }

    
    @Column(name="NUMERO_ASSISTENCIA", unique=true, nullable=false)
    public int getNumeroAssistencia() {
        return this.numeroAssistencia;
    }
    
    public void setNumeroAssistencia(int numeroAssistencia) {
        this.numeroAssistencia = numeroAssistencia;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATA_CHAMADO", nullable=false, length=19)
    public Date getDataChamado() {
        return this.dataChamado;
    }
    
    public void setDataChamado(Date dataChamado) {
        this.dataChamado = dataChamado;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATA_ASSISTENCIA", nullable=false, length=19)
    public Date getDataAssistencia() {
        return this.dataAssistencia;
    }
    
    public void setDataAssistencia(Date dataAssistencia) {
        this.dataAssistencia = dataAssistencia;
    }

    
    @Column(name="COTACAO_DOLAR", precision=9)
    public BigDecimal getCotacaoDolar() {
        return this.cotacaoDolar;
    }
    
    public void setCotacaoDolar(BigDecimal cotacaoDolar) {
        this.cotacaoDolar = cotacaoDolar;
    }

    
    @Column(name="DESP_CHAMADO", precision=9)
    public BigDecimal getDespChamado() {
        return this.despChamado;
    }
    
    public void setDespChamado(BigDecimal despChamado) {
        this.despChamado = despChamado;
    }

    
    @Column(name="DESP_HTEC_AD", precision=9)
    public BigDecimal getDespHtecAd() {
        return this.despHtecAd;
    }
    
    public void setDespHtecAd(BigDecimal despHtecAd) {
        this.despHtecAd = despHtecAd;
    }

    
    @Column(name="DESP_DESLOC", precision=9)
    public BigDecimal getDespDesloc() {
        return this.despDesloc;
    }
    
    public void setDespDesloc(BigDecimal despDesloc) {
        this.despDesloc = despDesloc;
    }

    
    @Column(name="VLR_PECAS", precision=9)
    public BigDecimal getVlrPecas() {
        return this.vlrPecas;
    }
    
    public void setVlrPecas(BigDecimal vlrPecas) {
        this.vlrPecas = vlrPecas;
    }

    
    @Column(name="VLR_TOTAL", precision=9)
    public BigDecimal getVlrTotal() {
        return this.vlrTotal;
    }
    
    public void setVlrTotal(BigDecimal vlrTotal) {
        this.vlrTotal = vlrTotal;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="HORA_INICIO", nullable=false, length=8)
    public Date getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(Date horaInicio) {
        this.horaInicio = horaInicio;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="HORA_FIM", length=8)
    public Date getHoraFim() {
        return this.horaFim;
    }
    
    public void setHoraFim(Date horaFim) {
        this.horaFim = horaFim;
    }

    
    @Column(name="GARANTIA", length=1)
    public String getGarantia() {
        return this.garantia;
    }
    
    public void setGarantia(String garantia) {
        this.garantia = garantia;
    }

    
    @Column(name="CONTRATO", length=1)
    public String getContrato() {
        return this.contrato;
    }
    
    public void setContrato(String contrato) {
        this.contrato = contrato;
    }

    
    @Column(name="FRETE", length=1)
    public String getFrete() {
        return this.frete;
    }
    
    public void setFrete(String frete) {
        this.frete = frete;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="assistencias")
    public Set<AssistenciasEquips> getAssistenciasEquipses() {
        return this.assistenciasEquipses;
    }
    
    public void setAssistenciasEquipses(Set<AssistenciasEquips> assistenciasEquipses) {
        this.assistenciasEquipses = assistenciasEquipses;
    }




}


