package br.com.msystem.vo;
// Generated 12/03/2013 13:33:49 by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AssistenciasItens generated by hbm2java
 */
@Entity
@Table(name="assistencias_itens"
    ,catalog="handy"
)
public class AssistenciasItens  implements java.io.Serializable {


     private int assistenciaItemSq;
     private AssistenciasEquips assistenciasEquips;
     private Produtos produtos;
     private int qtdeAssistenciaItem;
     private BigDecimal precoUnit;

    public AssistenciasItens() {
    }

	
    public AssistenciasItens(AssistenciasEquips assistenciasEquips, Produtos produtos, int qtdeAssistenciaItem) {
        this.assistenciasEquips = assistenciasEquips;
        this.produtos = produtos;
        this.qtdeAssistenciaItem = qtdeAssistenciaItem;
    }
    public AssistenciasItens(AssistenciasEquips assistenciasEquips, Produtos produtos, int qtdeAssistenciaItem, BigDecimal precoUnit) {
       this.assistenciasEquips = assistenciasEquips;
       this.produtos = produtos;
       this.qtdeAssistenciaItem = qtdeAssistenciaItem;
       this.precoUnit = precoUnit;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ASSISTENCIA_ITEM_SQ", unique=true, nullable=false)
    public int getAssistenciaItemSq() {
        return this.assistenciaItemSq;
    }
    
    public void setAssistenciaItemSq(int assistenciaItemSq) {
        this.assistenciaItemSq = assistenciaItemSq;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="assistencia_equip_sq", nullable=false)
    public AssistenciasEquips getAssistenciasEquips() {
        return this.assistenciasEquips;
    }
    
    public void setAssistenciasEquips(AssistenciasEquips assistenciasEquips) {
        this.assistenciasEquips = assistenciasEquips;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PRODUTO_SQ", nullable=false)
    public Produtos getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Produtos produtos) {
        this.produtos = produtos;
    }

    
    @Column(name="QTDE_ASSISTENCIA_ITEM", nullable=false)
    public int getQtdeAssistenciaItem() {
        return this.qtdeAssistenciaItem;
    }
    
    public void setQtdeAssistenciaItem(int qtdeAssistenciaItem) {
        this.qtdeAssistenciaItem = qtdeAssistenciaItem;
    }

    
    @Column(name="PRECO_UNIT", precision=9)
    public BigDecimal getPrecoUnit() {
        return this.precoUnit;
    }
    
    public void setPrecoUnit(BigDecimal precoUnit) {
        this.precoUnit = precoUnit;
    }




}


