package br.com.msystem.vo;
// Generated 12/03/2013 13:33:49 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Balanco generated by hbm2java
 */
@Entity
@Table(name="balanco"
    ,catalog="handy"
)
public class Balanco  implements java.io.Serializable {


     private int balancoSq;
     private Empresas empresas;
     private Date dataInicioBalanco;
     private Date dataTerminoBalanco;
     private int qtdeContagem;
     private int numeroEstoque;
     private int grupoBalanco;
     private char statusBalanco;
     private Set<BalancoContagem> balancoContagems = new HashSet<BalancoContagem>(0);

    public Balanco() {
    }

	
    public Balanco(Empresas empresas, Date dataInicioBalanco, int qtdeContagem, int numeroEstoque, int grupoBalanco, char statusBalanco) {
        this.empresas = empresas;
        this.dataInicioBalanco = dataInicioBalanco;
        this.qtdeContagem = qtdeContagem;
        this.numeroEstoque = numeroEstoque;
        this.grupoBalanco = grupoBalanco;
        this.statusBalanco = statusBalanco;
    }
    public Balanco(Empresas empresas, Date dataInicioBalanco, Date dataTerminoBalanco, int qtdeContagem, int numeroEstoque, int grupoBalanco, char statusBalanco, Set<BalancoContagem> balancoContagems) {
       this.empresas = empresas;
       this.dataInicioBalanco = dataInicioBalanco;
       this.dataTerminoBalanco = dataTerminoBalanco;
       this.qtdeContagem = qtdeContagem;
       this.numeroEstoque = numeroEstoque;
       this.grupoBalanco = grupoBalanco;
       this.statusBalanco = statusBalanco;
       this.balancoContagems = balancoContagems;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="balanco_sq", unique=true, nullable=false)
    public int getBalancoSq() {
        return this.balancoSq;
    }
    
    public void setBalancoSq(int balancoSq) {
        this.balancoSq = balancoSq;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="empresa_sq", nullable=false)
    public Empresas getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Empresas empresas) {
        this.empresas = empresas;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_inicio_balanco", nullable=false, length=19)
    public Date getDataInicioBalanco() {
        return this.dataInicioBalanco;
    }
    
    public void setDataInicioBalanco(Date dataInicioBalanco) {
        this.dataInicioBalanco = dataInicioBalanco;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_termino_balanco", length=19)
    public Date getDataTerminoBalanco() {
        return this.dataTerminoBalanco;
    }
    
    public void setDataTerminoBalanco(Date dataTerminoBalanco) {
        this.dataTerminoBalanco = dataTerminoBalanco;
    }

    
    @Column(name="qtde_contagem", nullable=false)
    public int getQtdeContagem() {
        return this.qtdeContagem;
    }
    
    public void setQtdeContagem(int qtdeContagem) {
        this.qtdeContagem = qtdeContagem;
    }

    
    @Column(name="numero_estoque", nullable=false)
    public int getNumeroEstoque() {
        return this.numeroEstoque;
    }
    
    public void setNumeroEstoque(int numeroEstoque) {
        this.numeroEstoque = numeroEstoque;
    }

    
    @Column(name="grupo_balanco", nullable=false)
    public int getGrupoBalanco() {
        return this.grupoBalanco;
    }
    
    public void setGrupoBalanco(int grupoBalanco) {
        this.grupoBalanco = grupoBalanco;
    }

    
    @Column(name="status_balanco", nullable=false, length=1)
    public char getStatusBalanco() {
        return this.statusBalanco;
    }
    
    public void setStatusBalanco(char statusBalanco) {
        this.statusBalanco = statusBalanco;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="balanco")
    public Set<BalancoContagem> getBalancoContagems() {
        return this.balancoContagems;
    }
    
    public void setBalancoContagems(Set<BalancoContagem> balancoContagems) {
        this.balancoContagems = balancoContagems;
    }




}


