package br.com.msystem.vo;
// Generated 12/03/2013 13:33:49 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CartaCorrecao generated by hbm2java
 */
@Entity
@Table(name="carta_correcao"
    ,catalog="handy"
)
public class CartaCorrecao  implements java.io.Serializable {


     private int cartaCorrecaoSq;
     private Nfiscais nfiscais;
     private String chave;
     private String codOrgao;
     private String cnpj;
     private Integer NSeqEvento;
     private String correcao;
     private Date dhEvento;

    public CartaCorrecao() {
    }

	
    public CartaCorrecao(Nfiscais nfiscais, String chave, String codOrgao, String cnpj, String correcao) {
        this.nfiscais = nfiscais;
        this.chave = chave;
        this.codOrgao = codOrgao;
        this.cnpj = cnpj;
        this.correcao = correcao;
    }
    public CartaCorrecao(Nfiscais nfiscais, String chave, String codOrgao, String cnpj, Integer NSeqEvento, String correcao, Date dhEvento) {
       this.nfiscais = nfiscais;
       this.chave = chave;
       this.codOrgao = codOrgao;
       this.cnpj = cnpj;
       this.NSeqEvento = NSeqEvento;
       this.correcao = correcao;
       this.dhEvento = dhEvento;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="carta_correcao_sq", unique=true, nullable=false)
    public int getCartaCorrecaoSq() {
        return this.cartaCorrecaoSq;
    }
    
    public void setCartaCorrecaoSq(int cartaCorrecaoSq) {
        this.cartaCorrecaoSq = cartaCorrecaoSq;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="nfiscal_sq", nullable=false)
    public Nfiscais getNfiscais() {
        return this.nfiscais;
    }
    
    public void setNfiscais(Nfiscais nfiscais) {
        this.nfiscais = nfiscais;
    }

    
    @Column(name="chave", nullable=false, length=44)
    public String getChave() {
        return this.chave;
    }
    
    public void setChave(String chave) {
        this.chave = chave;
    }

    
    @Column(name="cod_orgao", nullable=false, length=2)
    public String getCodOrgao() {
        return this.codOrgao;
    }
    
    public void setCodOrgao(String codOrgao) {
        this.codOrgao = codOrgao;
    }

    
    @Column(name="cnpj", nullable=false, length=14)
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }

    
    @Column(name="n_seq_evento")
    public Integer getNSeqEvento() {
        return this.NSeqEvento;
    }
    
    public void setNSeqEvento(Integer NSeqEvento) {
        this.NSeqEvento = NSeqEvento;
    }

    
    @Column(name="correcao", nullable=false, length=1000)
    public String getCorrecao() {
        return this.correcao;
    }
    
    public void setCorrecao(String correcao) {
        this.correcao = correcao;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dh_evento", length=19)
    public Date getDhEvento() {
        return this.dhEvento;
    }
    
    public void setDhEvento(Date dhEvento) {
        this.dhEvento = dhEvento;
    }




}


