package br.com.msystem.vo;
// Generated 12/03/2013 13:33:49 by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Classificacao generated by hbm2java
 */
@Entity
@Table(name="classificacao"
    ,catalog="handy"
    , uniqueConstraints = @UniqueConstraint(columnNames="CODIGO_CLASSIFICACAO") 
)
public class Classificacao  implements java.io.Serializable {


     private int classificacaoSq;
     private String codigoClassificacao;
     private BigDecimal limiteMinimo;
     private BigDecimal limiteMaximo;
     private Integer mesesBonus;
     private Set<Clientes> clienteses = new HashSet<Clientes>(0);

    public Classificacao() {
    }

	
    public Classificacao(String codigoClassificacao, BigDecimal limiteMinimo) {
        this.codigoClassificacao = codigoClassificacao;
        this.limiteMinimo = limiteMinimo;
    }
    public Classificacao(String codigoClassificacao, BigDecimal limiteMinimo, BigDecimal limiteMaximo, Integer mesesBonus, Set<Clientes> clienteses) {
       this.codigoClassificacao = codigoClassificacao;
       this.limiteMinimo = limiteMinimo;
       this.limiteMaximo = limiteMaximo;
       this.mesesBonus = mesesBonus;
       this.clienteses = clienteses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="CLASSIFICACAO_SQ", unique=true, nullable=false)
    public int getClassificacaoSq() {
        return this.classificacaoSq;
    }
    
    public void setClassificacaoSq(int classificacaoSq) {
        this.classificacaoSq = classificacaoSq;
    }

    
    @Column(name="CODIGO_CLASSIFICACAO", unique=true, nullable=false, length=50)
    public String getCodigoClassificacao() {
        return this.codigoClassificacao;
    }
    
    public void setCodigoClassificacao(String codigoClassificacao) {
        this.codigoClassificacao = codigoClassificacao;
    }

    
    @Column(name="LIMITE_MINIMO", nullable=false, precision=9)
    public BigDecimal getLimiteMinimo() {
        return this.limiteMinimo;
    }
    
    public void setLimiteMinimo(BigDecimal limiteMinimo) {
        this.limiteMinimo = limiteMinimo;
    }

    
    @Column(name="LIMITE_MAXIMO", precision=9)
    public BigDecimal getLimiteMaximo() {
        return this.limiteMaximo;
    }
    
    public void setLimiteMaximo(BigDecimal limiteMaximo) {
        this.limiteMaximo = limiteMaximo;
    }

    
    @Column(name="MESES_BONUS")
    public Integer getMesesBonus() {
        return this.mesesBonus;
    }
    
    public void setMesesBonus(Integer mesesBonus) {
        this.mesesBonus = mesesBonus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="classificacao")
    public Set<Clientes> getClienteses() {
        return this.clienteses;
    }
    
    public void setClienteses(Set<Clientes> clienteses) {
        this.clienteses = clienteses;
    }




}


