package br.com.msystem.vo;
// Generated 12/03/2013 13:33:49 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ConteinerItens generated by hbm2java
 */
@Entity
@Table(name="conteiner_itens"
    ,catalog="handy"
)
public class ConteinerItens  implements java.io.Serializable {


     private int conteinerItemSq;
     private Conteiner conteiner;
     private Produtos produtos;
     private int quantidade;

    public ConteinerItens() {
    }

    public ConteinerItens(Conteiner conteiner, Produtos produtos, int quantidade) {
       this.conteiner = conteiner;
       this.produtos = produtos;
       this.quantidade = quantidade;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="conteiner_item_sq", unique=true, nullable=false)
    public int getConteinerItemSq() {
        return this.conteinerItemSq;
    }
    
    public void setConteinerItemSq(int conteinerItemSq) {
        this.conteinerItemSq = conteinerItemSq;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="conteiner_sq", nullable=false)
    public Conteiner getConteiner() {
        return this.conteiner;
    }
    
    public void setConteiner(Conteiner conteiner) {
        this.conteiner = conteiner;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="produto_sq", nullable=false)
    public Produtos getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Produtos produtos) {
        this.produtos = produtos;
    }

    
    @Column(name="quantidade", nullable=false)
    public int getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }




}


