package br.com.msystem.vo;
// Generated 12/03/2013 13:33:49 by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ContasPagarPgto generated by hbm2java
 */
@Entity
@Table(name="contas_pagar_pgto"
    ,catalog="handy"
)
public class ContasPagarPgto  implements java.io.Serializable {


     private int contaPagarPgtoSq;
     private ContasPagar contasPagar;
     private Date dtPgto;
     private BigDecimal valorPgto;
     private String formaPgto;
     private String observacao;
     private String banco;
     private String conta;

    public ContasPagarPgto() {
    }

	
    public ContasPagarPgto(ContasPagar contasPagar, Date dtPgto, BigDecimal valorPgto) {
        this.contasPagar = contasPagar;
        this.dtPgto = dtPgto;
        this.valorPgto = valorPgto;
    }
    public ContasPagarPgto(ContasPagar contasPagar, Date dtPgto, BigDecimal valorPgto, String formaPgto, String observacao, String banco, String conta) {
       this.contasPagar = contasPagar;
       this.dtPgto = dtPgto;
       this.valorPgto = valorPgto;
       this.formaPgto = formaPgto;
       this.observacao = observacao;
       this.banco = banco;
       this.conta = conta;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="conta_pagar_pgto_sq", unique=true, nullable=false)
    public int getContaPagarPgtoSq() {
        return this.contaPagarPgtoSq;
    }
    
    public void setContaPagarPgtoSq(int contaPagarPgtoSq) {
        this.contaPagarPgtoSq = contaPagarPgtoSq;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="conta_pagar_sq", nullable=false)
    public ContasPagar getContasPagar() {
        return this.contasPagar;
    }
    
    public void setContasPagar(ContasPagar contasPagar) {
        this.contasPagar = contasPagar;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dt_pgto", nullable=false, length=19)
    public Date getDtPgto() {
        return this.dtPgto;
    }
    
    public void setDtPgto(Date dtPgto) {
        this.dtPgto = dtPgto;
    }

    
    @Column(name="valor_pgto", nullable=false, precision=9)
    public BigDecimal getValorPgto() {
        return this.valorPgto;
    }
    
    public void setValorPgto(BigDecimal valorPgto) {
        this.valorPgto = valorPgto;
    }

    
    @Column(name="forma_pgto", length=20)
    public String getFormaPgto() {
        return this.formaPgto;
    }
    
    public void setFormaPgto(String formaPgto) {
        this.formaPgto = formaPgto;
    }

    
    @Column(name="observacao", length=100)
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }

    
    @Column(name="banco", length=10)
    public String getBanco() {
        return this.banco;
    }
    
    public void setBanco(String banco) {
        this.banco = banco;
    }

    
    @Column(name="conta", length=20)
    public String getConta() {
        return this.conta;
    }
    
    public void setConta(String conta) {
        this.conta = conta;
    }




}


