package br.com.msystem.vo;
// Generated 12/03/2013 13:33:49 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Contatos generated by hbm2java
 */
@Entity
@Table(name="contatos"
    ,catalog="handy"
    , uniqueConstraints = @UniqueConstraint(columnNames={"DATA_CONTATO", "CLIENTE_SQ"}) 
)
public class Contatos  implements java.io.Serializable {


     private int contatoSq;
     private NfiscaisItens nfiscaisItens;
     private Clientes clientes;
     private Vendedores vendedores;
     private Date dataContato;
     private String observacao;
     private String tipoContato;
     private String formaContato;
     private Integer qtdeProdutos;
     private Character finalizado;

    public Contatos() {
    }

	
    public Contatos(Clientes clientes, Vendedores vendedores, Date dataContato) {
        this.clientes = clientes;
        this.vendedores = vendedores;
        this.dataContato = dataContato;
    }
    public Contatos(NfiscaisItens nfiscaisItens, Clientes clientes, Vendedores vendedores, Date dataContato, String observacao, String tipoContato, String formaContato, Integer qtdeProdutos, Character finalizado) {
       this.nfiscaisItens = nfiscaisItens;
       this.clientes = clientes;
       this.vendedores = vendedores;
       this.dataContato = dataContato;
       this.observacao = observacao;
       this.tipoContato = tipoContato;
       this.formaContato = formaContato;
       this.qtdeProdutos = qtdeProdutos;
       this.finalizado = finalizado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="CONTATO_SQ", unique=true, nullable=false)
    public int getContatoSq() {
        return this.contatoSq;
    }
    
    public void setContatoSq(int contatoSq) {
        this.contatoSq = contatoSq;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NFISCAL_ITEM_SQ")
    public NfiscaisItens getNfiscaisItens() {
        return this.nfiscaisItens;
    }
    
    public void setNfiscaisItens(NfiscaisItens nfiscaisItens) {
        this.nfiscaisItens = nfiscaisItens;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENTE_SQ", nullable=false)
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="VENDEDOR_SQ", nullable=false)
    public Vendedores getVendedores() {
        return this.vendedores;
    }
    
    public void setVendedores(Vendedores vendedores) {
        this.vendedores = vendedores;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATA_CONTATO", nullable=false, length=19)
    public Date getDataContato() {
        return this.dataContato;
    }
    
    public void setDataContato(Date dataContato) {
        this.dataContato = dataContato;
    }

    
    @Column(name="OBSERVACAO", length=65535)
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }

    
    @Column(name="TIPO_CONTATO", length=1)
    public String getTipoContato() {
        return this.tipoContato;
    }
    
    public void setTipoContato(String tipoContato) {
        this.tipoContato = tipoContato;
    }

    
    @Column(name="FORMA_CONTATO", length=1)
    public String getFormaContato() {
        return this.formaContato;
    }
    
    public void setFormaContato(String formaContato) {
        this.formaContato = formaContato;
    }

    
    @Column(name="QTDE_PRODUTOS")
    public Integer getQtdeProdutos() {
        return this.qtdeProdutos;
    }
    
    public void setQtdeProdutos(Integer qtdeProdutos) {
        this.qtdeProdutos = qtdeProdutos;
    }

    
    @Column(name="finalizado", length=1)
    public Character getFinalizado() {
        return this.finalizado;
    }
    
    public void setFinalizado(Character finalizado) {
        this.finalizado = finalizado;
    }




}


