package br.com.msystem.vo;
// Generated 12/03/2013 13:33:49 by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Empresas generated by hbm2java
 */
@Entity
@Table(name="empresas"
    ,catalog="handy"
)
public class Empresas  implements java.io.Serializable {


     private int empresaSq;
     private String codigoEmpresa;
     private String nomeEmpresa;
     private Integer acessos;
     private String senha;
     private Integer numeroNfiscal;
     private String estado;
     private Integer numeroPedido;
     private String altDataPedido;
     private String altDtemissaoNfiscal;
     private BigDecimal aliqIcmsProd1;
     private BigDecimal aliqIcmsPec1;
     private Integer stribut;
     private String altNrPedido;
     private String altNrNfiscal;
     private Integer diasDemonstracao;
     private Integer numeroAssistencia;
     private BigDecimal aliqPis;
     private BigDecimal aliqCofins;
     private Date ultimaClassificacao;
     private Integer aammClassificacao;
     private BigDecimal aliqIss;
     private BigDecimal margemEsqNf;
     private BigDecimal margemSupNf;
     private String bancoImagens;
     private Character baixaEstoquePedido;
     private BigDecimal jurosReceber;
     private Integer numeroRma;
     private String estoqueNegativo;
     private String descricaoEstoque1;
     private String descricaoEstoque2;
     private String descricaoEstoque3;
     private String descricaoEstoque4;
     private String descricaoEstoque5;
     private String descricaoEstoque6;
     private String descricaoEstoque7;
     private String descricaoEstoque8;
     private String descricaoEstoque9;
     private String descricaoEstoque10;
     private int codigoRegimeTributario;
     private Integer codigoSituacaoOperacao;
     private Set<HistoricoAcesso> historicoAcessos = new HashSet<HistoricoAcesso>(0);
     private Set<Balanco> balancos = new HashSet<Balanco>(0);

    public Empresas() {
    }

	
    public Empresas(String codigoEmpresa, String nomeEmpresa, Date ultimaClassificacao, int codigoRegimeTributario) {
        this.codigoEmpresa = codigoEmpresa;
        this.nomeEmpresa = nomeEmpresa;
        this.ultimaClassificacao = ultimaClassificacao;
        this.codigoRegimeTributario = codigoRegimeTributario;
    }
    public Empresas(String codigoEmpresa, String nomeEmpresa, Integer acessos, String senha, Integer numeroNfiscal, String estado, Integer numeroPedido, String altDataPedido, String altDtemissaoNfiscal, BigDecimal aliqIcmsProd1, BigDecimal aliqIcmsPec1, Integer stribut, String altNrPedido, String altNrNfiscal, Integer diasDemonstracao, Integer numeroAssistencia, BigDecimal aliqPis, BigDecimal aliqCofins, Date ultimaClassificacao, Integer aammClassificacao, BigDecimal aliqIss, BigDecimal margemEsqNf, BigDecimal margemSupNf, String bancoImagens, Character baixaEstoquePedido, BigDecimal jurosReceber, Integer numeroRma, String estoqueNegativo, String descricaoEstoque1, String descricaoEstoque2, String descricaoEstoque3, String descricaoEstoque4, String descricaoEstoque5, String descricaoEstoque6, String descricaoEstoque7, String descricaoEstoque8, String descricaoEstoque9, String descricaoEstoque10, int codigoRegimeTributario, Integer codigoSituacaoOperacao, Set<HistoricoAcesso> historicoAcessos, Set<Balanco> balancos) {
       this.codigoEmpresa = codigoEmpresa;
       this.nomeEmpresa = nomeEmpresa;
       this.acessos = acessos;
       this.senha = senha;
       this.numeroNfiscal = numeroNfiscal;
       this.estado = estado;
       this.numeroPedido = numeroPedido;
       this.altDataPedido = altDataPedido;
       this.altDtemissaoNfiscal = altDtemissaoNfiscal;
       this.aliqIcmsProd1 = aliqIcmsProd1;
       this.aliqIcmsPec1 = aliqIcmsPec1;
       this.stribut = stribut;
       this.altNrPedido = altNrPedido;
       this.altNrNfiscal = altNrNfiscal;
       this.diasDemonstracao = diasDemonstracao;
       this.numeroAssistencia = numeroAssistencia;
       this.aliqPis = aliqPis;
       this.aliqCofins = aliqCofins;
       this.ultimaClassificacao = ultimaClassificacao;
       this.aammClassificacao = aammClassificacao;
       this.aliqIss = aliqIss;
       this.margemEsqNf = margemEsqNf;
       this.margemSupNf = margemSupNf;
       this.bancoImagens = bancoImagens;
       this.baixaEstoquePedido = baixaEstoquePedido;
       this.jurosReceber = jurosReceber;
       this.numeroRma = numeroRma;
       this.estoqueNegativo = estoqueNegativo;
       this.descricaoEstoque1 = descricaoEstoque1;
       this.descricaoEstoque2 = descricaoEstoque2;
       this.descricaoEstoque3 = descricaoEstoque3;
       this.descricaoEstoque4 = descricaoEstoque4;
       this.descricaoEstoque5 = descricaoEstoque5;
       this.descricaoEstoque6 = descricaoEstoque6;
       this.descricaoEstoque7 = descricaoEstoque7;
       this.descricaoEstoque8 = descricaoEstoque8;
       this.descricaoEstoque9 = descricaoEstoque9;
       this.descricaoEstoque10 = descricaoEstoque10;
       this.codigoRegimeTributario = codigoRegimeTributario;
       this.codigoSituacaoOperacao = codigoSituacaoOperacao;
       this.historicoAcessos = historicoAcessos;
       this.balancos = balancos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="EMPRESA_SQ", unique=true, nullable=false)
    public int getEmpresaSq() {
        return this.empresaSq;
    }
    
    public void setEmpresaSq(int empresaSq) {
        this.empresaSq = empresaSq;
    }

    
    @Column(name="CODIGO_EMPRESA", nullable=false, length=15)
    public String getCodigoEmpresa() {
        return this.codigoEmpresa;
    }
    
    public void setCodigoEmpresa(String codigoEmpresa) {
        this.codigoEmpresa = codigoEmpresa;
    }

    
    @Column(name="NOME_EMPRESA", nullable=false, length=50)
    public String getNomeEmpresa() {
        return this.nomeEmpresa;
    }
    
    public void setNomeEmpresa(String nomeEmpresa) {
        this.nomeEmpresa = nomeEmpresa;
    }

    
    @Column(name="ACESSOS")
    public Integer getAcessos() {
        return this.acessos;
    }
    
    public void setAcessos(Integer acessos) {
        this.acessos = acessos;
    }

    
    @Column(name="SENHA", length=14)
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }

    
    @Column(name="NUMERO_NFISCAL")
    public Integer getNumeroNfiscal() {
        return this.numeroNfiscal;
    }
    
    public void setNumeroNfiscal(Integer numeroNfiscal) {
        this.numeroNfiscal = numeroNfiscal;
    }

    
    @Column(name="ESTADO", length=2)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="NUMERO_PEDIDO")
    public Integer getNumeroPedido() {
        return this.numeroPedido;
    }
    
    public void setNumeroPedido(Integer numeroPedido) {
        this.numeroPedido = numeroPedido;
    }

    
    @Column(name="ALT_DATA_PEDIDO", length=1)
    public String getAltDataPedido() {
        return this.altDataPedido;
    }
    
    public void setAltDataPedido(String altDataPedido) {
        this.altDataPedido = altDataPedido;
    }

    
    @Column(name="ALT_DTEMISSAO_NFISCAL", length=1)
    public String getAltDtemissaoNfiscal() {
        return this.altDtemissaoNfiscal;
    }
    
    public void setAltDtemissaoNfiscal(String altDtemissaoNfiscal) {
        this.altDtemissaoNfiscal = altDtemissaoNfiscal;
    }

    
    @Column(name="ALIQ_ICMS_PROD1", precision=9)
    public BigDecimal getAliqIcmsProd1() {
        return this.aliqIcmsProd1;
    }
    
    public void setAliqIcmsProd1(BigDecimal aliqIcmsProd1) {
        this.aliqIcmsProd1 = aliqIcmsProd1;
    }

    
    @Column(name="ALIQ_ICMS_PEC1", precision=9)
    public BigDecimal getAliqIcmsPec1() {
        return this.aliqIcmsPec1;
    }
    
    public void setAliqIcmsPec1(BigDecimal aliqIcmsPec1) {
        this.aliqIcmsPec1 = aliqIcmsPec1;
    }

    
    @Column(name="STRIBUT")
    public Integer getStribut() {
        return this.stribut;
    }
    
    public void setStribut(Integer stribut) {
        this.stribut = stribut;
    }

    
    @Column(name="ALT_NR_PEDIDO", length=1)
    public String getAltNrPedido() {
        return this.altNrPedido;
    }
    
    public void setAltNrPedido(String altNrPedido) {
        this.altNrPedido = altNrPedido;
    }

    
    @Column(name="ALT_NR_NFISCAL", length=1)
    public String getAltNrNfiscal() {
        return this.altNrNfiscal;
    }
    
    public void setAltNrNfiscal(String altNrNfiscal) {
        this.altNrNfiscal = altNrNfiscal;
    }

    
    @Column(name="DIAS_DEMONSTRACAO")
    public Integer getDiasDemonstracao() {
        return this.diasDemonstracao;
    }
    
    public void setDiasDemonstracao(Integer diasDemonstracao) {
        this.diasDemonstracao = diasDemonstracao;
    }

    
    @Column(name="NUMERO_ASSISTENCIA")
    public Integer getNumeroAssistencia() {
        return this.numeroAssistencia;
    }
    
    public void setNumeroAssistencia(Integer numeroAssistencia) {
        this.numeroAssistencia = numeroAssistencia;
    }

    
    @Column(name="ALIQ_PIS", precision=9)
    public BigDecimal getAliqPis() {
        return this.aliqPis;
    }
    
    public void setAliqPis(BigDecimal aliqPis) {
        this.aliqPis = aliqPis;
    }

    
    @Column(name="ALIQ_COFINS", precision=9)
    public BigDecimal getAliqCofins() {
        return this.aliqCofins;
    }
    
    public void setAliqCofins(BigDecimal aliqCofins) {
        this.aliqCofins = aliqCofins;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ULTIMA_CLASSIFICACAO", nullable=false, length=19)
    public Date getUltimaClassificacao() {
        return this.ultimaClassificacao;
    }
    
    public void setUltimaClassificacao(Date ultimaClassificacao) {
        this.ultimaClassificacao = ultimaClassificacao;
    }

    
    @Column(name="AAMM_CLASSIFICACAO")
    public Integer getAammClassificacao() {
        return this.aammClassificacao;
    }
    
    public void setAammClassificacao(Integer aammClassificacao) {
        this.aammClassificacao = aammClassificacao;
    }

    
    @Column(name="ALIQ_ISS", precision=9)
    public BigDecimal getAliqIss() {
        return this.aliqIss;
    }
    
    public void setAliqIss(BigDecimal aliqIss) {
        this.aliqIss = aliqIss;
    }

    
    @Column(name="MARGEM_ESQ_NF", precision=4)
    public BigDecimal getMargemEsqNf() {
        return this.margemEsqNf;
    }
    
    public void setMargemEsqNf(BigDecimal margemEsqNf) {
        this.margemEsqNf = margemEsqNf;
    }

    
    @Column(name="MARGEM_SUP_NF", precision=4)
    public BigDecimal getMargemSupNf() {
        return this.margemSupNf;
    }
    
    public void setMargemSupNf(BigDecimal margemSupNf) {
        this.margemSupNf = margemSupNf;
    }

    
    @Column(name="BANCO_IMAGENS", length=50)
    public String getBancoImagens() {
        return this.bancoImagens;
    }
    
    public void setBancoImagens(String bancoImagens) {
        this.bancoImagens = bancoImagens;
    }

    
    @Column(name="baixa_estoque_pedido", length=1)
    public Character getBaixaEstoquePedido() {
        return this.baixaEstoquePedido;
    }
    
    public void setBaixaEstoquePedido(Character baixaEstoquePedido) {
        this.baixaEstoquePedido = baixaEstoquePedido;
    }

    
    @Column(name="juros_receber", precision=5)
    public BigDecimal getJurosReceber() {
        return this.jurosReceber;
    }
    
    public void setJurosReceber(BigDecimal jurosReceber) {
        this.jurosReceber = jurosReceber;
    }

    
    @Column(name="numero_rma")
    public Integer getNumeroRma() {
        return this.numeroRma;
    }
    
    public void setNumeroRma(Integer numeroRma) {
        this.numeroRma = numeroRma;
    }

    
    @Column(name="estoque_negativo", length=1)
    public String getEstoqueNegativo() {
        return this.estoqueNegativo;
    }
    
    public void setEstoqueNegativo(String estoqueNegativo) {
        this.estoqueNegativo = estoqueNegativo;
    }

    
    @Column(name="descricao_estoque1", length=100)
    public String getDescricaoEstoque1() {
        return this.descricaoEstoque1;
    }
    
    public void setDescricaoEstoque1(String descricaoEstoque1) {
        this.descricaoEstoque1 = descricaoEstoque1;
    }

    
    @Column(name="descricao_estoque2", length=100)
    public String getDescricaoEstoque2() {
        return this.descricaoEstoque2;
    }
    
    public void setDescricaoEstoque2(String descricaoEstoque2) {
        this.descricaoEstoque2 = descricaoEstoque2;
    }

    
    @Column(name="descricao_estoque3", length=100)
    public String getDescricaoEstoque3() {
        return this.descricaoEstoque3;
    }
    
    public void setDescricaoEstoque3(String descricaoEstoque3) {
        this.descricaoEstoque3 = descricaoEstoque3;
    }

    
    @Column(name="descricao_estoque4", length=100)
    public String getDescricaoEstoque4() {
        return this.descricaoEstoque4;
    }
    
    public void setDescricaoEstoque4(String descricaoEstoque4) {
        this.descricaoEstoque4 = descricaoEstoque4;
    }

    
    @Column(name="descricao_estoque5", length=100)
    public String getDescricaoEstoque5() {
        return this.descricaoEstoque5;
    }
    
    public void setDescricaoEstoque5(String descricaoEstoque5) {
        this.descricaoEstoque5 = descricaoEstoque5;
    }

    
    @Column(name="descricao_estoque6", length=100)
    public String getDescricaoEstoque6() {
        return this.descricaoEstoque6;
    }
    
    public void setDescricaoEstoque6(String descricaoEstoque6) {
        this.descricaoEstoque6 = descricaoEstoque6;
    }

    
    @Column(name="descricao_estoque7", length=100)
    public String getDescricaoEstoque7() {
        return this.descricaoEstoque7;
    }
    
    public void setDescricaoEstoque7(String descricaoEstoque7) {
        this.descricaoEstoque7 = descricaoEstoque7;
    }

    
    @Column(name="descricao_estoque8", length=100)
    public String getDescricaoEstoque8() {
        return this.descricaoEstoque8;
    }
    
    public void setDescricaoEstoque8(String descricaoEstoque8) {
        this.descricaoEstoque8 = descricaoEstoque8;
    }

    
    @Column(name="descricao_estoque9", length=100)
    public String getDescricaoEstoque9() {
        return this.descricaoEstoque9;
    }
    
    public void setDescricaoEstoque9(String descricaoEstoque9) {
        this.descricaoEstoque9 = descricaoEstoque9;
    }

    
    @Column(name="descricao_estoque10", length=100)
    public String getDescricaoEstoque10() {
        return this.descricaoEstoque10;
    }
    
    public void setDescricaoEstoque10(String descricaoEstoque10) {
        this.descricaoEstoque10 = descricaoEstoque10;
    }

    
    @Column(name="codigo_regime_tributario", nullable=false)
    public int getCodigoRegimeTributario() {
        return this.codigoRegimeTributario;
    }
    
    public void setCodigoRegimeTributario(int codigoRegimeTributario) {
        this.codigoRegimeTributario = codigoRegimeTributario;
    }

    
    @Column(name="codigo_situacao_operacao")
    public Integer getCodigoSituacaoOperacao() {
        return this.codigoSituacaoOperacao;
    }
    
    public void setCodigoSituacaoOperacao(Integer codigoSituacaoOperacao) {
        this.codigoSituacaoOperacao = codigoSituacaoOperacao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresas")
    public Set<HistoricoAcesso> getHistoricoAcessos() {
        return this.historicoAcessos;
    }
    
    public void setHistoricoAcessos(Set<HistoricoAcesso> historicoAcessos) {
        this.historicoAcessos = historicoAcessos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresas")
    public Set<Balanco> getBalancos() {
        return this.balancos;
    }
    
    public void setBalancos(Set<Balanco> balancos) {
        this.balancos = balancos;
    }




}


