package br.com.msystem.vo;
// Generated 12/03/2013 13:33:49 by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EstadoIva generated by hbm2java
 */
@Entity
@Table(name="estado_iva"
    ,catalog="handy"
)
public class EstadoIva  implements java.io.Serializable {


     private int estadoIvaSq;
     private Nbm nbm;
     private Estado estado;
     private BigDecimal aliqIva;

    public EstadoIva() {
    }

	
    public EstadoIva(Nbm nbm, Estado estado) {
        this.nbm = nbm;
        this.estado = estado;
    }
    public EstadoIva(Nbm nbm, Estado estado, BigDecimal aliqIva) {
       this.nbm = nbm;
       this.estado = estado;
       this.aliqIva = aliqIva;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="estado_iva_sq", unique=true, nullable=false)
    public int getEstadoIvaSq() {
        return this.estadoIvaSq;
    }
    
    public void setEstadoIvaSq(int estadoIvaSq) {
        this.estadoIvaSq = estadoIvaSq;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="nbm_sq", nullable=false)
    public Nbm getNbm() {
        return this.nbm;
    }
    
    public void setNbm(Nbm nbm) {
        this.nbm = nbm;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="estado_sq", nullable=false)
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }

    
    @Column(name="aliq_iva", precision=5)
    public BigDecimal getAliqIva() {
        return this.aliqIva;
    }
    
    public void setAliqIva(BigDecimal aliqIva) {
        this.aliqIva = aliqIva;
    }




}


