package br.com.msystem.vo;
// Generated 12/03/2013 13:33:49 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Fornecedor generated by hbm2java
 */
@Entity
@Table(name="fornecedor"
    ,catalog="handy"
    , uniqueConstraints = @UniqueConstraint(columnNames="cnpj_fornecedor") 
)
public class Fornecedor  implements java.io.Serializable {


     private int fornecedorSq;
     private String cnpjFornecedor;
     private String nomeFornecedor;
     private String inscrMunicipal;
     private String inscrEstadual;
     private String logradouro;
     private String numero;
     private String bairro;
     private String complemento;
     private String cep;
     private String cidade;
     private String estado;
     private String pais;
     private String telefone;
     private String celular;
     private String EMail;
     private String contato;
     private String observacao;
     private Set<ContasPagar> contasPagars = new HashSet<ContasPagar>(0);

    public Fornecedor() {
    }

	
    public Fornecedor(String cnpjFornecedor, String nomeFornecedor) {
        this.cnpjFornecedor = cnpjFornecedor;
        this.nomeFornecedor = nomeFornecedor;
    }
    public Fornecedor(String cnpjFornecedor, String nomeFornecedor, String inscrMunicipal, String inscrEstadual, String logradouro, String numero, String bairro, String complemento, String cep, String cidade, String estado, String pais, String telefone, String celular, String EMail, String contato, String observacao, Set<ContasPagar> contasPagars) {
       this.cnpjFornecedor = cnpjFornecedor;
       this.nomeFornecedor = nomeFornecedor;
       this.inscrMunicipal = inscrMunicipal;
       this.inscrEstadual = inscrEstadual;
       this.logradouro = logradouro;
       this.numero = numero;
       this.bairro = bairro;
       this.complemento = complemento;
       this.cep = cep;
       this.cidade = cidade;
       this.estado = estado;
       this.pais = pais;
       this.telefone = telefone;
       this.celular = celular;
       this.EMail = EMail;
       this.contato = contato;
       this.observacao = observacao;
       this.contasPagars = contasPagars;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="fornecedor_sq", unique=true, nullable=false)
    public int getFornecedorSq() {
        return this.fornecedorSq;
    }
    
    public void setFornecedorSq(int fornecedorSq) {
        this.fornecedorSq = fornecedorSq;
    }

    
    @Column(name="cnpj_fornecedor", unique=true, nullable=false, length=15)
    public String getCnpjFornecedor() {
        return this.cnpjFornecedor;
    }
    
    public void setCnpjFornecedor(String cnpjFornecedor) {
        this.cnpjFornecedor = cnpjFornecedor;
    }

    
    @Column(name="nome_fornecedor", nullable=false, length=50)
    public String getNomeFornecedor() {
        return this.nomeFornecedor;
    }
    
    public void setNomeFornecedor(String nomeFornecedor) {
        this.nomeFornecedor = nomeFornecedor;
    }

    
    @Column(name="inscr_municipal", length=20)
    public String getInscrMunicipal() {
        return this.inscrMunicipal;
    }
    
    public void setInscrMunicipal(String inscrMunicipal) {
        this.inscrMunicipal = inscrMunicipal;
    }

    
    @Column(name="inscr_estadual", length=20)
    public String getInscrEstadual() {
        return this.inscrEstadual;
    }
    
    public void setInscrEstadual(String inscrEstadual) {
        this.inscrEstadual = inscrEstadual;
    }

    
    @Column(name="logradouro", length=50)
    public String getLogradouro() {
        return this.logradouro;
    }
    
    public void setLogradouro(String logradouro) {
        this.logradouro = logradouro;
    }

    
    @Column(name="numero", length=20)
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }

    
    @Column(name="bairro", length=30)
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    
    @Column(name="complemento", length=50)
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }

    
    @Column(name="cep", length=8)
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }

    
    @Column(name="cidade", length=30)
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }

    
    @Column(name="estado", length=2)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="pais", length=50)
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }

    
    @Column(name="telefone", length=50)
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    
    @Column(name="celular", length=50)
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }

    
    @Column(name="e_mail", length=100)
    public String getEMail() {
        return this.EMail;
    }
    
    public void setEMail(String EMail) {
        this.EMail = EMail;
    }

    
    @Column(name="contato", length=50)
    public String getContato() {
        return this.contato;
    }
    
    public void setContato(String contato) {
        this.contato = contato;
    }

    
    @Column(name="observacao", length=65535)
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fornecedor")
    public Set<ContasPagar> getContasPagars() {
        return this.contasPagars;
    }
    
    public void setContasPagars(Set<ContasPagar> contasPagars) {
        this.contasPagars = contasPagars;
    }




}


