package br.com.msystem.vo;
// Generated 12/03/2013 13:33:49 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HistAlteracoes generated by hbm2java
 */
@Entity
@Table(name="hist_alteracoes"
    ,catalog="handy"
)
public class HistAlteracoes  implements java.io.Serializable {


     private int histAlteracaoSq;
     private Usuarios usuarios;
     private String nomeTabela;
     private int chaveSq;
     private int tipoAlteracao;
     private Date dataAlteracao;
     private String observacao;

    public HistAlteracoes() {
    }

	
    public HistAlteracoes(Usuarios usuarios, String nomeTabela, int chaveSq, int tipoAlteracao, Date dataAlteracao) {
        this.usuarios = usuarios;
        this.nomeTabela = nomeTabela;
        this.chaveSq = chaveSq;
        this.tipoAlteracao = tipoAlteracao;
        this.dataAlteracao = dataAlteracao;
    }
    public HistAlteracoes(Usuarios usuarios, String nomeTabela, int chaveSq, int tipoAlteracao, Date dataAlteracao, String observacao) {
       this.usuarios = usuarios;
       this.nomeTabela = nomeTabela;
       this.chaveSq = chaveSq;
       this.tipoAlteracao = tipoAlteracao;
       this.dataAlteracao = dataAlteracao;
       this.observacao = observacao;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="HIST_ALTERACAO_SQ", unique=true, nullable=false)
    public int getHistAlteracaoSq() {
        return this.histAlteracaoSq;
    }
    
    public void setHistAlteracaoSq(int histAlteracaoSq) {
        this.histAlteracaoSq = histAlteracaoSq;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USUARIO_SQ", nullable=false)
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }

    
    @Column(name="NOME_TABELA", nullable=false, length=50)
    public String getNomeTabela() {
        return this.nomeTabela;
    }
    
    public void setNomeTabela(String nomeTabela) {
        this.nomeTabela = nomeTabela;
    }

    
    @Column(name="chave_sq", nullable=false)
    public int getChaveSq() {
        return this.chaveSq;
    }
    
    public void setChaveSq(int chaveSq) {
        this.chaveSq = chaveSq;
    }

    
    @Column(name="TIPO_ALTERACAO", nullable=false)
    public int getTipoAlteracao() {
        return this.tipoAlteracao;
    }
    
    public void setTipoAlteracao(int tipoAlteracao) {
        this.tipoAlteracao = tipoAlteracao;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATA_ALTERACAO", nullable=false, length=19)
    public Date getDataAlteracao() {
        return this.dataAlteracao;
    }
    
    public void setDataAlteracao(Date dataAlteracao) {
        this.dataAlteracao = dataAlteracao;
    }

    
    @Column(name="observacao", length=65535)
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }




}


