package br.com.msystem.vo;
// Generated 12/03/2013 13:33:49 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HistoricoLogin generated by hbm2java
 */
@Entity
@Table(name="historico_login"
    ,catalog="handy"
)
public class HistoricoLogin  implements java.io.Serializable {


     private int histLoginSq;
     private Usuarios usuarios;
     private Date dataLogin;
     private String ipLogin;

    public HistoricoLogin() {
    }

	
    public HistoricoLogin(Usuarios usuarios, Date dataLogin) {
        this.usuarios = usuarios;
        this.dataLogin = dataLogin;
    }
    public HistoricoLogin(Usuarios usuarios, Date dataLogin, String ipLogin) {
       this.usuarios = usuarios;
       this.dataLogin = dataLogin;
       this.ipLogin = ipLogin;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="HIST_LOGIN_SQ", unique=true, nullable=false)
    public int getHistLoginSq() {
        return this.histLoginSq;
    }
    
    public void setHistLoginSq(int histLoginSq) {
        this.histLoginSq = histLoginSq;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USUARIO_SQ", nullable=false)
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATA_LOGIN", nullable=false, length=19)
    public Date getDataLogin() {
        return this.dataLogin;
    }
    
    public void setDataLogin(Date dataLogin) {
        this.dataLogin = dataLogin;
    }

    
    @Column(name="IP_LOGIN", length=15)
    public String getIpLogin() {
        return this.ipLogin;
    }
    
    public void setIpLogin(String ipLogin) {
        this.ipLogin = ipLogin;
    }




}


