package br.com.msystem.vo;
// Generated 12/03/2013 13:33:49 by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Kardex generated by hbm2java
 */
@Entity
@Table(name="kardex"
    ,catalog="handy"
)
public class Kardex  implements java.io.Serializable {


     private int kardexSq;
     private PedidosItens pedidosItens;
     private Usuarios usuarios;
     private Produtos produtos;
     private String tipoMov;
     private Integer qtde;
     private BigDecimal valor;
     private Date data;
     private Integer nfiscal;
     private String nrSerie;
     private Integer numeroEstoque;

    public Kardex() {
    }

	
    public Kardex(Date data) {
        this.data = data;
    }
    public Kardex(PedidosItens pedidosItens, Usuarios usuarios, Produtos produtos, String tipoMov, Integer qtde, BigDecimal valor, Date data, Integer nfiscal, String nrSerie, Integer numeroEstoque) {
       this.pedidosItens = pedidosItens;
       this.usuarios = usuarios;
       this.produtos = produtos;
       this.tipoMov = tipoMov;
       this.qtde = qtde;
       this.valor = valor;
       this.data = data;
       this.nfiscal = nfiscal;
       this.nrSerie = nrSerie;
       this.numeroEstoque = numeroEstoque;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="KARDEX_SQ", unique=true, nullable=false)
    public int getKardexSq() {
        return this.kardexSq;
    }
    
    public void setKardexSq(int kardexSq) {
        this.kardexSq = kardexSq;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pedido_item_sq")
    public PedidosItens getPedidosItens() {
        return this.pedidosItens;
    }
    
    public void setPedidosItens(PedidosItens pedidosItens) {
        this.pedidosItens = pedidosItens;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USUARIO_SQ")
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PRODUTO_SQ")
    public Produtos getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Produtos produtos) {
        this.produtos = produtos;
    }

    
    @Column(name="TIPO_MOV", length=1)
    public String getTipoMov() {
        return this.tipoMov;
    }
    
    public void setTipoMov(String tipoMov) {
        this.tipoMov = tipoMov;
    }

    
    @Column(name="QTDE")
    public Integer getQtde() {
        return this.qtde;
    }
    
    public void setQtde(Integer qtde) {
        this.qtde = qtde;
    }

    
    @Column(name="VALOR", precision=9)
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATA", nullable=false, length=19)
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }

    
    @Column(name="NFISCAL")
    public Integer getNfiscal() {
        return this.nfiscal;
    }
    
    public void setNfiscal(Integer nfiscal) {
        this.nfiscal = nfiscal;
    }

    
    @Column(name="NR_SERIE", length=65535)
    public String getNrSerie() {
        return this.nrSerie;
    }
    
    public void setNrSerie(String nrSerie) {
        this.nrSerie = nrSerie;
    }

    
    @Column(name="numero_estoque")
    public Integer getNumeroEstoque() {
        return this.numeroEstoque;
    }
    
    public void setNumeroEstoque(Integer numeroEstoque) {
        this.numeroEstoque = numeroEstoque;
    }




}


