package br.com.msystem.vo;
// Generated 12/03/2013 13:33:49 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Linha generated by hbm2java
 */
@Entity
@Table(name="linha"
    ,catalog="handy"
)
public class Linha  implements java.io.Serializable {


     private int linhaSq;
     private String descricaoLinha;
     private Character exclusiva;
     private Set<Produtos> produtoses = new HashSet<Produtos>(0);
     private Set<Nfiscais> nfiscaises = new HashSet<Nfiscais>(0);
     private Set<Pedidos> pedidoses = new HashSet<Pedidos>(0);

    public Linha() {
    }

    public Linha(String descricaoLinha, Character exclusiva, Set<Produtos> produtoses, Set<Nfiscais> nfiscaises, Set<Pedidos> pedidoses) {
       this.descricaoLinha = descricaoLinha;
       this.exclusiva = exclusiva;
       this.produtoses = produtoses;
       this.nfiscaises = nfiscaises;
       this.pedidoses = pedidoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="linha_sq", unique=true, nullable=false)
    public int getLinhaSq() {
        return this.linhaSq;
    }
    
    public void setLinhaSq(int linhaSq) {
        this.linhaSq = linhaSq;
    }

    
    @Column(name="descricao_linha", length=50)
    public String getDescricaoLinha() {
        return this.descricaoLinha;
    }
    
    public void setDescricaoLinha(String descricaoLinha) {
        this.descricaoLinha = descricaoLinha;
    }

    
    @Column(name="exclusiva", length=1)
    public Character getExclusiva() {
        return this.exclusiva;
    }
    
    public void setExclusiva(Character exclusiva) {
        this.exclusiva = exclusiva;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="linha")
    public Set<Produtos> getProdutoses() {
        return this.produtoses;
    }
    
    public void setProdutoses(Set<Produtos> produtoses) {
        this.produtoses = produtoses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="linha")
    public Set<Nfiscais> getNfiscaises() {
        return this.nfiscaises;
    }
    
    public void setNfiscaises(Set<Nfiscais> nfiscaises) {
        this.nfiscaises = nfiscaises;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="linha")
    public Set<Pedidos> getPedidoses() {
        return this.pedidoses;
    }
    
    public void setPedidoses(Set<Pedidos> pedidoses) {
        this.pedidoses = pedidoses;
    }




}


