package br.com.msystem.vo;
// Generated 12/03/2013 13:33:49 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Modelos generated by hbm2java
 */
@Entity
@Table(name="modelos"
    ,catalog="handy"
    , uniqueConstraints = @UniqueConstraint(columnNames="CODIGO_MODELO") 
)
public class Modelos  implements java.io.Serializable {


     private int modeloSq;
     private Modelos modelos;
     private String codigoModelo;
     private String descricaoModelo;
     private Set<Modelos> modeloses = new HashSet<Modelos>(0);
     private Set<Produtos> produtoses = new HashSet<Produtos>(0);

    public Modelos() {
    }

	
    public Modelos(String codigoModelo, String descricaoModelo) {
        this.codigoModelo = codigoModelo;
        this.descricaoModelo = descricaoModelo;
    }
    public Modelos(Modelos modelos, String codigoModelo, String descricaoModelo, Set<Modelos> modeloses, Set<Produtos> produtoses) {
       this.modelos = modelos;
       this.codigoModelo = codigoModelo;
       this.descricaoModelo = descricaoModelo;
       this.modeloses = modeloses;
       this.produtoses = produtoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="MODELO_SQ", unique=true, nullable=false)
    public int getModeloSq() {
        return this.modeloSq;
    }
    
    public void setModeloSq(int modeloSq) {
        this.modeloSq = modeloSq;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MODELO_SQ_PAI")
    public Modelos getModelos() {
        return this.modelos;
    }
    
    public void setModelos(Modelos modelos) {
        this.modelos = modelos;
    }

    
    @Column(name="CODIGO_MODELO", unique=true, nullable=false, length=30)
    public String getCodigoModelo() {
        return this.codigoModelo;
    }
    
    public void setCodigoModelo(String codigoModelo) {
        this.codigoModelo = codigoModelo;
    }

    
    @Column(name="DESCRICAO_MODELO", nullable=false, length=200)
    public String getDescricaoModelo() {
        return this.descricaoModelo;
    }
    
    public void setDescricaoModelo(String descricaoModelo) {
        this.descricaoModelo = descricaoModelo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="modelos")
    public Set<Modelos> getModeloses() {
        return this.modeloses;
    }
    
    public void setModeloses(Set<Modelos> modeloses) {
        this.modeloses = modeloses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="modelos")
    public Set<Produtos> getProdutoses() {
        return this.produtoses;
    }
    
    public void setProdutoses(Set<Produtos> produtoses) {
        this.produtoses = produtoses;
    }




}


