package br.com.msystem.vo;
// Generated 12/03/2013 13:33:49 by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Naturezas generated by hbm2java
 */
@Entity
@Table(name="naturezas"
    ,catalog="handy"
    , uniqueConstraints = @UniqueConstraint(columnNames="CODIGO_NATUREZA") 
)
public class Naturezas  implements java.io.Serializable {


     private int naturezaSq;
     private int codigoNatureza;
     private String descricaoNatureza;
     private String cfo;
     private BigDecimal aliqIcms;
     private BigDecimal aliqIpi;
     private String entSai;
     private String observacao;
     private String uf01;
     private String uf02;
     private String uf03;
     private String uf04;
     private String uf05;
     private String uf06;
     private String uf07;
     private String uf08;
     private String uf09;
     private String uf10;
     private String uf11;
     private String uf12;
     private String uf13;
     private String uf14;
     private String uf15;
     private String uf16;
     private String uf17;
     private String uf18;
     private String uf19;
     private String uf20;
     private String uf21;
     private String uf22;
     private String uf23;
     private String uf24;
     private String uf25;
     private String uf26;
     private String uf27;
     private String uf28;
     private String uf29;
     private String uf30;
     private String isencaoIpi;
     private String isencaoIcms;
     private String descricaoNaturezaNfiscal;
     private Integer tipoNfiscal;
     private String icmsSubst;
     private String cfoSubst;
     private Integer numeroEstoqueSaida;
     private Integer numeroEstoqueEntrada;
     private Set<Nfiscais> nfiscaisesForNaturezaSq = new HashSet<Nfiscais>(0);
     private Set<Pedidos> pedidoses = new HashSet<Pedidos>(0);
     private Set<NfEntradas> nfEntradases = new HashSet<NfEntradas>(0);
     private Set<Nfiscais> nfiscaisesForNaturezaRetDem = new HashSet<Nfiscais>(0);

    public Naturezas() {
    }

	
    public Naturezas(int codigoNatureza, String descricaoNatureza, String cfo) {
        this.codigoNatureza = codigoNatureza;
        this.descricaoNatureza = descricaoNatureza;
        this.cfo = cfo;
    }
    public Naturezas(int codigoNatureza, String descricaoNatureza, String cfo, BigDecimal aliqIcms, BigDecimal aliqIpi, String entSai, String observacao, String uf01, String uf02, String uf03, String uf04, String uf05, String uf06, String uf07, String uf08, String uf09, String uf10, String uf11, String uf12, String uf13, String uf14, String uf15, String uf16, String uf17, String uf18, String uf19, String uf20, String uf21, String uf22, String uf23, String uf24, String uf25, String uf26, String uf27, String uf28, String uf29, String uf30, String isencaoIpi, String isencaoIcms, String descricaoNaturezaNfiscal, Integer tipoNfiscal, String icmsSubst, String cfoSubst, Integer numeroEstoqueSaida, Integer numeroEstoqueEntrada, Set<Nfiscais> nfiscaisesForNaturezaSq, Set<Pedidos> pedidoses, Set<NfEntradas> nfEntradases, Set<Nfiscais> nfiscaisesForNaturezaRetDem) {
       this.codigoNatureza = codigoNatureza;
       this.descricaoNatureza = descricaoNatureza;
       this.cfo = cfo;
       this.aliqIcms = aliqIcms;
       this.aliqIpi = aliqIpi;
       this.entSai = entSai;
       this.observacao = observacao;
       this.uf01 = uf01;
       this.uf02 = uf02;
       this.uf03 = uf03;
       this.uf04 = uf04;
       this.uf05 = uf05;
       this.uf06 = uf06;
       this.uf07 = uf07;
       this.uf08 = uf08;
       this.uf09 = uf09;
       this.uf10 = uf10;
       this.uf11 = uf11;
       this.uf12 = uf12;
       this.uf13 = uf13;
       this.uf14 = uf14;
       this.uf15 = uf15;
       this.uf16 = uf16;
       this.uf17 = uf17;
       this.uf18 = uf18;
       this.uf19 = uf19;
       this.uf20 = uf20;
       this.uf21 = uf21;
       this.uf22 = uf22;
       this.uf23 = uf23;
       this.uf24 = uf24;
       this.uf25 = uf25;
       this.uf26 = uf26;
       this.uf27 = uf27;
       this.uf28 = uf28;
       this.uf29 = uf29;
       this.uf30 = uf30;
       this.isencaoIpi = isencaoIpi;
       this.isencaoIcms = isencaoIcms;
       this.descricaoNaturezaNfiscal = descricaoNaturezaNfiscal;
       this.tipoNfiscal = tipoNfiscal;
       this.icmsSubst = icmsSubst;
       this.cfoSubst = cfoSubst;
       this.numeroEstoqueSaida = numeroEstoqueSaida;
       this.numeroEstoqueEntrada = numeroEstoqueEntrada;
       this.nfiscaisesForNaturezaSq = nfiscaisesForNaturezaSq;
       this.pedidoses = pedidoses;
       this.nfEntradases = nfEntradases;
       this.nfiscaisesForNaturezaRetDem = nfiscaisesForNaturezaRetDem;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="NATUREZA_SQ", unique=true, nullable=false)
    public int getNaturezaSq() {
        return this.naturezaSq;
    }
    
    public void setNaturezaSq(int naturezaSq) {
        this.naturezaSq = naturezaSq;
    }

    
    @Column(name="CODIGO_NATUREZA", unique=true, nullable=false)
    public int getCodigoNatureza() {
        return this.codigoNatureza;
    }
    
    public void setCodigoNatureza(int codigoNatureza) {
        this.codigoNatureza = codigoNatureza;
    }

    
    @Column(name="DESCRICAO_NATUREZA", nullable=false, length=50)
    public String getDescricaoNatureza() {
        return this.descricaoNatureza;
    }
    
    public void setDescricaoNatureza(String descricaoNatureza) {
        this.descricaoNatureza = descricaoNatureza;
    }

    
    @Column(name="CFO", nullable=false, length=4)
    public String getCfo() {
        return this.cfo;
    }
    
    public void setCfo(String cfo) {
        this.cfo = cfo;
    }

    
    @Column(name="ALIQ_ICMS", precision=9)
    public BigDecimal getAliqIcms() {
        return this.aliqIcms;
    }
    
    public void setAliqIcms(BigDecimal aliqIcms) {
        this.aliqIcms = aliqIcms;
    }

    
    @Column(name="ALIQ_IPI", precision=9)
    public BigDecimal getAliqIpi() {
        return this.aliqIpi;
    }
    
    public void setAliqIpi(BigDecimal aliqIpi) {
        this.aliqIpi = aliqIpi;
    }

    
    @Column(name="ENT_SAI", length=1)
    public String getEntSai() {
        return this.entSai;
    }
    
    public void setEntSai(String entSai) {
        this.entSai = entSai;
    }

    
    @Column(name="OBSERVACAO", length=65535)
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }

    
    @Column(name="UF01", length=2)
    public String getUf01() {
        return this.uf01;
    }
    
    public void setUf01(String uf01) {
        this.uf01 = uf01;
    }

    
    @Column(name="UF02", length=2)
    public String getUf02() {
        return this.uf02;
    }
    
    public void setUf02(String uf02) {
        this.uf02 = uf02;
    }

    
    @Column(name="UF03", length=2)
    public String getUf03() {
        return this.uf03;
    }
    
    public void setUf03(String uf03) {
        this.uf03 = uf03;
    }

    
    @Column(name="UF04", length=2)
    public String getUf04() {
        return this.uf04;
    }
    
    public void setUf04(String uf04) {
        this.uf04 = uf04;
    }

    
    @Column(name="UF05", length=2)
    public String getUf05() {
        return this.uf05;
    }
    
    public void setUf05(String uf05) {
        this.uf05 = uf05;
    }

    
    @Column(name="UF06", length=2)
    public String getUf06() {
        return this.uf06;
    }
    
    public void setUf06(String uf06) {
        this.uf06 = uf06;
    }

    
    @Column(name="UF07", length=2)
    public String getUf07() {
        return this.uf07;
    }
    
    public void setUf07(String uf07) {
        this.uf07 = uf07;
    }

    
    @Column(name="UF08", length=2)
    public String getUf08() {
        return this.uf08;
    }
    
    public void setUf08(String uf08) {
        this.uf08 = uf08;
    }

    
    @Column(name="UF09", length=2)
    public String getUf09() {
        return this.uf09;
    }
    
    public void setUf09(String uf09) {
        this.uf09 = uf09;
    }

    
    @Column(name="UF10", length=2)
    public String getUf10() {
        return this.uf10;
    }
    
    public void setUf10(String uf10) {
        this.uf10 = uf10;
    }

    
    @Column(name="UF11", length=2)
    public String getUf11() {
        return this.uf11;
    }
    
    public void setUf11(String uf11) {
        this.uf11 = uf11;
    }

    
    @Column(name="UF12", length=2)
    public String getUf12() {
        return this.uf12;
    }
    
    public void setUf12(String uf12) {
        this.uf12 = uf12;
    }

    
    @Column(name="UF13", length=2)
    public String getUf13() {
        return this.uf13;
    }
    
    public void setUf13(String uf13) {
        this.uf13 = uf13;
    }

    
    @Column(name="UF14", length=2)
    public String getUf14() {
        return this.uf14;
    }
    
    public void setUf14(String uf14) {
        this.uf14 = uf14;
    }

    
    @Column(name="UF15", length=2)
    public String getUf15() {
        return this.uf15;
    }
    
    public void setUf15(String uf15) {
        this.uf15 = uf15;
    }

    
    @Column(name="UF16", length=2)
    public String getUf16() {
        return this.uf16;
    }
    
    public void setUf16(String uf16) {
        this.uf16 = uf16;
    }

    
    @Column(name="UF17", length=2)
    public String getUf17() {
        return this.uf17;
    }
    
    public void setUf17(String uf17) {
        this.uf17 = uf17;
    }

    
    @Column(name="UF18", length=2)
    public String getUf18() {
        return this.uf18;
    }
    
    public void setUf18(String uf18) {
        this.uf18 = uf18;
    }

    
    @Column(name="UF19", length=2)
    public String getUf19() {
        return this.uf19;
    }
    
    public void setUf19(String uf19) {
        this.uf19 = uf19;
    }

    
    @Column(name="UF20", length=2)
    public String getUf20() {
        return this.uf20;
    }
    
    public void setUf20(String uf20) {
        this.uf20 = uf20;
    }

    
    @Column(name="UF21", length=2)
    public String getUf21() {
        return this.uf21;
    }
    
    public void setUf21(String uf21) {
        this.uf21 = uf21;
    }

    
    @Column(name="UF22", length=2)
    public String getUf22() {
        return this.uf22;
    }
    
    public void setUf22(String uf22) {
        this.uf22 = uf22;
    }

    
    @Column(name="UF23", length=2)
    public String getUf23() {
        return this.uf23;
    }
    
    public void setUf23(String uf23) {
        this.uf23 = uf23;
    }

    
    @Column(name="UF24", length=2)
    public String getUf24() {
        return this.uf24;
    }
    
    public void setUf24(String uf24) {
        this.uf24 = uf24;
    }

    
    @Column(name="UF25", length=2)
    public String getUf25() {
        return this.uf25;
    }
    
    public void setUf25(String uf25) {
        this.uf25 = uf25;
    }

    
    @Column(name="UF26", length=2)
    public String getUf26() {
        return this.uf26;
    }
    
    public void setUf26(String uf26) {
        this.uf26 = uf26;
    }

    
    @Column(name="UF27", length=2)
    public String getUf27() {
        return this.uf27;
    }
    
    public void setUf27(String uf27) {
        this.uf27 = uf27;
    }

    
    @Column(name="UF28", length=2)
    public String getUf28() {
        return this.uf28;
    }
    
    public void setUf28(String uf28) {
        this.uf28 = uf28;
    }

    
    @Column(name="UF29", length=2)
    public String getUf29() {
        return this.uf29;
    }
    
    public void setUf29(String uf29) {
        this.uf29 = uf29;
    }

    
    @Column(name="UF30", length=2)
    public String getUf30() {
        return this.uf30;
    }
    
    public void setUf30(String uf30) {
        this.uf30 = uf30;
    }

    
    @Column(name="ISENCAO_IPI", length=1)
    public String getIsencaoIpi() {
        return this.isencaoIpi;
    }
    
    public void setIsencaoIpi(String isencaoIpi) {
        this.isencaoIpi = isencaoIpi;
    }

    
    @Column(name="ISENCAO_ICMS", length=1)
    public String getIsencaoIcms() {
        return this.isencaoIcms;
    }
    
    public void setIsencaoIcms(String isencaoIcms) {
        this.isencaoIcms = isencaoIcms;
    }

    
    @Column(name="DESCRICAO_NATUREZA_NFISCAL", length=50)
    public String getDescricaoNaturezaNfiscal() {
        return this.descricaoNaturezaNfiscal;
    }
    
    public void setDescricaoNaturezaNfiscal(String descricaoNaturezaNfiscal) {
        this.descricaoNaturezaNfiscal = descricaoNaturezaNfiscal;
    }

    
    @Column(name="TIPO_NFISCAL")
    public Integer getTipoNfiscal() {
        return this.tipoNfiscal;
    }
    
    public void setTipoNfiscal(Integer tipoNfiscal) {
        this.tipoNfiscal = tipoNfiscal;
    }

    
    @Column(name="icms_subst", length=1)
    public String getIcmsSubst() {
        return this.icmsSubst;
    }
    
    public void setIcmsSubst(String icmsSubst) {
        this.icmsSubst = icmsSubst;
    }

    
    @Column(name="cfo_subst", length=4)
    public String getCfoSubst() {
        return this.cfoSubst;
    }
    
    public void setCfoSubst(String cfoSubst) {
        this.cfoSubst = cfoSubst;
    }

    
    @Column(name="numero_estoque_saida")
    public Integer getNumeroEstoqueSaida() {
        return this.numeroEstoqueSaida;
    }
    
    public void setNumeroEstoqueSaida(Integer numeroEstoqueSaida) {
        this.numeroEstoqueSaida = numeroEstoqueSaida;
    }

    
    @Column(name="numero_estoque_entrada")
    public Integer getNumeroEstoqueEntrada() {
        return this.numeroEstoqueEntrada;
    }
    
    public void setNumeroEstoqueEntrada(Integer numeroEstoqueEntrada) {
        this.numeroEstoqueEntrada = numeroEstoqueEntrada;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="naturezasByNaturezaSq")
    public Set<Nfiscais> getNfiscaisesForNaturezaSq() {
        return this.nfiscaisesForNaturezaSq;
    }
    
    public void setNfiscaisesForNaturezaSq(Set<Nfiscais> nfiscaisesForNaturezaSq) {
        this.nfiscaisesForNaturezaSq = nfiscaisesForNaturezaSq;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="naturezas")
    public Set<Pedidos> getPedidoses() {
        return this.pedidoses;
    }
    
    public void setPedidoses(Set<Pedidos> pedidoses) {
        this.pedidoses = pedidoses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="naturezas")
    public Set<NfEntradas> getNfEntradases() {
        return this.nfEntradases;
    }
    
    public void setNfEntradases(Set<NfEntradas> nfEntradases) {
        this.nfEntradases = nfEntradases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="naturezasByNaturezaRetDem")
    public Set<Nfiscais> getNfiscaisesForNaturezaRetDem() {
        return this.nfiscaisesForNaturezaRetDem;
    }
    
    public void setNfiscaisesForNaturezaRetDem(Set<Nfiscais> nfiscaisesForNaturezaRetDem) {
        this.nfiscaisesForNaturezaRetDem = nfiscaisesForNaturezaRetDem;
    }




}


