package br.com.msystem.vo;
// Generated 12/03/2013 13:33:49 by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Nbm generated by hbm2java
 */
@Entity
@Table(name="nbm"
    ,catalog="handy"
    , uniqueConstraints = @UniqueConstraint(columnNames="CODIGO_NBM") 
)
public class Nbm  implements java.io.Serializable {


     private int nbmSq;
     private String codigoNbm;
     private BigDecimal aliqIcms;
     private BigDecimal aliqIpi;
     private BigDecimal aliqIva;
     private Set<EstadoIva> estadoIvas = new HashSet<EstadoIva>(0);
     private Set<Produtos> produtoses = new HashSet<Produtos>(0);

    public Nbm() {
    }

	
    public Nbm(String codigoNbm, BigDecimal aliqIva) {
        this.codigoNbm = codigoNbm;
        this.aliqIva = aliqIva;
    }
    public Nbm(String codigoNbm, BigDecimal aliqIcms, BigDecimal aliqIpi, BigDecimal aliqIva, Set<EstadoIva> estadoIvas, Set<Produtos> produtoses) {
       this.codigoNbm = codigoNbm;
       this.aliqIcms = aliqIcms;
       this.aliqIpi = aliqIpi;
       this.aliqIva = aliqIva;
       this.estadoIvas = estadoIvas;
       this.produtoses = produtoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="NBM_SQ", unique=true, nullable=false)
    public int getNbmSq() {
        return this.nbmSq;
    }
    
    public void setNbmSq(int nbmSq) {
        this.nbmSq = nbmSq;
    }

    
    @Column(name="CODIGO_NBM", unique=true, nullable=false, length=10)
    public String getCodigoNbm() {
        return this.codigoNbm;
    }
    
    public void setCodigoNbm(String codigoNbm) {
        this.codigoNbm = codigoNbm;
    }

    
    @Column(name="ALIQ_ICMS", precision=4)
    public BigDecimal getAliqIcms() {
        return this.aliqIcms;
    }
    
    public void setAliqIcms(BigDecimal aliqIcms) {
        this.aliqIcms = aliqIcms;
    }

    
    @Column(name="ALIQ_IPI", precision=4)
    public BigDecimal getAliqIpi() {
        return this.aliqIpi;
    }
    
    public void setAliqIpi(BigDecimal aliqIpi) {
        this.aliqIpi = aliqIpi;
    }

    
    @Column(name="aliq_iva", nullable=false, precision=5)
    public BigDecimal getAliqIva() {
        return this.aliqIva;
    }
    
    public void setAliqIva(BigDecimal aliqIva) {
        this.aliqIva = aliqIva;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nbm")
    public Set<EstadoIva> getEstadoIvas() {
        return this.estadoIvas;
    }
    
    public void setEstadoIvas(Set<EstadoIva> estadoIvas) {
        this.estadoIvas = estadoIvas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nbm")
    public Set<Produtos> getProdutoses() {
        return this.produtoses;
    }
    
    public void setProdutoses(Set<Produtos> produtoses) {
        this.produtoses = produtoses;
    }




}


