package br.com.msystem.vo;
// Generated 12/03/2013 13:33:49 by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * NfEntradasItens generated by hbm2java
 */
@Entity
@Table(name="nf_entradas_itens"
    ,catalog="handy"
)
public class NfEntradasItens  implements java.io.Serializable {


     private int nfEntradaItemSq;
     private NfEntradas nfEntradas;
     private Produtos produtos;
     private int item;
     private byte[] nrSerieItem;
     private Integer qtdeItem;
     private BigDecimal vlrUnitItem;
     private BigDecimal vlrTotalItem;
     private BigDecimal aliqIcmsItem;
     private BigDecimal aliqIpiItem;
     private BigDecimal vlrIcmsItem;
     private BigDecimal vlrIpiItem;
     private Integer numeroEstoque;

    public NfEntradasItens() {
    }

	
    public NfEntradasItens(NfEntradas nfEntradas, int item) {
        this.nfEntradas = nfEntradas;
        this.item = item;
    }
    public NfEntradasItens(NfEntradas nfEntradas, Produtos produtos, int item, byte[] nrSerieItem, Integer qtdeItem, BigDecimal vlrUnitItem, BigDecimal vlrTotalItem, BigDecimal aliqIcmsItem, BigDecimal aliqIpiItem, BigDecimal vlrIcmsItem, BigDecimal vlrIpiItem, Integer numeroEstoque) {
       this.nfEntradas = nfEntradas;
       this.produtos = produtos;
       this.item = item;
       this.nrSerieItem = nrSerieItem;
       this.qtdeItem = qtdeItem;
       this.vlrUnitItem = vlrUnitItem;
       this.vlrTotalItem = vlrTotalItem;
       this.aliqIcmsItem = aliqIcmsItem;
       this.aliqIpiItem = aliqIpiItem;
       this.vlrIcmsItem = vlrIcmsItem;
       this.vlrIpiItem = vlrIpiItem;
       this.numeroEstoque = numeroEstoque;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="NF_ENTRADA_ITEM_SQ", unique=true, nullable=false)
    public int getNfEntradaItemSq() {
        return this.nfEntradaItemSq;
    }
    
    public void setNfEntradaItemSq(int nfEntradaItemSq) {
        this.nfEntradaItemSq = nfEntradaItemSq;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NF_ENTRADA_SQ", nullable=false)
    public NfEntradas getNfEntradas() {
        return this.nfEntradas;
    }
    
    public void setNfEntradas(NfEntradas nfEntradas) {
        this.nfEntradas = nfEntradas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PRODUTO_SQ")
    public Produtos getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Produtos produtos) {
        this.produtos = produtos;
    }

    
    @Column(name="ITEM", nullable=false)
    public int getItem() {
        return this.item;
    }
    
    public void setItem(int item) {
        this.item = item;
    }

    
    @Column(name="NR_SERIE_ITEM")
    public byte[] getNrSerieItem() {
        return this.nrSerieItem;
    }
    
    public void setNrSerieItem(byte[] nrSerieItem) {
        this.nrSerieItem = nrSerieItem;
    }

    
    @Column(name="QTDE_ITEM")
    public Integer getQtdeItem() {
        return this.qtdeItem;
    }
    
    public void setQtdeItem(Integer qtdeItem) {
        this.qtdeItem = qtdeItem;
    }

    
    @Column(name="VLR_UNIT_ITEM", precision=9)
    public BigDecimal getVlrUnitItem() {
        return this.vlrUnitItem;
    }
    
    public void setVlrUnitItem(BigDecimal vlrUnitItem) {
        this.vlrUnitItem = vlrUnitItem;
    }

    
    @Column(name="VLR_TOTAL_ITEM", precision=9)
    public BigDecimal getVlrTotalItem() {
        return this.vlrTotalItem;
    }
    
    public void setVlrTotalItem(BigDecimal vlrTotalItem) {
        this.vlrTotalItem = vlrTotalItem;
    }

    
    @Column(name="ALIQ_ICMS_ITEM", precision=4)
    public BigDecimal getAliqIcmsItem() {
        return this.aliqIcmsItem;
    }
    
    public void setAliqIcmsItem(BigDecimal aliqIcmsItem) {
        this.aliqIcmsItem = aliqIcmsItem;
    }

    
    @Column(name="ALIQ_IPI_ITEM", precision=4)
    public BigDecimal getAliqIpiItem() {
        return this.aliqIpiItem;
    }
    
    public void setAliqIpiItem(BigDecimal aliqIpiItem) {
        this.aliqIpiItem = aliqIpiItem;
    }

    
    @Column(name="VLR_ICMS_ITEM", precision=9)
    public BigDecimal getVlrIcmsItem() {
        return this.vlrIcmsItem;
    }
    
    public void setVlrIcmsItem(BigDecimal vlrIcmsItem) {
        this.vlrIcmsItem = vlrIcmsItem;
    }

    
    @Column(name="VLR_IPI_ITEM", precision=9)
    public BigDecimal getVlrIpiItem() {
        return this.vlrIpiItem;
    }
    
    public void setVlrIpiItem(BigDecimal vlrIpiItem) {
        this.vlrIpiItem = vlrIpiItem;
    }

    
    @Column(name="numero_estoque")
    public Integer getNumeroEstoque() {
        return this.numeroEstoque;
    }
    
    public void setNumeroEstoque(Integer numeroEstoque) {
        this.numeroEstoque = numeroEstoque;
    }




}


