package br.com.msystem.vo;
// Generated 12/03/2013 13:33:49 by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Nfiscais generated by hbm2java
 */
@Entity
@Table(name="nfiscais"
    ,catalog="handy"
    , uniqueConstraints = @UniqueConstraint(columnNames="NUMERO_NFISCAL") 
)
public class Nfiscais  implements java.io.Serializable {


     private int nfiscalSq;
     private Transportadoras transportadoras;
     private CondPagto condPagto;
     private Naturezas naturezasByNaturezaSq;
     private Pedidos pedidos;
     private Linha linha;
     private Clientes clientes;
     private Naturezas naturezasByNaturezaRetDem;
     private Vendedores vendedores;
     private int numeroNfiscal;
     private Date dtemissaoNfiscal;
     private Date dtsaidaNfiscal;
     private BigDecimal baseIcms;
     private BigDecimal vlrIcms;
     private BigDecimal baseIcmsSubst;
     private BigDecimal vlrIcmsSubst;
     private BigDecimal vlrProdutos;
     private BigDecimal vlrFrete;
     private BigDecimal vlrSeguro;
     private BigDecimal vlrDespAcess;
     private BigDecimal vlrIpi;
     private BigDecimal vlrTotal;
     private String freteTransp;
     private String placaTransp;
     private String ufPlacaTransp;
     private Integer qtdeTransp;
     private String especieTransp;
     private String marcaTransp;
     private String numeroTransp;
     private String pbrutoTransp;
     private String pliquidoTransp;
     private Integer classFiscal1;
     private Integer classFiscal2;
     private Integer classFiscal3;
     private Integer classFiscal4;
     private Integer classFiscal5;
     private Integer classFiscal6;
     private Integer classFiscal7;
     private String mensagem;
     private String cancelada;
     private Integer diasDemonstracao;
     private BigDecimal cotacaoDolar;
     private Integer nrNfiscalRetorno;
     private Date dtNfiscalRetorno;
     private String concluida;
     private String nfManual;
     private String retornoProduto;
     private String retornoObservacao;
     private Integer classFiscal8;
     private Integer classFiscal9;
     private Integer classFiscal10;
     private Integer classFiscal11;
     private Integer classFiscal12;
     private Integer classFiscal13;
     private Integer classFiscal14;
     private Integer classFiscal15;
     private Integer classFiscal16;
     private Integer classFiscal17;
     private Integer classFiscal18;
     private Integer classFiscal19;
     private Integer classFiscal20;
     private Integer classFiscal21;
     private Integer classFiscal22;
     private Integer classFiscal23;
     private Integer classFiscal24;
     private String infAdicional;
     private String nfeChave;
     private byte[] nfeResposta;
     private Integer numeroNfe;
     private Integer nfiscalSqReferencia;
     private String reciboNfe;
     private String motivoCancelamento;
     private BigDecimal vlrIi;
     private String ufEmbarque;
     private String localEmbarque;
     private Set<Duplicatas> duplicatases = new HashSet<Duplicatas>(0);
     private Set<NfiscaisItens> nfiscaisItenses = new HashSet<NfiscaisItens>(0);
     private Set<CartaCorrecao> cartaCorrecaos = new HashSet<CartaCorrecao>(0);

    public Nfiscais() {
    }

	
    public Nfiscais(Transportadoras transportadoras, CondPagto condPagto, Naturezas naturezasByNaturezaSq, Clientes clientes, Vendedores vendedores, int numeroNfiscal, Date dtemissaoNfiscal, String cancelada) {
        this.transportadoras = transportadoras;
        this.condPagto = condPagto;
        this.naturezasByNaturezaSq = naturezasByNaturezaSq;
        this.clientes = clientes;
        this.vendedores = vendedores;
        this.numeroNfiscal = numeroNfiscal;
        this.dtemissaoNfiscal = dtemissaoNfiscal;
        this.cancelada = cancelada;
    }
    public Nfiscais(Transportadoras transportadoras, CondPagto condPagto, Naturezas naturezasByNaturezaSq, Pedidos pedidos, Linha linha, Clientes clientes, Naturezas naturezasByNaturezaRetDem, Vendedores vendedores, int numeroNfiscal, Date dtemissaoNfiscal, Date dtsaidaNfiscal, BigDecimal baseIcms, BigDecimal vlrIcms, BigDecimal baseIcmsSubst, BigDecimal vlrIcmsSubst, BigDecimal vlrProdutos, BigDecimal vlrFrete, BigDecimal vlrSeguro, BigDecimal vlrDespAcess, BigDecimal vlrIpi, BigDecimal vlrTotal, String freteTransp, String placaTransp, String ufPlacaTransp, Integer qtdeTransp, String especieTransp, String marcaTransp, String numeroTransp, String pbrutoTransp, String pliquidoTransp, Integer classFiscal1, Integer classFiscal2, Integer classFiscal3, Integer classFiscal4, Integer classFiscal5, Integer classFiscal6, Integer classFiscal7, String mensagem, String cancelada, Integer diasDemonstracao, BigDecimal cotacaoDolar, Integer nrNfiscalRetorno, Date dtNfiscalRetorno, String concluida, String nfManual, String retornoProduto, String retornoObservacao, Integer classFiscal8, Integer classFiscal9, Integer classFiscal10, Integer classFiscal11, Integer classFiscal12, Integer classFiscal13, Integer classFiscal14, Integer classFiscal15, Integer classFiscal16, Integer classFiscal17, Integer classFiscal18, Integer classFiscal19, Integer classFiscal20, Integer classFiscal21, Integer classFiscal22, Integer classFiscal23, Integer classFiscal24, String infAdicional, String nfeChave, byte[] nfeResposta, Integer numeroNfe, Integer nfiscalSqReferencia, String reciboNfe, String motivoCancelamento, BigDecimal vlrIi, String ufEmbarque, String localEmbarque, Set<Duplicatas> duplicatases, Set<NfiscaisItens> nfiscaisItenses, Set<CartaCorrecao> cartaCorrecaos) {
       this.transportadoras = transportadoras;
       this.condPagto = condPagto;
       this.naturezasByNaturezaSq = naturezasByNaturezaSq;
       this.pedidos = pedidos;
       this.linha = linha;
       this.clientes = clientes;
       this.naturezasByNaturezaRetDem = naturezasByNaturezaRetDem;
       this.vendedores = vendedores;
       this.numeroNfiscal = numeroNfiscal;
       this.dtemissaoNfiscal = dtemissaoNfiscal;
       this.dtsaidaNfiscal = dtsaidaNfiscal;
       this.baseIcms = baseIcms;
       this.vlrIcms = vlrIcms;
       this.baseIcmsSubst = baseIcmsSubst;
       this.vlrIcmsSubst = vlrIcmsSubst;
       this.vlrProdutos = vlrProdutos;
       this.vlrFrete = vlrFrete;
       this.vlrSeguro = vlrSeguro;
       this.vlrDespAcess = vlrDespAcess;
       this.vlrIpi = vlrIpi;
       this.vlrTotal = vlrTotal;
       this.freteTransp = freteTransp;
       this.placaTransp = placaTransp;
       this.ufPlacaTransp = ufPlacaTransp;
       this.qtdeTransp = qtdeTransp;
       this.especieTransp = especieTransp;
       this.marcaTransp = marcaTransp;
       this.numeroTransp = numeroTransp;
       this.pbrutoTransp = pbrutoTransp;
       this.pliquidoTransp = pliquidoTransp;
       this.classFiscal1 = classFiscal1;
       this.classFiscal2 = classFiscal2;
       this.classFiscal3 = classFiscal3;
       this.classFiscal4 = classFiscal4;
       this.classFiscal5 = classFiscal5;
       this.classFiscal6 = classFiscal6;
       this.classFiscal7 = classFiscal7;
       this.mensagem = mensagem;
       this.cancelada = cancelada;
       this.diasDemonstracao = diasDemonstracao;
       this.cotacaoDolar = cotacaoDolar;
       this.nrNfiscalRetorno = nrNfiscalRetorno;
       this.dtNfiscalRetorno = dtNfiscalRetorno;
       this.concluida = concluida;
       this.nfManual = nfManual;
       this.retornoProduto = retornoProduto;
       this.retornoObservacao = retornoObservacao;
       this.classFiscal8 = classFiscal8;
       this.classFiscal9 = classFiscal9;
       this.classFiscal10 = classFiscal10;
       this.classFiscal11 = classFiscal11;
       this.classFiscal12 = classFiscal12;
       this.classFiscal13 = classFiscal13;
       this.classFiscal14 = classFiscal14;
       this.classFiscal15 = classFiscal15;
       this.classFiscal16 = classFiscal16;
       this.classFiscal17 = classFiscal17;
       this.classFiscal18 = classFiscal18;
       this.classFiscal19 = classFiscal19;
       this.classFiscal20 = classFiscal20;
       this.classFiscal21 = classFiscal21;
       this.classFiscal22 = classFiscal22;
       this.classFiscal23 = classFiscal23;
       this.classFiscal24 = classFiscal24;
       this.infAdicional = infAdicional;
       this.nfeChave = nfeChave;
       this.nfeResposta = nfeResposta;
       this.numeroNfe = numeroNfe;
       this.nfiscalSqReferencia = nfiscalSqReferencia;
       this.reciboNfe = reciboNfe;
       this.motivoCancelamento = motivoCancelamento;
       this.vlrIi = vlrIi;
       this.ufEmbarque = ufEmbarque;
       this.localEmbarque = localEmbarque;
       this.duplicatases = duplicatases;
       this.nfiscaisItenses = nfiscaisItenses;
       this.cartaCorrecaos = cartaCorrecaos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="NFISCAL_SQ", unique=true, nullable=false)
    public int getNfiscalSq() {
        return this.nfiscalSq;
    }
    
    public void setNfiscalSq(int nfiscalSq) {
        this.nfiscalSq = nfiscalSq;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TRANSPORTADORA_SQ", nullable=false)
    public Transportadoras getTransportadoras() {
        return this.transportadoras;
    }
    
    public void setTransportadoras(Transportadoras transportadoras) {
        this.transportadoras = transportadoras;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COND_PAGTO_SQ", nullable=false)
    public CondPagto getCondPagto() {
        return this.condPagto;
    }
    
    public void setCondPagto(CondPagto condPagto) {
        this.condPagto = condPagto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NATUREZA_SQ", nullable=false)
    public Naturezas getNaturezasByNaturezaSq() {
        return this.naturezasByNaturezaSq;
    }
    
    public void setNaturezasByNaturezaSq(Naturezas naturezasByNaturezaSq) {
        this.naturezasByNaturezaSq = naturezasByNaturezaSq;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PEDIDO_SQ")
    public Pedidos getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Pedidos pedidos) {
        this.pedidos = pedidos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="linha_sq")
    public Linha getLinha() {
        return this.linha;
    }
    
    public void setLinha(Linha linha) {
        this.linha = linha;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENTE_SQ", nullable=false)
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NATUREZA_RET_DEM")
    public Naturezas getNaturezasByNaturezaRetDem() {
        return this.naturezasByNaturezaRetDem;
    }
    
    public void setNaturezasByNaturezaRetDem(Naturezas naturezasByNaturezaRetDem) {
        this.naturezasByNaturezaRetDem = naturezasByNaturezaRetDem;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="VENDEDOR_SQ", nullable=false)
    public Vendedores getVendedores() {
        return this.vendedores;
    }
    
    public void setVendedores(Vendedores vendedores) {
        this.vendedores = vendedores;
    }

    
    @Column(name="NUMERO_NFISCAL", unique=true, nullable=false)
    public int getNumeroNfiscal() {
        return this.numeroNfiscal;
    }
    
    public void setNumeroNfiscal(int numeroNfiscal) {
        this.numeroNfiscal = numeroNfiscal;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DTEMISSAO_NFISCAL", nullable=false, length=19)
    public Date getDtemissaoNfiscal() {
        return this.dtemissaoNfiscal;
    }
    
    public void setDtemissaoNfiscal(Date dtemissaoNfiscal) {
        this.dtemissaoNfiscal = dtemissaoNfiscal;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DTSAIDA_NFISCAL", length=19)
    public Date getDtsaidaNfiscal() {
        return this.dtsaidaNfiscal;
    }
    
    public void setDtsaidaNfiscal(Date dtsaidaNfiscal) {
        this.dtsaidaNfiscal = dtsaidaNfiscal;
    }

    
    @Column(name="BASE_ICMS", precision=9)
    public BigDecimal getBaseIcms() {
        return this.baseIcms;
    }
    
    public void setBaseIcms(BigDecimal baseIcms) {
        this.baseIcms = baseIcms;
    }

    
    @Column(name="VLR_ICMS", precision=9)
    public BigDecimal getVlrIcms() {
        return this.vlrIcms;
    }
    
    public void setVlrIcms(BigDecimal vlrIcms) {
        this.vlrIcms = vlrIcms;
    }

    
    @Column(name="BASE_ICMS_SUBST", precision=9)
    public BigDecimal getBaseIcmsSubst() {
        return this.baseIcmsSubst;
    }
    
    public void setBaseIcmsSubst(BigDecimal baseIcmsSubst) {
        this.baseIcmsSubst = baseIcmsSubst;
    }

    
    @Column(name="VLR_ICMS_SUBST", precision=9)
    public BigDecimal getVlrIcmsSubst() {
        return this.vlrIcmsSubst;
    }
    
    public void setVlrIcmsSubst(BigDecimal vlrIcmsSubst) {
        this.vlrIcmsSubst = vlrIcmsSubst;
    }

    
    @Column(name="VLR_PRODUTOS", precision=9)
    public BigDecimal getVlrProdutos() {
        return this.vlrProdutos;
    }
    
    public void setVlrProdutos(BigDecimal vlrProdutos) {
        this.vlrProdutos = vlrProdutos;
    }

    
    @Column(name="VLR_FRETE", precision=9)
    public BigDecimal getVlrFrete() {
        return this.vlrFrete;
    }
    
    public void setVlrFrete(BigDecimal vlrFrete) {
        this.vlrFrete = vlrFrete;
    }

    
    @Column(name="VLR_SEGURO", precision=9)
    public BigDecimal getVlrSeguro() {
        return this.vlrSeguro;
    }
    
    public void setVlrSeguro(BigDecimal vlrSeguro) {
        this.vlrSeguro = vlrSeguro;
    }

    
    @Column(name="VLR_DESP_ACESS", precision=9)
    public BigDecimal getVlrDespAcess() {
        return this.vlrDespAcess;
    }
    
    public void setVlrDespAcess(BigDecimal vlrDespAcess) {
        this.vlrDespAcess = vlrDespAcess;
    }

    
    @Column(name="VLR_IPI", precision=9)
    public BigDecimal getVlrIpi() {
        return this.vlrIpi;
    }
    
    public void setVlrIpi(BigDecimal vlrIpi) {
        this.vlrIpi = vlrIpi;
    }

    
    @Column(name="VLR_TOTAL", precision=9)
    public BigDecimal getVlrTotal() {
        return this.vlrTotal;
    }
    
    public void setVlrTotal(BigDecimal vlrTotal) {
        this.vlrTotal = vlrTotal;
    }

    
    @Column(name="FRETE_TRANSP", length=1)
    public String getFreteTransp() {
        return this.freteTransp;
    }
    
    public void setFreteTransp(String freteTransp) {
        this.freteTransp = freteTransp;
    }

    
    @Column(name="PLACA_TRANSP", length=7)
    public String getPlacaTransp() {
        return this.placaTransp;
    }
    
    public void setPlacaTransp(String placaTransp) {
        this.placaTransp = placaTransp;
    }

    
    @Column(name="UF_PLACA_TRANSP", length=2)
    public String getUfPlacaTransp() {
        return this.ufPlacaTransp;
    }
    
    public void setUfPlacaTransp(String ufPlacaTransp) {
        this.ufPlacaTransp = ufPlacaTransp;
    }

    
    @Column(name="QTDE_TRANSP")
    public Integer getQtdeTransp() {
        return this.qtdeTransp;
    }
    
    public void setQtdeTransp(Integer qtdeTransp) {
        this.qtdeTransp = qtdeTransp;
    }

    
    @Column(name="ESPECIE_TRANSP", length=20)
    public String getEspecieTransp() {
        return this.especieTransp;
    }
    
    public void setEspecieTransp(String especieTransp) {
        this.especieTransp = especieTransp;
    }

    
    @Column(name="MARCA_TRANSP", length=30)
    public String getMarcaTransp() {
        return this.marcaTransp;
    }
    
    public void setMarcaTransp(String marcaTransp) {
        this.marcaTransp = marcaTransp;
    }

    
    @Column(name="NUMERO_TRANSP", length=10)
    public String getNumeroTransp() {
        return this.numeroTransp;
    }
    
    public void setNumeroTransp(String numeroTransp) {
        this.numeroTransp = numeroTransp;
    }

    
    @Column(name="PBRUTO_TRANSP", length=20)
    public String getPbrutoTransp() {
        return this.pbrutoTransp;
    }
    
    public void setPbrutoTransp(String pbrutoTransp) {
        this.pbrutoTransp = pbrutoTransp;
    }

    
    @Column(name="PLIQUIDO_TRANSP", length=20)
    public String getPliquidoTransp() {
        return this.pliquidoTransp;
    }
    
    public void setPliquidoTransp(String pliquidoTransp) {
        this.pliquidoTransp = pliquidoTransp;
    }

    
    @Column(name="CLASS_FISCAL1")
    public Integer getClassFiscal1() {
        return this.classFiscal1;
    }
    
    public void setClassFiscal1(Integer classFiscal1) {
        this.classFiscal1 = classFiscal1;
    }

    
    @Column(name="CLASS_FISCAL2")
    public Integer getClassFiscal2() {
        return this.classFiscal2;
    }
    
    public void setClassFiscal2(Integer classFiscal2) {
        this.classFiscal2 = classFiscal2;
    }

    
    @Column(name="CLASS_FISCAL3")
    public Integer getClassFiscal3() {
        return this.classFiscal3;
    }
    
    public void setClassFiscal3(Integer classFiscal3) {
        this.classFiscal3 = classFiscal3;
    }

    
    @Column(name="CLASS_FISCAL4")
    public Integer getClassFiscal4() {
        return this.classFiscal4;
    }
    
    public void setClassFiscal4(Integer classFiscal4) {
        this.classFiscal4 = classFiscal4;
    }

    
    @Column(name="CLASS_FISCAL5")
    public Integer getClassFiscal5() {
        return this.classFiscal5;
    }
    
    public void setClassFiscal5(Integer classFiscal5) {
        this.classFiscal5 = classFiscal5;
    }

    
    @Column(name="CLASS_FISCAL6")
    public Integer getClassFiscal6() {
        return this.classFiscal6;
    }
    
    public void setClassFiscal6(Integer classFiscal6) {
        this.classFiscal6 = classFiscal6;
    }

    
    @Column(name="CLASS_FISCAL7")
    public Integer getClassFiscal7() {
        return this.classFiscal7;
    }
    
    public void setClassFiscal7(Integer classFiscal7) {
        this.classFiscal7 = classFiscal7;
    }

    
    @Column(name="MENSAGEM", length=65535)
    public String getMensagem() {
        return this.mensagem;
    }
    
    public void setMensagem(String mensagem) {
        this.mensagem = mensagem;
    }

    
    @Column(name="CANCELADA", nullable=false, length=1)
    public String getCancelada() {
        return this.cancelada;
    }
    
    public void setCancelada(String cancelada) {
        this.cancelada = cancelada;
    }

    
    @Column(name="DIAS_DEMONSTRACAO")
    public Integer getDiasDemonstracao() {
        return this.diasDemonstracao;
    }
    
    public void setDiasDemonstracao(Integer diasDemonstracao) {
        this.diasDemonstracao = diasDemonstracao;
    }

    
    @Column(name="COTACAO_DOLAR", precision=9, scale=4)
    public BigDecimal getCotacaoDolar() {
        return this.cotacaoDolar;
    }
    
    public void setCotacaoDolar(BigDecimal cotacaoDolar) {
        this.cotacaoDolar = cotacaoDolar;
    }

    
    @Column(name="NR_NFISCAL_RETORNO")
    public Integer getNrNfiscalRetorno() {
        return this.nrNfiscalRetorno;
    }
    
    public void setNrNfiscalRetorno(Integer nrNfiscalRetorno) {
        this.nrNfiscalRetorno = nrNfiscalRetorno;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DT_NFISCAL_RETORNO", length=19)
    public Date getDtNfiscalRetorno() {
        return this.dtNfiscalRetorno;
    }
    
    public void setDtNfiscalRetorno(Date dtNfiscalRetorno) {
        this.dtNfiscalRetorno = dtNfiscalRetorno;
    }

    
    @Column(name="CONCLUIDA", length=1)
    public String getConcluida() {
        return this.concluida;
    }
    
    public void setConcluida(String concluida) {
        this.concluida = concluida;
    }

    
    @Column(name="NF_MANUAL", length=1)
    public String getNfManual() {
        return this.nfManual;
    }
    
    public void setNfManual(String nfManual) {
        this.nfManual = nfManual;
    }

    
    @Column(name="RETORNO_PRODUTO", length=1)
    public String getRetornoProduto() {
        return this.retornoProduto;
    }
    
    public void setRetornoProduto(String retornoProduto) {
        this.retornoProduto = retornoProduto;
    }

    
    @Column(name="RETORNO_OBSERVACAO", length=65535)
    public String getRetornoObservacao() {
        return this.retornoObservacao;
    }
    
    public void setRetornoObservacao(String retornoObservacao) {
        this.retornoObservacao = retornoObservacao;
    }

    
    @Column(name="class_fiscal8")
    public Integer getClassFiscal8() {
        return this.classFiscal8;
    }
    
    public void setClassFiscal8(Integer classFiscal8) {
        this.classFiscal8 = classFiscal8;
    }

    
    @Column(name="class_fiscal9")
    public Integer getClassFiscal9() {
        return this.classFiscal9;
    }
    
    public void setClassFiscal9(Integer classFiscal9) {
        this.classFiscal9 = classFiscal9;
    }

    
    @Column(name="class_fiscal10")
    public Integer getClassFiscal10() {
        return this.classFiscal10;
    }
    
    public void setClassFiscal10(Integer classFiscal10) {
        this.classFiscal10 = classFiscal10;
    }

    
    @Column(name="class_fiscal11")
    public Integer getClassFiscal11() {
        return this.classFiscal11;
    }
    
    public void setClassFiscal11(Integer classFiscal11) {
        this.classFiscal11 = classFiscal11;
    }

    
    @Column(name="class_fiscal12")
    public Integer getClassFiscal12() {
        return this.classFiscal12;
    }
    
    public void setClassFiscal12(Integer classFiscal12) {
        this.classFiscal12 = classFiscal12;
    }

    
    @Column(name="class_fiscal13")
    public Integer getClassFiscal13() {
        return this.classFiscal13;
    }
    
    public void setClassFiscal13(Integer classFiscal13) {
        this.classFiscal13 = classFiscal13;
    }

    
    @Column(name="class_fiscal14")
    public Integer getClassFiscal14() {
        return this.classFiscal14;
    }
    
    public void setClassFiscal14(Integer classFiscal14) {
        this.classFiscal14 = classFiscal14;
    }

    
    @Column(name="class_fiscal15")
    public Integer getClassFiscal15() {
        return this.classFiscal15;
    }
    
    public void setClassFiscal15(Integer classFiscal15) {
        this.classFiscal15 = classFiscal15;
    }

    
    @Column(name="class_fiscal16")
    public Integer getClassFiscal16() {
        return this.classFiscal16;
    }
    
    public void setClassFiscal16(Integer classFiscal16) {
        this.classFiscal16 = classFiscal16;
    }

    
    @Column(name="class_fiscal17")
    public Integer getClassFiscal17() {
        return this.classFiscal17;
    }
    
    public void setClassFiscal17(Integer classFiscal17) {
        this.classFiscal17 = classFiscal17;
    }

    
    @Column(name="class_fiscal18")
    public Integer getClassFiscal18() {
        return this.classFiscal18;
    }
    
    public void setClassFiscal18(Integer classFiscal18) {
        this.classFiscal18 = classFiscal18;
    }

    
    @Column(name="class_fiscal19")
    public Integer getClassFiscal19() {
        return this.classFiscal19;
    }
    
    public void setClassFiscal19(Integer classFiscal19) {
        this.classFiscal19 = classFiscal19;
    }

    
    @Column(name="class_fiscal20")
    public Integer getClassFiscal20() {
        return this.classFiscal20;
    }
    
    public void setClassFiscal20(Integer classFiscal20) {
        this.classFiscal20 = classFiscal20;
    }

    
    @Column(name="class_fiscal21")
    public Integer getClassFiscal21() {
        return this.classFiscal21;
    }
    
    public void setClassFiscal21(Integer classFiscal21) {
        this.classFiscal21 = classFiscal21;
    }

    
    @Column(name="class_fiscal22")
    public Integer getClassFiscal22() {
        return this.classFiscal22;
    }
    
    public void setClassFiscal22(Integer classFiscal22) {
        this.classFiscal22 = classFiscal22;
    }

    
    @Column(name="class_fiscal23")
    public Integer getClassFiscal23() {
        return this.classFiscal23;
    }
    
    public void setClassFiscal23(Integer classFiscal23) {
        this.classFiscal23 = classFiscal23;
    }

    
    @Column(name="class_fiscal24")
    public Integer getClassFiscal24() {
        return this.classFiscal24;
    }
    
    public void setClassFiscal24(Integer classFiscal24) {
        this.classFiscal24 = classFiscal24;
    }

    
    @Column(name="inf_adicional", length=100)
    public String getInfAdicional() {
        return this.infAdicional;
    }
    
    public void setInfAdicional(String infAdicional) {
        this.infAdicional = infAdicional;
    }

    
    @Column(name="nfe_chave", length=47)
    public String getNfeChave() {
        return this.nfeChave;
    }
    
    public void setNfeChave(String nfeChave) {
        this.nfeChave = nfeChave;
    }

    
    @Column(name="nfe_resposta")
    public byte[] getNfeResposta() {
        return this.nfeResposta;
    }
    
    public void setNfeResposta(byte[] nfeResposta) {
        this.nfeResposta = nfeResposta;
    }

    
    @Column(name="numero_nfe")
    public Integer getNumeroNfe() {
        return this.numeroNfe;
    }
    
    public void setNumeroNfe(Integer numeroNfe) {
        this.numeroNfe = numeroNfe;
    }

    
    @Column(name="nfiscal_sq_referencia")
    public Integer getNfiscalSqReferencia() {
        return this.nfiscalSqReferencia;
    }
    
    public void setNfiscalSqReferencia(Integer nfiscalSqReferencia) {
        this.nfiscalSqReferencia = nfiscalSqReferencia;
    }

    
    @Column(name="recibo_nfe", length=15)
    public String getReciboNfe() {
        return this.reciboNfe;
    }
    
    public void setReciboNfe(String reciboNfe) {
        this.reciboNfe = reciboNfe;
    }

    
    @Column(name="motivo_cancelamento", length=45)
    public String getMotivoCancelamento() {
        return this.motivoCancelamento;
    }
    
    public void setMotivoCancelamento(String motivoCancelamento) {
        this.motivoCancelamento = motivoCancelamento;
    }

    
    @Column(name="vlr_ii", precision=9)
    public BigDecimal getVlrIi() {
        return this.vlrIi;
    }
    
    public void setVlrIi(BigDecimal vlrIi) {
        this.vlrIi = vlrIi;
    }

    
    @Column(name="uf_embarque", length=2)
    public String getUfEmbarque() {
        return this.ufEmbarque;
    }
    
    public void setUfEmbarque(String ufEmbarque) {
        this.ufEmbarque = ufEmbarque;
    }

    
    @Column(name="local_embarque", length=60)
    public String getLocalEmbarque() {
        return this.localEmbarque;
    }
    
    public void setLocalEmbarque(String localEmbarque) {
        this.localEmbarque = localEmbarque;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nfiscais")
    public Set<Duplicatas> getDuplicatases() {
        return this.duplicatases;
    }
    
    public void setDuplicatases(Set<Duplicatas> duplicatases) {
        this.duplicatases = duplicatases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nfiscais")
    public Set<NfiscaisItens> getNfiscaisItenses() {
        return this.nfiscaisItenses;
    }
    
    public void setNfiscaisItenses(Set<NfiscaisItens> nfiscaisItenses) {
        this.nfiscaisItenses = nfiscaisItenses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nfiscais")
    public Set<CartaCorrecao> getCartaCorrecaos() {
        return this.cartaCorrecaos;
    }
    
    public void setCartaCorrecaos(Set<CartaCorrecao> cartaCorrecaos) {
        this.cartaCorrecaos = cartaCorrecaos;
    }




}


