package br.com.msystem.vo;
// Generated 12/03/2013 13:33:49 by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NfiscaisItens generated by hbm2java
 */
@Entity
@Table(name="nfiscais_itens"
    ,catalog="handy"
)
public class NfiscaisItens  implements java.io.Serializable {


     private int nfiscalItemSq;
     private Produtos produtos;
     private Nfiscais nfiscais;
     private int item;
     private String nrSerieItem;
     private String classFiscal;
     private Integer stribut;
     private Integer qtdeItem1Old;
     private BigDecimal vlrUnitItem;
     private BigDecimal vlrTotalItem;
     private BigDecimal aliqIcmsItem;
     private BigDecimal aliqIpiItem;
     private BigDecimal vlrIcmsItem;
     private BigDecimal vlrIpiItem;
     private BigDecimal pesoBruto;
     private BigDecimal pesoLiquido;
     private Integer qtdeItem2Old;
     private Integer qtdeItem3Old;
     private BigDecimal vlrDesc;
     private BigDecimal pctDesc;
     private BigDecimal vlrJuros;
     private BigDecimal pctJuros;
     private BigDecimal baseIcmsSubstItem;
     private BigDecimal vlrIcmsSubstItem;
     private Integer origemMercadoria;
     private Integer qtdeItem4Old;
     private Integer qtdeItem5Old;
     private Integer qtdeItem6Old;
     private Integer qtdeItem7Old;
     private Integer qtdeItem8Old;
     private Integer qtdeItem9Old;
     private Integer qtdeItem10Old;
     private Integer qtdeItem;
     private BigDecimal vlrFreteItem;
     private BigDecimal vlrSeguroItem;
     private BigDecimal vlrDespAcessItem;
     private BigDecimal baseIiItem;
     private BigDecimal vlrIiItem;
     private BigDecimal vlrDespAduItem;
     private BigDecimal vlrIofItem;
     private String numeroDi;
     private Date dataDi;
     private String localDesemb;
     private String ufDesemb;
     private Date dataDesemb;
     private String codigoExportador;
     private BigDecimal baseIcmsItem;
     private Integer numeroEstoque;
     private Set<NfiscaisItensAdicao> nfiscaisItensAdicaos = new HashSet<NfiscaisItensAdicao>(0);
     private Set<Contatos> contatoses = new HashSet<Contatos>(0);
     private Set<NfiscaisItensSerie> nfiscaisItensSeries = new HashSet<NfiscaisItensSerie>(0);

    public NfiscaisItens() {
    }

	
    public NfiscaisItens(Nfiscais nfiscais, int item) {
        this.nfiscais = nfiscais;
        this.item = item;
    }
    public NfiscaisItens(Produtos produtos, Nfiscais nfiscais, int item, String nrSerieItem, String classFiscal, Integer stribut, Integer qtdeItem1Old, BigDecimal vlrUnitItem, BigDecimal vlrTotalItem, BigDecimal aliqIcmsItem, BigDecimal aliqIpiItem, BigDecimal vlrIcmsItem, BigDecimal vlrIpiItem, BigDecimal pesoBruto, BigDecimal pesoLiquido, Integer qtdeItem2Old, Integer qtdeItem3Old, BigDecimal vlrDesc, BigDecimal pctDesc, BigDecimal vlrJuros, BigDecimal pctJuros, BigDecimal baseIcmsSubstItem, BigDecimal vlrIcmsSubstItem, Integer origemMercadoria, Integer qtdeItem4Old, Integer qtdeItem5Old, Integer qtdeItem6Old, Integer qtdeItem7Old, Integer qtdeItem8Old, Integer qtdeItem9Old, Integer qtdeItem10Old, Integer qtdeItem, BigDecimal vlrFreteItem, BigDecimal vlrSeguroItem, BigDecimal vlrDespAcessItem, BigDecimal baseIiItem, BigDecimal vlrIiItem, BigDecimal vlrDespAduItem, BigDecimal vlrIofItem, String numeroDi, Date dataDi, String localDesemb, String ufDesemb, Date dataDesemb, String codigoExportador, BigDecimal baseIcmsItem, Integer numeroEstoque, Set<NfiscaisItensAdicao> nfiscaisItensAdicaos, Set<Contatos> contatoses, Set<NfiscaisItensSerie> nfiscaisItensSeries) {
       this.produtos = produtos;
       this.nfiscais = nfiscais;
       this.item = item;
       this.nrSerieItem = nrSerieItem;
       this.classFiscal = classFiscal;
       this.stribut = stribut;
       this.qtdeItem1Old = qtdeItem1Old;
       this.vlrUnitItem = vlrUnitItem;
       this.vlrTotalItem = vlrTotalItem;
       this.aliqIcmsItem = aliqIcmsItem;
       this.aliqIpiItem = aliqIpiItem;
       this.vlrIcmsItem = vlrIcmsItem;
       this.vlrIpiItem = vlrIpiItem;
       this.pesoBruto = pesoBruto;
       this.pesoLiquido = pesoLiquido;
       this.qtdeItem2Old = qtdeItem2Old;
       this.qtdeItem3Old = qtdeItem3Old;
       this.vlrDesc = vlrDesc;
       this.pctDesc = pctDesc;
       this.vlrJuros = vlrJuros;
       this.pctJuros = pctJuros;
       this.baseIcmsSubstItem = baseIcmsSubstItem;
       this.vlrIcmsSubstItem = vlrIcmsSubstItem;
       this.origemMercadoria = origemMercadoria;
       this.qtdeItem4Old = qtdeItem4Old;
       this.qtdeItem5Old = qtdeItem5Old;
       this.qtdeItem6Old = qtdeItem6Old;
       this.qtdeItem7Old = qtdeItem7Old;
       this.qtdeItem8Old = qtdeItem8Old;
       this.qtdeItem9Old = qtdeItem9Old;
       this.qtdeItem10Old = qtdeItem10Old;
       this.qtdeItem = qtdeItem;
       this.vlrFreteItem = vlrFreteItem;
       this.vlrSeguroItem = vlrSeguroItem;
       this.vlrDespAcessItem = vlrDespAcessItem;
       this.baseIiItem = baseIiItem;
       this.vlrIiItem = vlrIiItem;
       this.vlrDespAduItem = vlrDespAduItem;
       this.vlrIofItem = vlrIofItem;
       this.numeroDi = numeroDi;
       this.dataDi = dataDi;
       this.localDesemb = localDesemb;
       this.ufDesemb = ufDesemb;
       this.dataDesemb = dataDesemb;
       this.codigoExportador = codigoExportador;
       this.baseIcmsItem = baseIcmsItem;
       this.numeroEstoque = numeroEstoque;
       this.nfiscaisItensAdicaos = nfiscaisItensAdicaos;
       this.contatoses = contatoses;
       this.nfiscaisItensSeries = nfiscaisItensSeries;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="NFISCAL_ITEM_SQ", unique=true, nullable=false)
    public int getNfiscalItemSq() {
        return this.nfiscalItemSq;
    }
    
    public void setNfiscalItemSq(int nfiscalItemSq) {
        this.nfiscalItemSq = nfiscalItemSq;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PRODUTO_SQ")
    public Produtos getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Produtos produtos) {
        this.produtos = produtos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NFISCAL_SQ", nullable=false)
    public Nfiscais getNfiscais() {
        return this.nfiscais;
    }
    
    public void setNfiscais(Nfiscais nfiscais) {
        this.nfiscais = nfiscais;
    }

    
    @Column(name="ITEM", nullable=false)
    public int getItem() {
        return this.item;
    }
    
    public void setItem(int item) {
        this.item = item;
    }

    
    @Column(name="NR_SERIE_ITEM", length=65535)
    public String getNrSerieItem() {
        return this.nrSerieItem;
    }
    
    public void setNrSerieItem(String nrSerieItem) {
        this.nrSerieItem = nrSerieItem;
    }

    
    @Column(name="CLASS_FISCAL", length=1)
    public String getClassFiscal() {
        return this.classFiscal;
    }
    
    public void setClassFiscal(String classFiscal) {
        this.classFiscal = classFiscal;
    }

    
    @Column(name="STRIBUT")
    public Integer getStribut() {
        return this.stribut;
    }
    
    public void setStribut(Integer stribut) {
        this.stribut = stribut;
    }

    
    @Column(name="qtde_item1_old")
    public Integer getQtdeItem1Old() {
        return this.qtdeItem1Old;
    }
    
    public void setQtdeItem1Old(Integer qtdeItem1Old) {
        this.qtdeItem1Old = qtdeItem1Old;
    }

    
    @Column(name="VLR_UNIT_ITEM", precision=9)
    public BigDecimal getVlrUnitItem() {
        return this.vlrUnitItem;
    }
    
    public void setVlrUnitItem(BigDecimal vlrUnitItem) {
        this.vlrUnitItem = vlrUnitItem;
    }

    
    @Column(name="VLR_TOTAL_ITEM", precision=9)
    public BigDecimal getVlrTotalItem() {
        return this.vlrTotalItem;
    }
    
    public void setVlrTotalItem(BigDecimal vlrTotalItem) {
        this.vlrTotalItem = vlrTotalItem;
    }

    
    @Column(name="ALIQ_ICMS_ITEM", precision=4)
    public BigDecimal getAliqIcmsItem() {
        return this.aliqIcmsItem;
    }
    
    public void setAliqIcmsItem(BigDecimal aliqIcmsItem) {
        this.aliqIcmsItem = aliqIcmsItem;
    }

    
    @Column(name="ALIQ_IPI_ITEM", precision=4)
    public BigDecimal getAliqIpiItem() {
        return this.aliqIpiItem;
    }
    
    public void setAliqIpiItem(BigDecimal aliqIpiItem) {
        this.aliqIpiItem = aliqIpiItem;
    }

    
    @Column(name="VLR_ICMS_ITEM", precision=9)
    public BigDecimal getVlrIcmsItem() {
        return this.vlrIcmsItem;
    }
    
    public void setVlrIcmsItem(BigDecimal vlrIcmsItem) {
        this.vlrIcmsItem = vlrIcmsItem;
    }

    
    @Column(name="VLR_IPI_ITEM", precision=9)
    public BigDecimal getVlrIpiItem() {
        return this.vlrIpiItem;
    }
    
    public void setVlrIpiItem(BigDecimal vlrIpiItem) {
        this.vlrIpiItem = vlrIpiItem;
    }

    
    @Column(name="PESO_BRUTO", precision=9)
    public BigDecimal getPesoBruto() {
        return this.pesoBruto;
    }
    
    public void setPesoBruto(BigDecimal pesoBruto) {
        this.pesoBruto = pesoBruto;
    }

    
    @Column(name="PESO_LIQUIDO", precision=9)
    public BigDecimal getPesoLiquido() {
        return this.pesoLiquido;
    }
    
    public void setPesoLiquido(BigDecimal pesoLiquido) {
        this.pesoLiquido = pesoLiquido;
    }

    
    @Column(name="qtde_item2_old")
    public Integer getQtdeItem2Old() {
        return this.qtdeItem2Old;
    }
    
    public void setQtdeItem2Old(Integer qtdeItem2Old) {
        this.qtdeItem2Old = qtdeItem2Old;
    }

    
    @Column(name="qtde_item3_old")
    public Integer getQtdeItem3Old() {
        return this.qtdeItem3Old;
    }
    
    public void setQtdeItem3Old(Integer qtdeItem3Old) {
        this.qtdeItem3Old = qtdeItem3Old;
    }

    
    @Column(name="VLR_DESC", precision=9)
    public BigDecimal getVlrDesc() {
        return this.vlrDesc;
    }
    
    public void setVlrDesc(BigDecimal vlrDesc) {
        this.vlrDesc = vlrDesc;
    }

    
    @Column(name="PCT_DESC", precision=5)
    public BigDecimal getPctDesc() {
        return this.pctDesc;
    }
    
    public void setPctDesc(BigDecimal pctDesc) {
        this.pctDesc = pctDesc;
    }

    
    @Column(name="VLR_JUROS", precision=9)
    public BigDecimal getVlrJuros() {
        return this.vlrJuros;
    }
    
    public void setVlrJuros(BigDecimal vlrJuros) {
        this.vlrJuros = vlrJuros;
    }

    
    @Column(name="PCT_JUROS", precision=5)
    public BigDecimal getPctJuros() {
        return this.pctJuros;
    }
    
    public void setPctJuros(BigDecimal pctJuros) {
        this.pctJuros = pctJuros;
    }

    
    @Column(name="base_icms_subst_item", precision=9)
    public BigDecimal getBaseIcmsSubstItem() {
        return this.baseIcmsSubstItem;
    }
    
    public void setBaseIcmsSubstItem(BigDecimal baseIcmsSubstItem) {
        this.baseIcmsSubstItem = baseIcmsSubstItem;
    }

    
    @Column(name="vlr_icms_subst_item", precision=9)
    public BigDecimal getVlrIcmsSubstItem() {
        return this.vlrIcmsSubstItem;
    }
    
    public void setVlrIcmsSubstItem(BigDecimal vlrIcmsSubstItem) {
        this.vlrIcmsSubstItem = vlrIcmsSubstItem;
    }

    
    @Column(name="origem_mercadoria")
    public Integer getOrigemMercadoria() {
        return this.origemMercadoria;
    }
    
    public void setOrigemMercadoria(Integer origemMercadoria) {
        this.origemMercadoria = origemMercadoria;
    }

    
    @Column(name="qtde_item4_old")
    public Integer getQtdeItem4Old() {
        return this.qtdeItem4Old;
    }
    
    public void setQtdeItem4Old(Integer qtdeItem4Old) {
        this.qtdeItem4Old = qtdeItem4Old;
    }

    
    @Column(name="qtde_item5_old")
    public Integer getQtdeItem5Old() {
        return this.qtdeItem5Old;
    }
    
    public void setQtdeItem5Old(Integer qtdeItem5Old) {
        this.qtdeItem5Old = qtdeItem5Old;
    }

    
    @Column(name="qtde_item6_old")
    public Integer getQtdeItem6Old() {
        return this.qtdeItem6Old;
    }
    
    public void setQtdeItem6Old(Integer qtdeItem6Old) {
        this.qtdeItem6Old = qtdeItem6Old;
    }

    
    @Column(name="qtde_item7_old")
    public Integer getQtdeItem7Old() {
        return this.qtdeItem7Old;
    }
    
    public void setQtdeItem7Old(Integer qtdeItem7Old) {
        this.qtdeItem7Old = qtdeItem7Old;
    }

    
    @Column(name="qtde_item8_old")
    public Integer getQtdeItem8Old() {
        return this.qtdeItem8Old;
    }
    
    public void setQtdeItem8Old(Integer qtdeItem8Old) {
        this.qtdeItem8Old = qtdeItem8Old;
    }

    
    @Column(name="qtde_item9_old")
    public Integer getQtdeItem9Old() {
        return this.qtdeItem9Old;
    }
    
    public void setQtdeItem9Old(Integer qtdeItem9Old) {
        this.qtdeItem9Old = qtdeItem9Old;
    }

    
    @Column(name="qtde_item10_old")
    public Integer getQtdeItem10Old() {
        return this.qtdeItem10Old;
    }
    
    public void setQtdeItem10Old(Integer qtdeItem10Old) {
        this.qtdeItem10Old = qtdeItem10Old;
    }

    
    @Column(name="qtde_item")
    public Integer getQtdeItem() {
        return this.qtdeItem;
    }
    
    public void setQtdeItem(Integer qtdeItem) {
        this.qtdeItem = qtdeItem;
    }

    
    @Column(name="vlr_frete_item", precision=9)
    public BigDecimal getVlrFreteItem() {
        return this.vlrFreteItem;
    }
    
    public void setVlrFreteItem(BigDecimal vlrFreteItem) {
        this.vlrFreteItem = vlrFreteItem;
    }

    
    @Column(name="vlr_seguro_item", precision=9)
    public BigDecimal getVlrSeguroItem() {
        return this.vlrSeguroItem;
    }
    
    public void setVlrSeguroItem(BigDecimal vlrSeguroItem) {
        this.vlrSeguroItem = vlrSeguroItem;
    }

    
    @Column(name="vlr_desp_acess_item", precision=9)
    public BigDecimal getVlrDespAcessItem() {
        return this.vlrDespAcessItem;
    }
    
    public void setVlrDespAcessItem(BigDecimal vlrDespAcessItem) {
        this.vlrDespAcessItem = vlrDespAcessItem;
    }

    
    @Column(name="base_ii_item", precision=9)
    public BigDecimal getBaseIiItem() {
        return this.baseIiItem;
    }
    
    public void setBaseIiItem(BigDecimal baseIiItem) {
        this.baseIiItem = baseIiItem;
    }

    
    @Column(name="vlr_ii_item", precision=9)
    public BigDecimal getVlrIiItem() {
        return this.vlrIiItem;
    }
    
    public void setVlrIiItem(BigDecimal vlrIiItem) {
        this.vlrIiItem = vlrIiItem;
    }

    
    @Column(name="vlr_desp_adu_item", precision=9)
    public BigDecimal getVlrDespAduItem() {
        return this.vlrDespAduItem;
    }
    
    public void setVlrDespAduItem(BigDecimal vlrDespAduItem) {
        this.vlrDespAduItem = vlrDespAduItem;
    }

    
    @Column(name="vlr_iof_item", precision=9)
    public BigDecimal getVlrIofItem() {
        return this.vlrIofItem;
    }
    
    public void setVlrIofItem(BigDecimal vlrIofItem) {
        this.vlrIofItem = vlrIofItem;
    }

    
    @Column(name="numero_di", length=10)
    public String getNumeroDi() {
        return this.numeroDi;
    }
    
    public void setNumeroDi(String numeroDi) {
        this.numeroDi = numeroDi;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_di", length=10)
    public Date getDataDi() {
        return this.dataDi;
    }
    
    public void setDataDi(Date dataDi) {
        this.dataDi = dataDi;
    }

    
    @Column(name="local_desemb", length=60)
    public String getLocalDesemb() {
        return this.localDesemb;
    }
    
    public void setLocalDesemb(String localDesemb) {
        this.localDesemb = localDesemb;
    }

    
    @Column(name="uf_desemb", length=2)
    public String getUfDesemb() {
        return this.ufDesemb;
    }
    
    public void setUfDesemb(String ufDesemb) {
        this.ufDesemb = ufDesemb;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_desemb", length=10)
    public Date getDataDesemb() {
        return this.dataDesemb;
    }
    
    public void setDataDesemb(Date dataDesemb) {
        this.dataDesemb = dataDesemb;
    }

    
    @Column(name="codigo_exportador", length=60)
    public String getCodigoExportador() {
        return this.codigoExportador;
    }
    
    public void setCodigoExportador(String codigoExportador) {
        this.codigoExportador = codigoExportador;
    }

    
    @Column(name="base_icms_item", precision=9)
    public BigDecimal getBaseIcmsItem() {
        return this.baseIcmsItem;
    }
    
    public void setBaseIcmsItem(BigDecimal baseIcmsItem) {
        this.baseIcmsItem = baseIcmsItem;
    }

    
    @Column(name="numero_estoque")
    public Integer getNumeroEstoque() {
        return this.numeroEstoque;
    }
    
    public void setNumeroEstoque(Integer numeroEstoque) {
        this.numeroEstoque = numeroEstoque;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nfiscaisItens")
    public Set<NfiscaisItensAdicao> getNfiscaisItensAdicaos() {
        return this.nfiscaisItensAdicaos;
    }
    
    public void setNfiscaisItensAdicaos(Set<NfiscaisItensAdicao> nfiscaisItensAdicaos) {
        this.nfiscaisItensAdicaos = nfiscaisItensAdicaos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nfiscaisItens")
    public Set<Contatos> getContatoses() {
        return this.contatoses;
    }
    
    public void setContatoses(Set<Contatos> contatoses) {
        this.contatoses = contatoses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nfiscaisItens")
    public Set<NfiscaisItensSerie> getNfiscaisItensSeries() {
        return this.nfiscaisItensSeries;
    }
    
    public void setNfiscaisItensSeries(Set<NfiscaisItensSerie> nfiscaisItensSeries) {
        this.nfiscaisItensSeries = nfiscaisItensSeries;
    }




}


