package br.com.msystem.vo;
// Generated 12/03/2013 13:33:49 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * NfiscaisItensSerie generated by hbm2java
 */
@Entity
@Table(name="nfiscais_itens_serie"
    ,catalog="handy"
)
public class NfiscaisItensSerie  implements java.io.Serializable {


     private int nfiscalItemSerieSq;
     private ProdutoNumeroSerie produtoNumeroSerie;
     private NfiscaisItens nfiscaisItens;

    public NfiscaisItensSerie() {
    }

    public NfiscaisItensSerie(ProdutoNumeroSerie produtoNumeroSerie, NfiscaisItens nfiscaisItens) {
       this.produtoNumeroSerie = produtoNumeroSerie;
       this.nfiscaisItens = nfiscaisItens;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="nfiscal_item_serie_sq", unique=true, nullable=false)
    public int getNfiscalItemSerieSq() {
        return this.nfiscalItemSerieSq;
    }
    
    public void setNfiscalItemSerieSq(int nfiscalItemSerieSq) {
        this.nfiscalItemSerieSq = nfiscalItemSerieSq;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="produto_numero_serie_sq", nullable=false)
    public ProdutoNumeroSerie getProdutoNumeroSerie() {
        return this.produtoNumeroSerie;
    }
    
    public void setProdutoNumeroSerie(ProdutoNumeroSerie produtoNumeroSerie) {
        this.produtoNumeroSerie = produtoNumeroSerie;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="nfiscal_item_sq", nullable=false)
    public NfiscaisItens getNfiscaisItens() {
        return this.nfiscaisItens;
    }
    
    public void setNfiscaisItens(NfiscaisItens nfiscaisItens) {
        this.nfiscaisItens = nfiscaisItens;
    }




}


