package br.com.msystem.vo;
// Generated 12/03/2013 13:33:49 by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * NfServicos generated by hbm2java
 */
@Entity
@Table(name="nf_servicos"
    ,catalog="handy"
    , uniqueConstraints = @UniqueConstraint(columnNames="NUMERO_NF_SERVICO") 
)
public class NfServicos  implements java.io.Serializable {


     private int nfServicoSq;
     private Clientes clientes;
     private int numeroNfServico;
     private Date dataNfServico;
     private BigDecimal ttlNfServico;
     private BigDecimal aliqIssNfServico;
     private BigDecimal vlrIssNfServico;

    public NfServicos() {
    }

    public NfServicos(Clientes clientes, int numeroNfServico, Date dataNfServico, BigDecimal ttlNfServico, BigDecimal aliqIssNfServico, BigDecimal vlrIssNfServico) {
       this.clientes = clientes;
       this.numeroNfServico = numeroNfServico;
       this.dataNfServico = dataNfServico;
       this.ttlNfServico = ttlNfServico;
       this.aliqIssNfServico = aliqIssNfServico;
       this.vlrIssNfServico = vlrIssNfServico;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="NF_SERVICO_SQ", unique=true, nullable=false)
    public int getNfServicoSq() {
        return this.nfServicoSq;
    }
    
    public void setNfServicoSq(int nfServicoSq) {
        this.nfServicoSq = nfServicoSq;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENTE_SQ", nullable=false)
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }

    
    @Column(name="NUMERO_NF_SERVICO", unique=true, nullable=false)
    public int getNumeroNfServico() {
        return this.numeroNfServico;
    }
    
    public void setNumeroNfServico(int numeroNfServico) {
        this.numeroNfServico = numeroNfServico;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATA_NF_SERVICO", nullable=false, length=19)
    public Date getDataNfServico() {
        return this.dataNfServico;
    }
    
    public void setDataNfServico(Date dataNfServico) {
        this.dataNfServico = dataNfServico;
    }

    
    @Column(name="TTL_NF_SERVICO", nullable=false, precision=9)
    public BigDecimal getTtlNfServico() {
        return this.ttlNfServico;
    }
    
    public void setTtlNfServico(BigDecimal ttlNfServico) {
        this.ttlNfServico = ttlNfServico;
    }

    
    @Column(name="ALIQ_ISS_NF_SERVICO", nullable=false, precision=4)
    public BigDecimal getAliqIssNfServico() {
        return this.aliqIssNfServico;
    }
    
    public void setAliqIssNfServico(BigDecimal aliqIssNfServico) {
        this.aliqIssNfServico = aliqIssNfServico;
    }

    
    @Column(name="VLR_ISS_NF_SERVICO", nullable=false, precision=9)
    public BigDecimal getVlrIssNfServico() {
        return this.vlrIssNfServico;
    }
    
    public void setVlrIssNfServico(BigDecimal vlrIssNfServico) {
        this.vlrIssNfServico = vlrIssNfServico;
    }




}


