package br.com.msystem.vo;
// Generated 12/03/2013 13:33:49 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Notificacao generated by hbm2java
 */
@Entity
@Table(name="notificacao"
    ,catalog="handy"
    , uniqueConstraints = @UniqueConstraint(columnNames="data_notificacao") 
)
public class Notificacao  implements java.io.Serializable {


     private int notificacaoSq;
     private Date dataNotificacao;
     private String nomeUsuario;
     private String ipUsuario;
     private String versaoSoftware;
     private String nomeSoftware;
     private String tituloNotificacao;
     private String mensagem;
     private Character status;

    public Notificacao() {
    }

	
    public Notificacao(Date dataNotificacao) {
        this.dataNotificacao = dataNotificacao;
    }
    public Notificacao(Date dataNotificacao, String nomeUsuario, String ipUsuario, String versaoSoftware, String nomeSoftware, String tituloNotificacao, String mensagem, Character status) {
       this.dataNotificacao = dataNotificacao;
       this.nomeUsuario = nomeUsuario;
       this.ipUsuario = ipUsuario;
       this.versaoSoftware = versaoSoftware;
       this.nomeSoftware = nomeSoftware;
       this.tituloNotificacao = tituloNotificacao;
       this.mensagem = mensagem;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="notificacao_sq", unique=true, nullable=false)
    public int getNotificacaoSq() {
        return this.notificacaoSq;
    }
    
    public void setNotificacaoSq(int notificacaoSq) {
        this.notificacaoSq = notificacaoSq;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_notificacao", unique=true, nullable=false, length=19)
    public Date getDataNotificacao() {
        return this.dataNotificacao;
    }
    
    public void setDataNotificacao(Date dataNotificacao) {
        this.dataNotificacao = dataNotificacao;
    }

    
    @Column(name="nome_usuario", length=50)
    public String getNomeUsuario() {
        return this.nomeUsuario;
    }
    
    public void setNomeUsuario(String nomeUsuario) {
        this.nomeUsuario = nomeUsuario;
    }

    
    @Column(name="ip_usuario", length=15)
    public String getIpUsuario() {
        return this.ipUsuario;
    }
    
    public void setIpUsuario(String ipUsuario) {
        this.ipUsuario = ipUsuario;
    }

    
    @Column(name="versao_software", length=10)
    public String getVersaoSoftware() {
        return this.versaoSoftware;
    }
    
    public void setVersaoSoftware(String versaoSoftware) {
        this.versaoSoftware = versaoSoftware;
    }

    
    @Column(name="nome_software", length=50)
    public String getNomeSoftware() {
        return this.nomeSoftware;
    }
    
    public void setNomeSoftware(String nomeSoftware) {
        this.nomeSoftware = nomeSoftware;
    }

    
    @Column(name="titulo_notificacao", length=100)
    public String getTituloNotificacao() {
        return this.tituloNotificacao;
    }
    
    public void setTituloNotificacao(String tituloNotificacao) {
        this.tituloNotificacao = tituloNotificacao;
    }

    
    @Column(name="mensagem", length=65535)
    public String getMensagem() {
        return this.mensagem;
    }
    
    public void setMensagem(String mensagem) {
        this.mensagem = mensagem;
    }

    
    @Column(name="status", length=1)
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }




}


