package br.com.msystem.vo;
// Generated 12/03/2013 13:33:49 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PedidosItensSerie generated by hbm2java
 */
@Entity
@Table(name="pedidos_itens_serie"
    ,catalog="handy"
)
public class PedidosItensSerie  implements java.io.Serializable {


     private int pedidoItemSerieSq;
     private PedidosItens pedidosItens;
     private ProdutoNumeroSerie produtoNumeroSerie;

    public PedidosItensSerie() {
    }

    public PedidosItensSerie(PedidosItens pedidosItens, ProdutoNumeroSerie produtoNumeroSerie) {
       this.pedidosItens = pedidosItens;
       this.produtoNumeroSerie = produtoNumeroSerie;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="pedido_item_serie_sq", unique=true, nullable=false)
    public int getPedidoItemSerieSq() {
        return this.pedidoItemSerieSq;
    }
    
    public void setPedidoItemSerieSq(int pedidoItemSerieSq) {
        this.pedidoItemSerieSq = pedidoItemSerieSq;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pedido_item_sq", nullable=false)
    public PedidosItens getPedidosItens() {
        return this.pedidosItens;
    }
    
    public void setPedidosItens(PedidosItens pedidosItens) {
        this.pedidosItens = pedidosItens;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="produto_numero_serie_sq", nullable=false)
    public ProdutoNumeroSerie getProdutoNumeroSerie() {
        return this.produtoNumeroSerie;
    }
    
    public void setProdutoNumeroSerie(ProdutoNumeroSerie produtoNumeroSerie) {
        this.produtoNumeroSerie = produtoNumeroSerie;
    }




}


