package br.com.msystem.vo;
// Generated 12/03/2013 13:33:49 by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PedidosItens generated by hbm2java
 */
@Entity
@Table(name="pedidos_itens"
    ,catalog="handy"
)
public class PedidosItens  implements java.io.Serializable {


     private int pedidoItemSq;
     private Pedidos pedidos;
     private Produtos produtos;
     private int qtdePedidoItem;
     private String nrSerieItem;
     private BigDecimal precoUnit;
     private BigDecimal vlrDesc;
     private BigDecimal pctDesc;
     private BigDecimal aliqIcmsItem;
     private BigDecimal aliqIpiItem;
     private BigDecimal vlrIcmsItem;
     private BigDecimal vlrIpiItem;
     private BigDecimal vlrTotalItem;
     private BigDecimal pesoBruto;
     private BigDecimal pesoLiquido;
     private BigDecimal vlrJuros;
     private BigDecimal pctJuros;
     private BigDecimal baseIcmsSubstItem;
     private BigDecimal vlrIcmsSubstItem;
     private Integer numeroEstoque;
     private BigDecimal qtdeProdutoRetorno;
     private Set<PedidosItensSerie> pedidosItensSeries = new HashSet<PedidosItensSerie>(0);
     private Set<Kardex> kardexes = new HashSet<Kardex>(0);

    public PedidosItens() {
    }

	
    public PedidosItens(Pedidos pedidos, Produtos produtos, int qtdePedidoItem) {
        this.pedidos = pedidos;
        this.produtos = produtos;
        this.qtdePedidoItem = qtdePedidoItem;
    }
    public PedidosItens(Pedidos pedidos, Produtos produtos, int qtdePedidoItem, String nrSerieItem, BigDecimal precoUnit, BigDecimal vlrDesc, BigDecimal pctDesc, BigDecimal aliqIcmsItem, BigDecimal aliqIpiItem, BigDecimal vlrIcmsItem, BigDecimal vlrIpiItem, BigDecimal vlrTotalItem, BigDecimal pesoBruto, BigDecimal pesoLiquido, BigDecimal vlrJuros, BigDecimal pctJuros, BigDecimal baseIcmsSubstItem, BigDecimal vlrIcmsSubstItem, Integer numeroEstoque, BigDecimal qtdeProdutoRetorno, Set<PedidosItensSerie> pedidosItensSeries, Set<Kardex> kardexes) {
       this.pedidos = pedidos;
       this.produtos = produtos;
       this.qtdePedidoItem = qtdePedidoItem;
       this.nrSerieItem = nrSerieItem;
       this.precoUnit = precoUnit;
       this.vlrDesc = vlrDesc;
       this.pctDesc = pctDesc;
       this.aliqIcmsItem = aliqIcmsItem;
       this.aliqIpiItem = aliqIpiItem;
       this.vlrIcmsItem = vlrIcmsItem;
       this.vlrIpiItem = vlrIpiItem;
       this.vlrTotalItem = vlrTotalItem;
       this.pesoBruto = pesoBruto;
       this.pesoLiquido = pesoLiquido;
       this.vlrJuros = vlrJuros;
       this.pctJuros = pctJuros;
       this.baseIcmsSubstItem = baseIcmsSubstItem;
       this.vlrIcmsSubstItem = vlrIcmsSubstItem;
       this.numeroEstoque = numeroEstoque;
       this.qtdeProdutoRetorno = qtdeProdutoRetorno;
       this.pedidosItensSeries = pedidosItensSeries;
       this.kardexes = kardexes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PEDIDO_ITEM_SQ", unique=true, nullable=false)
    public int getPedidoItemSq() {
        return this.pedidoItemSq;
    }
    
    public void setPedidoItemSq(int pedidoItemSq) {
        this.pedidoItemSq = pedidoItemSq;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PEDIDO_SQ", nullable=false)
    public Pedidos getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Pedidos pedidos) {
        this.pedidos = pedidos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PRODUTO_SQ", nullable=false)
    public Produtos getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Produtos produtos) {
        this.produtos = produtos;
    }

    
    @Column(name="QTDE_PEDIDO_ITEM", nullable=false)
    public int getQtdePedidoItem() {
        return this.qtdePedidoItem;
    }
    
    public void setQtdePedidoItem(int qtdePedidoItem) {
        this.qtdePedidoItem = qtdePedidoItem;
    }

    
    @Column(name="NR_SERIE_ITEM", length=65535)
    public String getNrSerieItem() {
        return this.nrSerieItem;
    }
    
    public void setNrSerieItem(String nrSerieItem) {
        this.nrSerieItem = nrSerieItem;
    }

    
    @Column(name="PRECO_UNIT", precision=9)
    public BigDecimal getPrecoUnit() {
        return this.precoUnit;
    }
    
    public void setPrecoUnit(BigDecimal precoUnit) {
        this.precoUnit = precoUnit;
    }

    
    @Column(name="VLR_DESC", precision=9)
    public BigDecimal getVlrDesc() {
        return this.vlrDesc;
    }
    
    public void setVlrDesc(BigDecimal vlrDesc) {
        this.vlrDesc = vlrDesc;
    }

    
    @Column(name="PCT_DESC", precision=9)
    public BigDecimal getPctDesc() {
        return this.pctDesc;
    }
    
    public void setPctDesc(BigDecimal pctDesc) {
        this.pctDesc = pctDesc;
    }

    
    @Column(name="ALIQ_ICMS_ITEM", precision=4)
    public BigDecimal getAliqIcmsItem() {
        return this.aliqIcmsItem;
    }
    
    public void setAliqIcmsItem(BigDecimal aliqIcmsItem) {
        this.aliqIcmsItem = aliqIcmsItem;
    }

    
    @Column(name="ALIQ_IPI_ITEM", precision=4)
    public BigDecimal getAliqIpiItem() {
        return this.aliqIpiItem;
    }
    
    public void setAliqIpiItem(BigDecimal aliqIpiItem) {
        this.aliqIpiItem = aliqIpiItem;
    }

    
    @Column(name="VLR_ICMS_ITEM", precision=9)
    public BigDecimal getVlrIcmsItem() {
        return this.vlrIcmsItem;
    }
    
    public void setVlrIcmsItem(BigDecimal vlrIcmsItem) {
        this.vlrIcmsItem = vlrIcmsItem;
    }

    
    @Column(name="VLR_IPI_ITEM", precision=9)
    public BigDecimal getVlrIpiItem() {
        return this.vlrIpiItem;
    }
    
    public void setVlrIpiItem(BigDecimal vlrIpiItem) {
        this.vlrIpiItem = vlrIpiItem;
    }

    
    @Column(name="VLR_TOTAL_ITEM", precision=9)
    public BigDecimal getVlrTotalItem() {
        return this.vlrTotalItem;
    }
    
    public void setVlrTotalItem(BigDecimal vlrTotalItem) {
        this.vlrTotalItem = vlrTotalItem;
    }

    
    @Column(name="PESO_BRUTO", precision=9)
    public BigDecimal getPesoBruto() {
        return this.pesoBruto;
    }
    
    public void setPesoBruto(BigDecimal pesoBruto) {
        this.pesoBruto = pesoBruto;
    }

    
    @Column(name="PESO_LIQUIDO", precision=9)
    public BigDecimal getPesoLiquido() {
        return this.pesoLiquido;
    }
    
    public void setPesoLiquido(BigDecimal pesoLiquido) {
        this.pesoLiquido = pesoLiquido;
    }

    
    @Column(name="VLR_JUROS", precision=9)
    public BigDecimal getVlrJuros() {
        return this.vlrJuros;
    }
    
    public void setVlrJuros(BigDecimal vlrJuros) {
        this.vlrJuros = vlrJuros;
    }

    
    @Column(name="PCT_JUROS", precision=5)
    public BigDecimal getPctJuros() {
        return this.pctJuros;
    }
    
    public void setPctJuros(BigDecimal pctJuros) {
        this.pctJuros = pctJuros;
    }

    
    @Column(name="base_icms_subst_item", precision=9)
    public BigDecimal getBaseIcmsSubstItem() {
        return this.baseIcmsSubstItem;
    }
    
    public void setBaseIcmsSubstItem(BigDecimal baseIcmsSubstItem) {
        this.baseIcmsSubstItem = baseIcmsSubstItem;
    }

    
    @Column(name="vlr_icms_subst_item", precision=9)
    public BigDecimal getVlrIcmsSubstItem() {
        return this.vlrIcmsSubstItem;
    }
    
    public void setVlrIcmsSubstItem(BigDecimal vlrIcmsSubstItem) {
        this.vlrIcmsSubstItem = vlrIcmsSubstItem;
    }

    
    @Column(name="numero_estoque")
    public Integer getNumeroEstoque() {
        return this.numeroEstoque;
    }
    
    public void setNumeroEstoque(Integer numeroEstoque) {
        this.numeroEstoque = numeroEstoque;
    }

    
    @Column(name="qtde_produto_retorno", precision=4, scale=0)
    public BigDecimal getQtdeProdutoRetorno() {
        return this.qtdeProdutoRetorno;
    }
    
    public void setQtdeProdutoRetorno(BigDecimal qtdeProdutoRetorno) {
        this.qtdeProdutoRetorno = qtdeProdutoRetorno;
    }

    
@OneToMany(fetch=FetchType.LAZY, mappedBy="pedidosItens")
    public Set<PedidosItensSerie> getPedidosItensSeries() {
        return this.pedidosItensSeries;
    }
    
    public void setPedidosItensSeries(Set<PedidosItensSerie> pedidosItensSeries) {
        this.pedidosItensSeries = pedidosItensSeries;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pedidosItens")
    public Set<Kardex> getKardexes() {
        return this.kardexes;
    }
    
    public void setKardexes(Set<Kardex> kardexes) {
        this.kardexes = kardexes;
    }




}


