package br.com.msystem.vo;
// Generated 12/03/2013 13:33:49 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProdutoImagem generated by hbm2java
 */
@Entity
@Table(name="produto_imagem"
    ,catalog="handy"
)
public class ProdutoImagem  implements java.io.Serializable {


     private int produtoImagemSq;
     private Produtos produtos;
     private byte[] produtoImagem;

    public ProdutoImagem() {
    }

    public ProdutoImagem(Produtos produtos, byte[] produtoImagem) {
       this.produtos = produtos;
       this.produtoImagem = produtoImagem;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="produto_imagem_sq", unique=true, nullable=false)
    public int getProdutoImagemSq() {
        return this.produtoImagemSq;
    }
    
    public void setProdutoImagemSq(int produtoImagemSq) {
        this.produtoImagemSq = produtoImagemSq;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="produto_sq", nullable=false)
    public Produtos getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Produtos produtos) {
        this.produtos = produtos;
    }

    
    @Column(name="produto_imagem", nullable=false)
    public byte[] getProdutoImagem() {
        return this.produtoImagem;
    }
    
    public void setProdutoImagem(byte[] produtoImagem) {
        this.produtoImagem = produtoImagem;
    }




}


