package br.com.msystem.vo;
// Generated 12/03/2013 13:33:49 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Rma generated by hbm2java
 */
@Entity
@Table(name="rma"
    ,catalog="handy"
    , uniqueConstraints = @UniqueConstraint(columnNames="numero_rma") 
)
public class Rma  implements java.io.Serializable {


     private int rmaSq;
     private int numeroRma;
     private Date dataEntradaNf;
     private Date dataEmissaoNf;
     private Integer numeroNfCliente;
     private String nomeCliente;
     private String enderecoCliente;
     private String emailCliente;
     private String telefoneCliente;
     private String responsavelCliente;
     private Integer nfCompra;
     private Date dataCompra;
     private String lojaCliente;
     private String formaEnvio;
     private Set<RmaItem> rmaItems = new HashSet<RmaItem>(0);

    public Rma() {
    }

	
    public Rma(int numeroRma, Date dataEntradaNf, String nomeCliente) {
        this.numeroRma = numeroRma;
        this.dataEntradaNf = dataEntradaNf;
        this.nomeCliente = nomeCliente;
    }
    public Rma(int numeroRma, Date dataEntradaNf, Date dataEmissaoNf, Integer numeroNfCliente, String nomeCliente, String enderecoCliente, String emailCliente, String telefoneCliente, String responsavelCliente, Integer nfCompra, Date dataCompra, String lojaCliente, String formaEnvio, Set<RmaItem> rmaItems) {
       this.numeroRma = numeroRma;
       this.dataEntradaNf = dataEntradaNf;
       this.dataEmissaoNf = dataEmissaoNf;
       this.numeroNfCliente = numeroNfCliente;
       this.nomeCliente = nomeCliente;
       this.enderecoCliente = enderecoCliente;
       this.emailCliente = emailCliente;
       this.telefoneCliente = telefoneCliente;
       this.responsavelCliente = responsavelCliente;
       this.nfCompra = nfCompra;
       this.dataCompra = dataCompra;
       this.lojaCliente = lojaCliente;
       this.formaEnvio = formaEnvio;
       this.rmaItems = rmaItems;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="rma_sq", unique=true, nullable=false)
    public int getRmaSq() {
        return this.rmaSq;
    }
    
    public void setRmaSq(int rmaSq) {
        this.rmaSq = rmaSq;
    }

    
    @Column(name="numero_rma", unique=true, nullable=false)
    public int getNumeroRma() {
        return this.numeroRma;
    }
    
    public void setNumeroRma(int numeroRma) {
        this.numeroRma = numeroRma;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_entrada_nf", nullable=false, length=10)
    public Date getDataEntradaNf() {
        return this.dataEntradaNf;
    }
    
    public void setDataEntradaNf(Date dataEntradaNf) {
        this.dataEntradaNf = dataEntradaNf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_emissao_nf", length=10)
    public Date getDataEmissaoNf() {
        return this.dataEmissaoNf;
    }
    
    public void setDataEmissaoNf(Date dataEmissaoNf) {
        this.dataEmissaoNf = dataEmissaoNf;
    }

    
    @Column(name="numero_nf_cliente")
    public Integer getNumeroNfCliente() {
        return this.numeroNfCliente;
    }
    
    public void setNumeroNfCliente(Integer numeroNfCliente) {
        this.numeroNfCliente = numeroNfCliente;
    }

    
    @Column(name="nome_cliente", nullable=false, length=50)
    public String getNomeCliente() {
        return this.nomeCliente;
    }
    
    public void setNomeCliente(String nomeCliente) {
        this.nomeCliente = nomeCliente;
    }

    
    @Column(name="endereco_cliente", length=200)
    public String getEnderecoCliente() {
        return this.enderecoCliente;
    }
    
    public void setEnderecoCliente(String enderecoCliente) {
        this.enderecoCliente = enderecoCliente;
    }

    
    @Column(name="email_cliente", length=100)
    public String getEmailCliente() {
        return this.emailCliente;
    }
    
    public void setEmailCliente(String emailCliente) {
        this.emailCliente = emailCliente;
    }

    
    @Column(name="telefone_cliente", length=20)
    public String getTelefoneCliente() {
        return this.telefoneCliente;
    }
    
    public void setTelefoneCliente(String telefoneCliente) {
        this.telefoneCliente = telefoneCliente;
    }

    
    @Column(name="responsavel_cliente", length=50)
    public String getResponsavelCliente() {
        return this.responsavelCliente;
    }
    
    public void setResponsavelCliente(String responsavelCliente) {
        this.responsavelCliente = responsavelCliente;
    }

    
    @Column(name="nf_compra")
    public Integer getNfCompra() {
        return this.nfCompra;
    }
    
    public void setNfCompra(Integer nfCompra) {
        this.nfCompra = nfCompra;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_compra", length=10)
    public Date getDataCompra() {
        return this.dataCompra;
    }
    
    public void setDataCompra(Date dataCompra) {
        this.dataCompra = dataCompra;
    }

    
    @Column(name="loja_cliente", length=100)
    public String getLojaCliente() {
        return this.lojaCliente;
    }
    
    public void setLojaCliente(String lojaCliente) {
        this.lojaCliente = lojaCliente;
    }

    
    @Column(name="forma_envio", length=20)
    public String getFormaEnvio() {
        return this.formaEnvio;
    }
    
    public void setFormaEnvio(String formaEnvio) {
        this.formaEnvio = formaEnvio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rma")
    public Set<RmaItem> getRmaItems() {
        return this.rmaItems;
    }
    
    public void setRmaItems(Set<RmaItem> rmaItems) {
        this.rmaItems = rmaItems;
    }




}


