package br.com.msystem.vo;
// Generated 12/03/2013 13:33:49 by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RmaItem generated by hbm2java
 */
@Entity
@Table(name="rma_item"
    ,catalog="handy"
)
public class RmaItem  implements java.io.Serializable {


     private int rmaItemSq;
     private Produtos produtos;
     private Rma rma;
     private String nrSerieProduto;
     private int qtdeProduto;
     private String acessorioProduto;
     private BigDecimal vlrUnitProduto;
     private String defeitoProduto;
     private Date dataRetornoProduto;
     private Integer nfDevolucaoProduto;
     private String finalizacaoProduto;

    public RmaItem() {
    }

	
    public RmaItem(Produtos produtos, Rma rma, int qtdeProduto) {
        this.produtos = produtos;
        this.rma = rma;
        this.qtdeProduto = qtdeProduto;
    }
    public RmaItem(Produtos produtos, Rma rma, String nrSerieProduto, int qtdeProduto, String acessorioProduto, BigDecimal vlrUnitProduto, String defeitoProduto, Date dataRetornoProduto, Integer nfDevolucaoProduto, String finalizacaoProduto) {
       this.produtos = produtos;
       this.rma = rma;
       this.nrSerieProduto = nrSerieProduto;
       this.qtdeProduto = qtdeProduto;
       this.acessorioProduto = acessorioProduto;
       this.vlrUnitProduto = vlrUnitProduto;
       this.defeitoProduto = defeitoProduto;
       this.dataRetornoProduto = dataRetornoProduto;
       this.nfDevolucaoProduto = nfDevolucaoProduto;
       this.finalizacaoProduto = finalizacaoProduto;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="rma_item_sq", unique=true, nullable=false)
    public int getRmaItemSq() {
        return this.rmaItemSq;
    }
    
    public void setRmaItemSq(int rmaItemSq) {
        this.rmaItemSq = rmaItemSq;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="produto_sq", nullable=false)
    public Produtos getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Produtos produtos) {
        this.produtos = produtos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="rma_sq", nullable=false)
    public Rma getRma() {
        return this.rma;
    }
    
    public void setRma(Rma rma) {
        this.rma = rma;
    }

    
    @Column(name="nr_serie_produto", length=100)
    public String getNrSerieProduto() {
        return this.nrSerieProduto;
    }
    
    public void setNrSerieProduto(String nrSerieProduto) {
        this.nrSerieProduto = nrSerieProduto;
    }

    
    @Column(name="qtde_produto", nullable=false)
    public int getQtdeProduto() {
        return this.qtdeProduto;
    }
    
    public void setQtdeProduto(int qtdeProduto) {
        this.qtdeProduto = qtdeProduto;
    }

    
    @Column(name="acessorio_produto", length=100)
    public String getAcessorioProduto() {
        return this.acessorioProduto;
    }
    
    public void setAcessorioProduto(String acessorioProduto) {
        this.acessorioProduto = acessorioProduto;
    }

    
    @Column(name="vlr_unit_produto", precision=9)
    public BigDecimal getVlrUnitProduto() {
        return this.vlrUnitProduto;
    }
    
    public void setVlrUnitProduto(BigDecimal vlrUnitProduto) {
        this.vlrUnitProduto = vlrUnitProduto;
    }

    
    @Column(name="defeito_produto", length=100)
    public String getDefeitoProduto() {
        return this.defeitoProduto;
    }
    
    public void setDefeitoProduto(String defeitoProduto) {
        this.defeitoProduto = defeitoProduto;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_retorno_produto", length=19)
    public Date getDataRetornoProduto() {
        return this.dataRetornoProduto;
    }
    
    public void setDataRetornoProduto(Date dataRetornoProduto) {
        this.dataRetornoProduto = dataRetornoProduto;
    }

    
    @Column(name="nf_devolucao_produto")
    public Integer getNfDevolucaoProduto() {
        return this.nfDevolucaoProduto;
    }
    
    public void setNfDevolucaoProduto(Integer nfDevolucaoProduto) {
        this.nfDevolucaoProduto = nfDevolucaoProduto;
    }

    
    @Column(name="finalizacao_produto", length=100)
    public String getFinalizacaoProduto() {
        return this.finalizacaoProduto;
    }
    
    public void setFinalizacaoProduto(String finalizacaoProduto) {
        this.finalizacaoProduto = finalizacaoProduto;
    }




}


