package br.com.msystem.vo;
// Generated 12/03/2013 13:33:49 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TipoCliente generated by hbm2java
 */
@Entity
@Table(name="tipo_cliente"
    ,catalog="handy"
    , uniqueConstraints = @UniqueConstraint(columnNames="descricao_tipo") 
)
public class TipoCliente  implements java.io.Serializable {


     private int tipoClienteSq;
     private String descricaoTipo;
     private Set<Clientes> clienteses = new HashSet<Clientes>(0);

    public TipoCliente() {
    }

	
    public TipoCliente(String descricaoTipo) {
        this.descricaoTipo = descricaoTipo;
    }
    public TipoCliente(String descricaoTipo, Set<Clientes> clienteses) {
       this.descricaoTipo = descricaoTipo;
       this.clienteses = clienteses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="tipo_cliente_sq", unique=true, nullable=false)
    public int getTipoClienteSq() {
        return this.tipoClienteSq;
    }
    
    public void setTipoClienteSq(int tipoClienteSq) {
        this.tipoClienteSq = tipoClienteSq;
    }

    
    @Column(name="descricao_tipo", unique=true, nullable=false, length=100)
    public String getDescricaoTipo() {
        return this.descricaoTipo;
    }
    
    public void setDescricaoTipo(String descricaoTipo) {
        this.descricaoTipo = descricaoTipo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoCliente")
    public Set<Clientes> getClienteses() {
        return this.clienteses;
    }
    
    public void setClienteses(Set<Clientes> clienteses) {
        this.clienteses = clienteses;
    }




}


