package br.com.msystem.vo;
// Generated 12/03/2013 13:33:49 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Transportadoras generated by hbm2java
 */
@Entity
@Table(name="transportadoras"
    ,catalog="handy"
    , uniqueConstraints = @UniqueConstraint(columnNames="CODIGO_TRANSPORTADORA") 
)
public class Transportadoras  implements java.io.Serializable {


     private int transportadoraSq;
     private String codigoTransportadora;
     private String nomeTransportadora;
     private String enderecoTransportadora;
     private String municipioTransportadora;
     private String estadoTransportadora;
     private String inscrEstadual;
     private String dddFone;
     private String numeroFone;
     private String complFone;
     private Set<Nfiscais> nfiscaises = new HashSet<Nfiscais>(0);
     private Set<Pedidos> pedidoses = new HashSet<Pedidos>(0);
     private Set<Clientes> clienteses = new HashSet<Clientes>(0);

    public Transportadoras() {
    }

	
    public Transportadoras(String codigoTransportadora) {
        this.codigoTransportadora = codigoTransportadora;
    }
    public Transportadoras(String codigoTransportadora, String nomeTransportadora, String enderecoTransportadora, String municipioTransportadora, String estadoTransportadora, String inscrEstadual, String dddFone, String numeroFone, String complFone, Set<Nfiscais> nfiscaises, Set<Pedidos> pedidoses, Set<Clientes> clienteses) {
       this.codigoTransportadora = codigoTransportadora;
       this.nomeTransportadora = nomeTransportadora;
       this.enderecoTransportadora = enderecoTransportadora;
       this.municipioTransportadora = municipioTransportadora;
       this.estadoTransportadora = estadoTransportadora;
       this.inscrEstadual = inscrEstadual;
       this.dddFone = dddFone;
       this.numeroFone = numeroFone;
       this.complFone = complFone;
       this.nfiscaises = nfiscaises;
       this.pedidoses = pedidoses;
       this.clienteses = clienteses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="TRANSPORTADORA_SQ", unique=true, nullable=false)
    public int getTransportadoraSq() {
        return this.transportadoraSq;
    }
    
    public void setTransportadoraSq(int transportadoraSq) {
        this.transportadoraSq = transportadoraSq;
    }

    
    @Column(name="CODIGO_TRANSPORTADORA", unique=true, nullable=false, length=15)
    public String getCodigoTransportadora() {
        return this.codigoTransportadora;
    }
    
    public void setCodigoTransportadora(String codigoTransportadora) {
        this.codigoTransportadora = codigoTransportadora;
    }

    
    @Column(name="NOME_TRANSPORTADORA", length=50)
    public String getNomeTransportadora() {
        return this.nomeTransportadora;
    }
    
    public void setNomeTransportadora(String nomeTransportadora) {
        this.nomeTransportadora = nomeTransportadora;
    }

    
    @Column(name="ENDERECO_TRANSPORTADORA", length=50)
    public String getEnderecoTransportadora() {
        return this.enderecoTransportadora;
    }
    
    public void setEnderecoTransportadora(String enderecoTransportadora) {
        this.enderecoTransportadora = enderecoTransportadora;
    }

    
    @Column(name="MUNICIPIO_TRANSPORTADORA", length=30)
    public String getMunicipioTransportadora() {
        return this.municipioTransportadora;
    }
    
    public void setMunicipioTransportadora(String municipioTransportadora) {
        this.municipioTransportadora = municipioTransportadora;
    }

    
    @Column(name="ESTADO_TRANSPORTADORA", length=2)
    public String getEstadoTransportadora() {
        return this.estadoTransportadora;
    }
    
    public void setEstadoTransportadora(String estadoTransportadora) {
        this.estadoTransportadora = estadoTransportadora;
    }

    
    @Column(name="INSCR_ESTADUAL", length=20)
    public String getInscrEstadual() {
        return this.inscrEstadual;
    }
    
    public void setInscrEstadual(String inscrEstadual) {
        this.inscrEstadual = inscrEstadual;
    }

    
    @Column(name="DDD_FONE", length=4)
    public String getDddFone() {
        return this.dddFone;
    }
    
    public void setDddFone(String dddFone) {
        this.dddFone = dddFone;
    }

    
    @Column(name="NUMERO_FONE", length=15)
    public String getNumeroFone() {
        return this.numeroFone;
    }
    
    public void setNumeroFone(String numeroFone) {
        this.numeroFone = numeroFone;
    }

    
    @Column(name="COMPL_FONE", length=10)
    public String getComplFone() {
        return this.complFone;
    }
    
    public void setComplFone(String complFone) {
        this.complFone = complFone;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="transportadoras")
    public Set<Nfiscais> getNfiscaises() {
        return this.nfiscaises;
    }
    
    public void setNfiscaises(Set<Nfiscais> nfiscaises) {
        this.nfiscaises = nfiscaises;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="transportadoras")
    public Set<Pedidos> getPedidoses() {
        return this.pedidoses;
    }
    
    public void setPedidoses(Set<Pedidos> pedidoses) {
        this.pedidoses = pedidoses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="transportadoras")
    public Set<Clientes> getClienteses() {
        return this.clienteses;
    }
    
    public void setClienteses(Set<Clientes> clienteses) {
        this.clienteses = clienteses;
    }




}


