package br.com.msystem.vo;
// Generated 12/03/2013 13:33:49 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name="usuarios"
    ,catalog="handy"
    , uniqueConstraints = @UniqueConstraint(columnNames="CODIGO_USUARIO") 
)
public class Usuarios  implements java.io.Serializable {


     private int usuarioSq;
     private Vendedores vendedores;
     private String codigoUsuario;
     private String nomeUsuario;
     private String senhaUsuario;
     private String erroEmailFrom;
     private String erroNomeFrom;
     private String erroEmailTo;
     private String erroNomeTo;
     private String erroSmtp;
     private String erroUsername;
     private String erroPassword;
     private byte[] foto;
     private String fotoUsuario;
     private Set<Clientes> clienteses = new HashSet<Clientes>(0);
     private Set<HistoricoLogin> historicoLogins = new HashSet<HistoricoLogin>(0);
     private Set<HistoricoAcesso> historicoAcessos = new HashSet<HistoricoAcesso>(0);
     private Set<HistAlteracoes> histAlteracoeses = new HashSet<HistAlteracoes>(0);
     private Set<Kardex> kardexes = new HashSet<Kardex>(0);
     private Set<Acessos> acessoses = new HashSet<Acessos>(0);

    public Usuarios() {
    }

	
    public Usuarios(String codigoUsuario, String nomeUsuario) {
        this.codigoUsuario = codigoUsuario;
        this.nomeUsuario = nomeUsuario;
    }
    public Usuarios(Vendedores vendedores, String codigoUsuario, String nomeUsuario, String senhaUsuario, String erroEmailFrom, String erroNomeFrom, String erroEmailTo, String erroNomeTo, String erroSmtp, String erroUsername, String erroPassword, byte[] foto, String fotoUsuario, Set<Clientes> clienteses, Set<HistoricoLogin> historicoLogins, Set<HistoricoAcesso> historicoAcessos, Set<HistAlteracoes> histAlteracoeses, Set<Kardex> kardexes, Set<Acessos> acessoses) {
       this.vendedores = vendedores;
       this.codigoUsuario = codigoUsuario;
       this.nomeUsuario = nomeUsuario;
       this.senhaUsuario = senhaUsuario;
       this.erroEmailFrom = erroEmailFrom;
       this.erroNomeFrom = erroNomeFrom;
       this.erroEmailTo = erroEmailTo;
       this.erroNomeTo = erroNomeTo;
       this.erroSmtp = erroSmtp;
       this.erroUsername = erroUsername;
       this.erroPassword = erroPassword;
       this.foto = foto;
       this.fotoUsuario = fotoUsuario;
       this.clienteses = clienteses;
       this.historicoLogins = historicoLogins;
       this.historicoAcessos = historicoAcessos;
       this.histAlteracoeses = histAlteracoeses;
       this.kardexes = kardexes;
       this.acessoses = acessoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="USUARIO_SQ", unique=true, nullable=false)
    public int getUsuarioSq() {
        return this.usuarioSq;
    }
    
    public void setUsuarioSq(int usuarioSq) {
        this.usuarioSq = usuarioSq;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="VENDEDOR_SQ")
    public Vendedores getVendedores() {
        return this.vendedores;
    }
    
    public void setVendedores(Vendedores vendedores) {
        this.vendedores = vendedores;
    }

    
    @Column(name="CODIGO_USUARIO", unique=true, nullable=false, length=20)
    public String getCodigoUsuario() {
        return this.codigoUsuario;
    }
    
    public void setCodigoUsuario(String codigoUsuario) {
        this.codigoUsuario = codigoUsuario;
    }

    
    @Column(name="NOME_USUARIO", nullable=false, length=50)
    public String getNomeUsuario() {
        return this.nomeUsuario;
    }
    
    public void setNomeUsuario(String nomeUsuario) {
        this.nomeUsuario = nomeUsuario;
    }

    
    @Column(name="SENHA_USUARIO", length=50)
    public String getSenhaUsuario() {
        return this.senhaUsuario;
    }
    
    public void setSenhaUsuario(String senhaUsuario) {
        this.senhaUsuario = senhaUsuario;
    }

    
    @Column(name="ERRO_EMAIL_FROM", length=50)
    public String getErroEmailFrom() {
        return this.erroEmailFrom;
    }
    
    public void setErroEmailFrom(String erroEmailFrom) {
        this.erroEmailFrom = erroEmailFrom;
    }

    
    @Column(name="ERRO_NOME_FROM", length=50)
    public String getErroNomeFrom() {
        return this.erroNomeFrom;
    }
    
    public void setErroNomeFrom(String erroNomeFrom) {
        this.erroNomeFrom = erroNomeFrom;
    }

    
    @Column(name="ERRO_EMAIL_TO", length=50)
    public String getErroEmailTo() {
        return this.erroEmailTo;
    }
    
    public void setErroEmailTo(String erroEmailTo) {
        this.erroEmailTo = erroEmailTo;
    }

    
    @Column(name="ERRO_NOME_TO", length=50)
    public String getErroNomeTo() {
        return this.erroNomeTo;
    }
    
    public void setErroNomeTo(String erroNomeTo) {
        this.erroNomeTo = erroNomeTo;
    }

    
    @Column(name="ERRO_SMTP", length=50)
    public String getErroSmtp() {
        return this.erroSmtp;
    }
    
    public void setErroSmtp(String erroSmtp) {
        this.erroSmtp = erroSmtp;
    }

    
    @Column(name="ERRO_USERNAME", length=50)
    public String getErroUsername() {
        return this.erroUsername;
    }
    
    public void setErroUsername(String erroUsername) {
        this.erroUsername = erroUsername;
    }

    
    @Column(name="ERRO_PASSWORD", length=50)
    public String getErroPassword() {
        return this.erroPassword;
    }
    
    public void setErroPassword(String erroPassword) {
        this.erroPassword = erroPassword;
    }

    
    @Column(name="foto")
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }

    
    @Column(name="foto_usuario", length=50)
    public String getFotoUsuario() {
        return this.fotoUsuario;
    }
    
    public void setFotoUsuario(String fotoUsuario) {
        this.fotoUsuario = fotoUsuario;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuarios")
    public Set<Clientes> getClienteses() {
        return this.clienteses;
    }
    
    public void setClienteses(Set<Clientes> clienteses) {
        this.clienteses = clienteses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuarios")
    public Set<HistoricoLogin> getHistoricoLogins() {
        return this.historicoLogins;
    }
    
    public void setHistoricoLogins(Set<HistoricoLogin> historicoLogins) {
        this.historicoLogins = historicoLogins;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuarios")
    public Set<HistoricoAcesso> getHistoricoAcessos() {
        return this.historicoAcessos;
    }
    
    public void setHistoricoAcessos(Set<HistoricoAcesso> historicoAcessos) {
        this.historicoAcessos = historicoAcessos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuarios")
    public Set<HistAlteracoes> getHistAlteracoeses() {
        return this.histAlteracoeses;
    }
    
    public void setHistAlteracoeses(Set<HistAlteracoes> histAlteracoeses) {
        this.histAlteracoeses = histAlteracoeses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuarios")
    public Set<Kardex> getKardexes() {
        return this.kardexes;
    }
    
    public void setKardexes(Set<Kardex> kardexes) {
        this.kardexes = kardexes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuarios")
    public Set<Acessos> getAcessoses() {
        return this.acessoses;
    }
    
    public void setAcessoses(Set<Acessos> acessoses) {
        this.acessoses = acessoses;
    }




}


