package br.com.msystem.vo;
// Generated 12/03/2013 13:33:49 by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Vendedores generated by hbm2java
 */
@Entity
@Table(name="vendedores"
    ,catalog="handy"
    , uniqueConstraints = @UniqueConstraint(columnNames="CODIGO_VENDEDOR") 
)
public class Vendedores  implements java.io.Serializable {


     private int vendedorSq;
     private int codigoVendedor;
     private String nomeVendedor;
     private BigDecimal pctComissaoPropria;
     private BigDecimal pctComissaoParceria;
     private String baseComissao;
     private BigDecimal pctComissaoDesconto;
     private String obsComissaoDesconto;
     private Character tipoVendedor;
     private Date dataCadastro;
     private Date dataInativacao;
     private Integer pctDesconto;
     private Set<Contatos> contatoses = new HashSet<Contatos>(0);
     private Set<Clientes> clienteses = new HashSet<Clientes>(0);
     private Set<Assistencias> assistenciases = new HashSet<Assistencias>(0);
     private Set<Agenda> agendas = new HashSet<Agenda>(0);
     private Set<Pedidos> pedidoses = new HashSet<Pedidos>(0);
     private Set<Nfiscais> nfiscaises = new HashSet<Nfiscais>(0);
     private Set<Usuarios> usuarioses = new HashSet<Usuarios>(0);

    public Vendedores() {
    }

	
    public Vendedores(int codigoVendedor, String nomeVendedor) {
        this.codigoVendedor = codigoVendedor;
        this.nomeVendedor = nomeVendedor;
    }
    public Vendedores(int codigoVendedor, String nomeVendedor, BigDecimal pctComissaoPropria, BigDecimal pctComissaoParceria, String baseComissao, BigDecimal pctComissaoDesconto, String obsComissaoDesconto, Character tipoVendedor, Date dataCadastro, Date dataInativacao, Integer pctDesconto, Set<Contatos> contatoses, Set<Clientes> clienteses, Set<Assistencias> assistenciases, Set<Agenda> agendas, Set<Pedidos> pedidoses, Set<Nfiscais> nfiscaises, Set<Usuarios> usuarioses) {
       this.codigoVendedor = codigoVendedor;
       this.nomeVendedor = nomeVendedor;
       this.pctComissaoPropria = pctComissaoPropria;
       this.pctComissaoParceria = pctComissaoParceria;
       this.baseComissao = baseComissao;
       this.pctComissaoDesconto = pctComissaoDesconto;
       this.obsComissaoDesconto = obsComissaoDesconto;
       this.tipoVendedor = tipoVendedor;
       this.dataCadastro = dataCadastro;
       this.dataInativacao = dataInativacao;
       this.pctDesconto = pctDesconto;
       this.contatoses = contatoses;
       this.clienteses = clienteses;
       this.assistenciases = assistenciases;
       this.agendas = agendas;
       this.pedidoses = pedidoses;
       this.nfiscaises = nfiscaises;
       this.usuarioses = usuarioses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="VENDEDOR_SQ", unique=true, nullable=false)
    public int getVendedorSq() {
        return this.vendedorSq;
    }
    
    public void setVendedorSq(int vendedorSq) {
        this.vendedorSq = vendedorSq;
    }

    
    @Column(name="CODIGO_VENDEDOR", unique=true, nullable=false)
    public int getCodigoVendedor() {
        return this.codigoVendedor;
    }
    
    public void setCodigoVendedor(int codigoVendedor) {
        this.codigoVendedor = codigoVendedor;
    }

    
    @Column(name="NOME_VENDEDOR", nullable=false, length=100)
    public String getNomeVendedor() {
        return this.nomeVendedor;
    }
    
    public void setNomeVendedor(String nomeVendedor) {
        this.nomeVendedor = nomeVendedor;
    }

    
    @Column(name="pct_comissao_propria", precision=4)
    public BigDecimal getPctComissaoPropria() {
        return this.pctComissaoPropria;
    }
    
    public void setPctComissaoPropria(BigDecimal pctComissaoPropria) {
        this.pctComissaoPropria = pctComissaoPropria;
    }

    
    @Column(name="pct_comissao_parceria", precision=4)
    public BigDecimal getPctComissaoParceria() {
        return this.pctComissaoParceria;
    }
    
    public void setPctComissaoParceria(BigDecimal pctComissaoParceria) {
        this.pctComissaoParceria = pctComissaoParceria;
    }

    
    @Column(name="base_comissao", length=1)
    public String getBaseComissao() {
        return this.baseComissao;
    }
    
    public void setBaseComissao(String baseComissao) {
        this.baseComissao = baseComissao;
    }

    
    @Column(name="pct_comissao_desconto", precision=4)
    public BigDecimal getPctComissaoDesconto() {
        return this.pctComissaoDesconto;
    }
    
    public void setPctComissaoDesconto(BigDecimal pctComissaoDesconto) {
        this.pctComissaoDesconto = pctComissaoDesconto;
    }

    
    @Column(name="obs_comissao_desconto", length=100)
    public String getObsComissaoDesconto() {
        return this.obsComissaoDesconto;
    }
    
    public void setObsComissaoDesconto(String obsComissaoDesconto) {
        this.obsComissaoDesconto = obsComissaoDesconto;
    }

    
    @Column(name="tipo_vendedor", length=1)
    public Character getTipoVendedor() {
        return this.tipoVendedor;
    }
    
    public void setTipoVendedor(Character tipoVendedor) {
        this.tipoVendedor = tipoVendedor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_cadastro", length=10)
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_inativacao", length=10)
    public Date getDataInativacao() {
        return this.dataInativacao;
    }
    
    public void setDataInativacao(Date dataInativacao) {
        this.dataInativacao = dataInativacao;
    }

    
    @Column(name="PCT_DESCONTO")
    public Integer getPctDesconto() {
        return this.pctDesconto;
    }
    
    public void setPctDesconto(Integer pctDesconto) {
        this.pctDesconto = pctDesconto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vendedores")
    public Set<Contatos> getContatoses() {
        return this.contatoses;
    }
    
    public void setContatoses(Set<Contatos> contatoses) {
        this.contatoses = contatoses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vendedores")
    public Set<Clientes> getClienteses() {
        return this.clienteses;
    }
    
    public void setClienteses(Set<Clientes> clienteses) {
        this.clienteses = clienteses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vendedores")
    public Set<Assistencias> getAssistenciases() {
        return this.assistenciases;
    }
    
    public void setAssistenciases(Set<Assistencias> assistenciases) {
        this.assistenciases = assistenciases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vendedores")
    public Set<Agenda> getAgendas() {
        return this.agendas;
    }
    
    public void setAgendas(Set<Agenda> agendas) {
        this.agendas = agendas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vendedores")
    public Set<Pedidos> getPedidoses() {
        return this.pedidoses;
    }
    
    public void setPedidoses(Set<Pedidos> pedidoses) {
        this.pedidoses = pedidoses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vendedores")
    public Set<Nfiscais> getNfiscaises() {
        return this.nfiscaises;
    }
    
    public void setNfiscaises(Set<Nfiscais> nfiscaises) {
        this.nfiscaises = nfiscaises;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vendedores")
    public Set<Usuarios> getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set<Usuarios> usuarioses) {
        this.usuarioses = usuarioses;
    }




}


