unit UDMLista;

interface

uses
  SysUtils, Classes, DB, DBClient, MConnect, SConnect;

type
  TDMLista = class(TDataModule)
    cdsListaClientes: TClientDataSet;
    cdsListaDuplicatas: TClientDataSet;
    cdsListaNfiscaisItens: TClientDataSet;
    cdsListaNfiscais: TClientDataSet;
    cdsListaTransportadoras: TClientDataSet;
    cdsListaUsuarios: TClientDataSet;
    cdsListaPedidosItens: TClientDataSet;
    cdsListaNBM: TClientDataSet;
    cdsListaPecas: TClientDataSet;
    cdsListaNaturezas: TClientDataSet;
    cdsListaCondPagto: TClientDataSet;
    cdsCep: TClientDataSet;
    cdsCepCEP: TStringField;
    cdsCepLOGRADOURO: TStringField;
    cdsCepBAIRRO: TStringField;
    cdsCepCIDADE: TStringField;
    cdsCepUF: TStringField;
    cdsListaDuplicatasDUPLICATA_SQ: TIntegerField;
    cdsListaDuplicatasNUMERO_DUPLICATA: TIntegerField;
    cdsListaDuplicatasITEM_DUPLICATA: TIntegerField;
    cdsListaDuplicatasSEQ_DUPLICATA: TIntegerField;
    cdsListaDuplicatasNFISCAL_SQ: TIntegerField;
    cdsListaDuplicatasVALOR_DUPLICATA: TBCDField;
    cdsListaDuplicatasDTEMISSAO_DUPLICATA: TDateTimeField;
    cdsListaDuplicatasDTVENCTO_DUPLICATA: TDateTimeField;
    cdsListaDuplicatasDTPGTO_DUPLICATA: TDateTimeField;
    cdsListaDuplicatasVALORPG_DUPLICATA: TBCDField;
    cdsListaTransportadorasTRANSPORTADORA_SQ: TIntegerField;
    cdsListaTransportadorasCODIGO_TRANSPORTADORA: TStringField;
    cdsListaTransportadorasNOME_TRANSPORTADORA: TStringField;
    cdsListaTransportadorasENDERECO_TRANSPORTADORA: TStringField;
    cdsListaTransportadorasMUNICIPIO_TRANSPORTADORA: TStringField;
    cdsListaTransportadorasESTADO_TRANSPORTADORA: TStringField;
    cdsListaTransportadorasINSCR_ESTADUAL: TStringField;
    cdsListaTransportadorasDDD_FONE: TStringField;
    cdsListaTransportadorasNUMERO_FONE: TStringField;
    cdsListaTransportadorasCOMPL_FONE: TStringField;
    cdsListaClientesCLIENTE_SQ: TIntegerField;
    cdsListaClientesCODIGO_CLIENTE: TStringField;
    cdsListaClientesNOME_CLIENTE: TStringField;
    cdsListaClientesINSCR_ESTADUAL: TStringField;
    cdsListaClientesENDERECO: TStringField;
    cdsListaClientesNUMERO: TStringField;
    cdsListaClientesBAIRRO: TStringField;
    cdsListaClientesCOMPL_ENDERECO: TStringField;
    cdsListaClientesCIDADE: TStringField;
    cdsListaClientesESTADO: TStringField;
    cdsListaClientesCEP: TStringField;
    cdsListaClientesDDD_FONE1: TStringField;
    cdsListaClientesNUMERO_FONE1: TStringField;
    cdsListaClientesCOMPL_FONE1: TStringField;
    cdsListaClientesDDD_FONE2: TStringField;
    cdsListaClientesNUMERO_FONE2: TStringField;
    cdsListaClientesCOMPL_FONE2: TStringField;
    cdsListaClientesDDD_FONE3: TStringField;
    cdsListaClientesNUMERO_FONE3: TStringField;
    cdsListaClientesCOMPL_FONE3: TStringField;
    cdsListaClientesDDD_CELULAR: TStringField;
    cdsListaClientesNUMERO_CELULAR: TStringField;
    cdsListaClientesCOMPL_CELULAR: TStringField;
    cdsListaClientesDDD_FAX: TStringField;
    cdsListaClientesNUMERO_FAX: TStringField;
    cdsListaClientesCOMPL_FAX: TStringField;
    cdsListaClientesE_MAIL: TStringField;
    cdsListaClientesWEB_SITE: TStringField;
    cdsListaClientesCONTATO: TStringField;
    cdsListaClientesPAIS: TStringField;
    cdsListaClientesREVENDA: TStringField;
    cdsListaClientesBIRO: TStringField;
    cdsListaCondPagtoCOND_PAGTO_SQ: TIntegerField;
    cdsListaCondPagtoCODIGO_COND_PAGTO: TIntegerField;
    cdsListaCondPagtoDESCRICAO_COND_PAGTO: TStringField;
    cdsListaCondPagtoPARCELAS: TIntegerField;
    cdsListaCondPagtoD00: TIntegerField;
    cdsListaCondPagtoD01: TIntegerField;
    cdsListaCondPagtoD02: TIntegerField;
    cdsListaCondPagtoD03: TIntegerField;
    cdsListaCondPagtoD04: TIntegerField;
    cdsListaCondPagtoD05: TIntegerField;
    cdsListaCondPagtoD06: TIntegerField;
    cdsListaCondPagtoD07: TIntegerField;
    cdsListaCondPagtoD08: TIntegerField;
    cdsListaCondPagtoD09: TIntegerField;
    cdsListaNaturezasNATUREZA_SQ: TIntegerField;
    cdsListaNaturezasCODIGO_NATUREZA: TIntegerField;
    cdsListaNaturezasDESCRICAO_NATUREZA: TStringField;
    cdsListaNaturezasCFO: TStringField;
    cdsListaNaturezasALIQ_ICMS: TBCDField;
    cdsListaNaturezasALIQ_IPI: TBCDField;
    cdsListaNaturezasENT_SAI: TStringField;
    cdsListaNaturezasUF01: TStringField;
    cdsListaNaturezasUF02: TStringField;
    cdsListaNaturezasUF03: TStringField;
    cdsListaNaturezasUF04: TStringField;
    cdsListaNaturezasUF05: TStringField;
    cdsListaNaturezasUF06: TStringField;
    cdsListaNaturezasUF07: TStringField;
    cdsListaNaturezasUF08: TStringField;
    cdsListaNaturezasUF09: TStringField;
    cdsListaNaturezasUF10: TStringField;
    cdsListaNaturezasUF11: TStringField;
    cdsListaNaturezasUF12: TStringField;
    cdsListaNaturezasUF13: TStringField;
    cdsListaNaturezasUF14: TStringField;
    cdsListaNaturezasUF15: TStringField;
    cdsListaNaturezasUF16: TStringField;
    cdsListaNaturezasUF17: TStringField;
    cdsListaNaturezasUF18: TStringField;
    cdsListaNaturezasUF19: TStringField;
    cdsListaNaturezasUF20: TStringField;
    cdsListaNaturezasUF21: TStringField;
    cdsListaNaturezasUF22: TStringField;
    cdsListaNaturezasUF23: TStringField;
    cdsListaNaturezasUF24: TStringField;
    cdsListaNaturezasUF25: TStringField;
    cdsListaNaturezasUF26: TStringField;
    cdsListaNaturezasUF27: TStringField;
    cdsListaNaturezasUF28: TStringField;
    cdsListaNaturezasUF29: TStringField;
    cdsListaNaturezasUF30: TStringField;
    cdsListaNaturezasISENCAO_IPI: TStringField;
    cdsListaNaturezasISENCAO_ICMS: TStringField;
    cdsListaNaturezasDESCRICAO_NATUREZA_NFISCAL: TStringField;
    cdsListaNBMNBM_SQ: TIntegerField;
    cdsListaNBMCODIGO_NBM: TStringField;
    cdsListaNBMALIQ_ICMS: TBCDField;
    cdsListaNBMALIQ_IPI: TBCDField;
    cdsListaUsuariosUSUARIO_SQ: TIntegerField;
    cdsListaUsuariosCODIGO_USUARIO: TStringField;
    cdsListaUsuariosNOME_USUARIO: TStringField;
    cdsListaUsuariosSENHA_USUARIO: TStringField;
    cdsListaUsuariosERRO_EMAIL_FROM: TStringField;
    cdsListaUsuariosERRO_NOME_FROM: TStringField;
    cdsListaUsuariosERRO_EMAIL_TO: TStringField;
    cdsListaUsuariosERRO_NOME_TO: TStringField;
    cdsListaUsuariosERRO_SMTP: TStringField;
    cdsListaUsuariosERRO_USERNAME: TStringField;
    cdsListaUsuariosERRO_PASSWORD: TStringField;
    cdsBuscaClientes: TClientDataSet;
    cdsBuscaPecas: TClientDataSet;
    cdsBuscaClientesCLIENTE_SQ: TIntegerField;
    cdsBuscaClientesCODIGO_CLIENTE: TStringField;
    cdsBuscaClientesNOME_CLIENTE: TStringField;
    cdsBuscaClientesINSCR_ESTADUAL: TStringField;
    cdsBuscaClientesENDERECO: TStringField;
    cdsBuscaClientesNUMERO: TStringField;
    cdsBuscaClientesBAIRRO: TStringField;
    cdsBuscaClientesCOMPL_ENDERECO: TStringField;
    cdsBuscaClientesCIDADE: TStringField;
    cdsBuscaClientesESTADO: TStringField;
    cdsBuscaClientesCEP: TStringField;
    cdsBuscaClientesDDD_FONE1: TStringField;
    cdsBuscaClientesNUMERO_FONE1: TStringField;
    cdsBuscaClientesCOMPL_FONE1: TStringField;
    cdsBuscaClientesDDD_FONE2: TStringField;
    cdsBuscaClientesNUMERO_FONE2: TStringField;
    cdsBuscaClientesCOMPL_FONE2: TStringField;
    cdsBuscaClientesDDD_FONE3: TStringField;
    cdsBuscaClientesNUMERO_FONE3: TStringField;
    cdsBuscaClientesCOMPL_FONE3: TStringField;
    cdsBuscaClientesDDD_CELULAR: TStringField;
    cdsBuscaClientesNUMERO_CELULAR: TStringField;
    cdsBuscaClientesCOMPL_CELULAR: TStringField;
    cdsBuscaClientesDDD_FAX: TStringField;
    cdsBuscaClientesNUMERO_FAX: TStringField;
    cdsBuscaClientesCOMPL_FAX: TStringField;
    cdsBuscaClientesE_MAIL: TStringField;
    cdsBuscaClientesWEB_SITE: TStringField;
    cdsBuscaClientesCONTATO: TStringField;
    cdsBuscaClientesPAIS: TStringField;
    cdsBuscaClientesREVENDA: TStringField;
    cdsBuscaClientesBIRO: TStringField;
    SCServerLista: TSocketConnection;
    cdsListaNaturezasTIPO_NFISCAL: TIntegerField;
    cdsListaModelos: TClientDataSet;
    cdsListaAssistencias: TClientDataSet;
    cdsListaKardexPecas: TClientDataSet;
    cdsListaAssistenciasItens: TClientDataSet;
    cdsListaAssistenciasEquip: TClientDataSet;
    cdsListaVendedores: TClientDataSet;
    cdsListaVendedoresVENDEDOR_SQ: TIntegerField;
    cdsListaVendedoresCODIGO_VENDEDOR: TIntegerField;
    cdsListaVendedoresNOME_VENDEDOR: TStringField;
    cdsListaClientesCAPITAL_ATUAL: TBCDField;
    cdsListaClientesNOME_FANTASIA: TStringField;
    cdsListaClientesRAMO_ATIVIDADE_SQ: TIntegerField;
    cdsListaClientesFATURAMENTO_MENSAL: TBCDField;
    cdsListaClientesDATA_FUNDACAO: TDateTimeField;
    cdsListaClientesINSCR_MUNICIPAL: TStringField;
    cdsBuscaClientesCAPITAL_ATUAL: TBCDField;
    cdsBuscaClientesNOME_FANTASIA: TStringField;
    cdsBuscaClientesRAMO_ATIVIDADE_SQ: TIntegerField;
    cdsBuscaClientesFATURAMENTO_MENSAL: TBCDField;
    cdsBuscaClientesDATA_FUNDACAO: TDateTimeField;
    cdsBuscaClientesINSCR_MUNICIPAL: TStringField;
    cdsListaAcessos: TClientDataSet;
    cdsListaAcessosACESSO_SQ: TIntegerField;
    cdsListaAcessosNOME_PROGRAMA: TStringField;
    cdsListaAcessosUSUARIO_SQ: TIntegerField;
    cdsListaAcessosVISUALIZAR: TStringField;
    cdsListaAcessosCRIAR: TStringField;
    cdsListaAcessosEDITAR: TStringField;
    cdsListaAcessosAPAGAR: TStringField;
    cdsListaNfiscaisTotais: TClientDataSet;
    cdsListaNfiscaisTotaisULTIMA_VENDA: TDateTimeField;
    cdsListaNfiscaisTotaisPRIMEIRA_VENDA: TDateTimeField;
    cdsListaNfiscaisTotaisMAIOR_VENDA: TBCDField;
    cdsListaNfiscaisTotaisMENOR_VENDA: TBCDField;
    cdsListaNfiscaisTotaisTOTAL_VENDA: TBCDField;
    cdsListaClientesDATA_CADASTRO: TDateTimeField;
    cdsListaClientesDATA_ALT: TDateTimeField;
    cdsListaClientesUSUARIO_SQ_ALT: TIntegerField;
    cdsListaClientesTRANSPORTADORA_SQ: TIntegerField;
    cdsBuscaClientesDATA_CADASTRO: TDateTimeField;
    cdsBuscaClientesDATA_ALT: TDateTimeField;
    cdsBuscaClientesUSUARIO_SQ_ALT: TIntegerField;
    cdsBuscaClientesTRANSPORTADORA_SQ: TIntegerField;
    cdsListaAssistenciasASSISTENCIA_SQ: TIntegerField;
    cdsListaAssistenciasNUMERO_ASSISTENCIA: TIntegerField;
    cdsListaAssistenciasDATA_CHAMADO: TDateTimeField;
    cdsListaAssistenciasDATA_ASSISTENCIA: TDateTimeField;
    cdsListaAssistenciasCOTACAO_DOLAR: TBCDField;
    cdsListaAssistenciasCLIENTE_SQ: TIntegerField;
    cdsListaAssistenciasCOND_PAGTO_SQ: TIntegerField;
    cdsListaAssistenciasDESP_CHAMADO: TBCDField;
    cdsListaAssistenciasDESP_HTEC_AD: TBCDField;
    cdsListaAssistenciasDESP_DESLOC: TBCDField;
    cdsListaAssistenciasVLR_PECAS: TBCDField;
    cdsListaAssistenciasVLR_TOTAL: TBCDField;
    cdsListaAssistenciasHORA_INICIO: TDateTimeField;
    cdsListaAssistenciasHORA_FIM: TDateTimeField;
    cdsListaAssistenciasGARANTIA: TStringField;
    cdsListaAssistenciasCONTRATO: TStringField;
    cdsListaClassificacao: TClientDataSet;
    cdsListaClassificacaoCLASSIFICACAO_SQ: TIntegerField;
    cdsListaClassificacaoCODIGO_CLASSIFICACAO: TStringField;
    cdsListaClassificacaoLIMITE_MINIMO: TBCDField;
    cdsListaClassificacaoLIMITE_MAXIMO: TBCDField;
    cdsListaClassificacaoMESES_BONUS: TIntegerField;
    cdsListaClientesOBSERVACAO: TMemoField;
    cdsListaClientesCLASSIFICACAO_SQ: TIntegerField;
    cdsListaNaturezasOBSERVACAO: TMemoField;
    cdsBuscaClientesOBSERVACAO: TMemoField;
    cdsBuscaClientesCLASSIFICACAO_SQ: TIntegerField;
    cdsListaAssistenciasSERVICOS: TMemoField;
    cdsListaAssistenciasqrListaAssistenciasItens: TDataSetField;
    cdsListaAssistenciasqrListaAssistenciasEquip: TDataSetField;
    cdsListaNFServicos: TClientDataSet;
    cdsListaNFServicosNF_SERVICO_SQ: TIntegerField;
    cdsListaNFServicosNUMERO_NF_SERVICO: TIntegerField;
    cdsListaNFServicosDATA_NF_SERVICO: TDateTimeField;
    cdsListaNFServicosCLIENTE_SQ: TIntegerField;
    cdsListaNFServicosTTL_NF_SERVICO: TBCDField;
    cdsListaNFServicosALIQ_ISS_NF_SERVICO: TBCDField;
    cdsListaNFServicosVLR_ISS_NF_SERVICO: TBCDField;
    cdsListaNFServicosNOME_CLIENTE: TStringField;
    cdsListaKardexModelos: TClientDataSet;
    cdsListaPecasPECA_SQ: TIntegerField;
    cdsListaPecasCODIGO_PECA: TStringField;
    cdsListaPecasDESCRICAO_PECA: TStringField;
    cdsListaPecasQTDE_PECA_LOJA: TIntegerField;
    cdsListaPecasQTDE_PECA_ARMAZEM: TIntegerField;
    cdsListaPecasQTDE_PECA_DEMO: TIntegerField;
    cdsListaPecasQTDE_PECA_DEFEITO: TIntegerField;
    cdsListaPecasQTDE_PECA_EM_USO: TIntegerField;
    cdsListaPecasQTDE_PECA_BACKUP: TIntegerField;
    cdsListaPecasQTDE_PECA_DEMO_CLI: TIntegerField;
    cdsListaPecasQTDE_PECA_HLC: TIntegerField;
    cdsListaPecasNBM_SQ: TIntegerField;
    cdsListaPecasMODELO_SQ: TIntegerField;
    cdsListaPecasUN_PECA: TStringField;
    cdsListaPecasMARCA_PECA: TStringField;
    cdsListaPecasPRECO_UNIT_PECA: TBCDField;
    cdsListaPecasTIPO_PECA: TIntegerField;
    cdsListaPecasDESCRICAO_MODELO: TStringField;
    cdsListaPecasCODIGO_NBM: TStringField;
    cdsListaPecasALIQ_ICMS: TBCDField;
    cdsListaPecasALIQ_IPI: TBCDField;
    cdsListaAssistenciasItensASSISTENCIA_ITEM_SQ: TIntegerField;
    cdsListaAssistenciasItensASSISTENCIA_SQ: TIntegerField;
    cdsListaAssistenciasItensPECA_SQ: TIntegerField;
    cdsListaAssistenciasItensQTDE_ASSISTENCIA_ITEM: TIntegerField;
    cdsListaAssistenciasItensPRECO_UNIT: TBCDField;
    cdsListaAssistenciasItensDESCRICAO_PECA: TStringField;
    cdsListaKardexPecasKARDEX_PECA_SQ: TIntegerField;
    cdsListaKardexPecasPECA_SQ: TIntegerField;
    cdsListaKardexPecasTIPO_MOV: TStringField;
    cdsListaKardexPecasQTDE: TIntegerField;
    cdsListaKardexPecasVALOR: TBCDField;
    cdsListaKardexPecasDATA: TDateTimeField;
    cdsListaKardexPecasNFISCAL: TIntegerField;
    cdsListaKardexPecasUSUARIO_SQ: TIntegerField;
    cdsListaKardexPecasNR_SERIE: TMemoField;
    cdsListaKardexModelosKARDEX_MOD_SQ: TIntegerField;
    cdsListaKardexModelosMODELO_SQ: TIntegerField;
    cdsListaKardexModelosTIPO_MOV: TStringField;
    cdsListaKardexModelosQTDE: TIntegerField;
    cdsListaKardexModelosVALOR: TBCDField;
    cdsListaKardexModelosDATA: TDateTimeField;
    cdsListaKardexModelosNFISCAL: TIntegerField;
    cdsListaKardexModelosUSUARIO_SQ: TIntegerField;
    cdsListaKardexModelosNR_SERIE: TMemoField;
    cdsListaPedidosItensPEDIDO_ITEM_SQ: TIntegerField;
    cdsListaPedidosItensPEDIDO_SQ: TIntegerField;
    cdsListaPedidosItensTIPO_ITEM: TStringField;
    cdsListaPedidosItensPECA_SQ: TIntegerField;
    cdsListaPedidosItensMODELO_SQ: TIntegerField;
    cdsListaPedidosItensQTDE_PEDIDO_ITEM: TIntegerField;
    cdsListaPedidosItensNR_SERIE_ITEM: TMemoField;
    cdsListaPedidosItensPRECO_UNIT: TBCDField;
    cdsListaPedidosItensVLR_DESC: TBCDField;
    cdsListaPedidosItensPCT_DESC: TBCDField;
    cdsListaPedidosItensALIQ_ICMS_ITEM: TBCDField;
    cdsListaPedidosItensALIQ_IPI_ITEM: TBCDField;
    cdsListaPedidosItensVLR_ICMS_ITEM: TBCDField;
    cdsListaPedidosItensVLR_IPI_ITEM: TBCDField;
    cdsListaPedidosItensVLR_TOTAL_ITEM: TBCDField;
    cdsListaPedidosItensCODIGO_PECA: TStringField;
    cdsListaPedidosItensDESCRICAO_PECA: TStringField;
    cdsListaPedidosItensQTDE_PECA_LOJA: TIntegerField;
    cdsListaPedidosItensQTDE_PECA_ARMAZEM: TIntegerField;
    cdsListaPedidosItensCODIGO_NBM: TStringField;
    cdsListaNfiscaisNFISCAL_SQ: TIntegerField;
    cdsListaNfiscaisNUMERO_NFISCAL: TIntegerField;
    cdsListaNfiscaisDTEMISSAO_NFISCAL: TDateTimeField;
    cdsListaNfiscaisDTSAIDA_NFISCAL: TDateTimeField;
    cdsListaNfiscaisPEDIDO_SQ: TIntegerField;
    cdsListaNfiscaisCLIENTE_SQ: TIntegerField;
    cdsListaNfiscaisCOND_PAGTO_SQ: TIntegerField;
    cdsListaNfiscaisNATUREZA_SQ: TIntegerField;
    cdsListaNfiscaisTRANSPORTADORA_SQ: TIntegerField;
    cdsListaNfiscaisBASE_ICMS: TBCDField;
    cdsListaNfiscaisVLR_ICMS: TBCDField;
    cdsListaNfiscaisBASE_ICMS_SUBST: TBCDField;
    cdsListaNfiscaisVLR_ICMS_SUBST: TBCDField;
    cdsListaNfiscaisVLR_PRODUTOS: TBCDField;
    cdsListaNfiscaisVLR_FRETE: TBCDField;
    cdsListaNfiscaisVLR_SEGURO: TBCDField;
    cdsListaNfiscaisVLR_DESP_ACESS: TBCDField;
    cdsListaNfiscaisVLR_IPI: TBCDField;
    cdsListaNfiscaisVLR_TOTAL: TBCDField;
    cdsListaNfiscaisFRETE_TRANSP: TStringField;
    cdsListaNfiscaisPLACA_TRANSP: TStringField;
    cdsListaNfiscaisUF_PLACA_TRANSP: TStringField;
    cdsListaNfiscaisQTDE_TRANSP: TIntegerField;
    cdsListaNfiscaisESPECIE_TRANSP: TStringField;
    cdsListaNfiscaisMARCA_TRANSP: TStringField;
    cdsListaNfiscaisNUMERO_TRANSP: TStringField;
    cdsListaNfiscaisPBRUTO_TRANSP: TStringField;
    cdsListaNfiscaisPLIQUIDO_TRANSP: TStringField;
    cdsListaNfiscaisCLASS_FISCAL1: TIntegerField;
    cdsListaNfiscaisCLASS_FISCAL2: TIntegerField;
    cdsListaNfiscaisCLASS_FISCAL3: TIntegerField;
    cdsListaNfiscaisCLASS_FISCAL4: TIntegerField;
    cdsListaNfiscaisCLASS_FISCAL5: TIntegerField;
    cdsListaNfiscaisCLASS_FISCAL6: TIntegerField;
    cdsListaNfiscaisCLASS_FISCAL7: TIntegerField;
    cdsListaNfiscaisMENSAGEM: TMemoField;
    cdsListaNfiscaisCANCELADA: TStringField;
    cdsListaNfiscaisDIAS_DEMONSTRACAO: TIntegerField;
    cdsListaNfiscaisCOTACAO_DOLAR: TBCDField;
    cdsListaNfiscaisNR_NFISCAL_RETORNO: TIntegerField;
    cdsListaNfiscaisDT_NFISCAL_RETORNO: TDateTimeField;
    cdsListaNfiscaisCONCLUIDA: TStringField;
    cdsListaNfiscaisVENDEDOR_SQ: TIntegerField;
    cdsListaNfiscaisNF_MANUAL: TStringField;
    cdsListaNfiscaisRETORNO_PRODUTO: TStringField;
    cdsListaNfiscaisRETORNO_OBSERVACAO: TMemoField;
    cdsListaNfiscaisqrListaNfiscaisItens: TDataSetField;
    cdsListaNfiscaisItensNFISCAL_ITEM_SQ: TIntegerField;
    cdsListaNfiscaisItensNFISCAL_SQ: TIntegerField;
    cdsListaNfiscaisItensITEM: TIntegerField;
    cdsListaNfiscaisItensTIPO_ITEM: TStringField;
    cdsListaNfiscaisItensPECA_SQ: TIntegerField;
    cdsListaNfiscaisItensMODELO_SQ: TIntegerField;
    cdsListaNfiscaisItensNR_SERIE_ITEM: TMemoField;
    cdsListaNfiscaisItensCLASS_FISCAL: TStringField;
    cdsListaNfiscaisItensSTRIBUT: TIntegerField;
    cdsListaNfiscaisItensQTDE_ITEM: TIntegerField;
    cdsListaNfiscaisItensVLR_UNIT_ITEM: TBCDField;
    cdsListaNfiscaisItensVLR_TOTAL_ITEM: TBCDField;
    cdsListaNfiscaisItensALIQ_ICMS_ITEM: TBCDField;
    cdsListaNfiscaisItensALIQ_IPI_ITEM: TBCDField;
    cdsListaNfiscaisItensVLR_ICMS_ITEM: TBCDField;
    cdsListaNfiscaisItensVLR_IPI_ITEM: TBCDField;
    cdsListaNfiscaisItensCODIGO_PECA: TStringField;
    cdsListaNfiscaisItensDESCRICAO_PECA: TStringField;
    cdsListaNfiscaisItensQTDE_PECA_LOJA: TIntegerField;
    cdsListaNfiscaisItensQTDE_PECA_ARMAZEM: TIntegerField;
    cdsListaNfiscaisItensCODIGO_NBM: TStringField;
    cdsListaModelosMODELO_SQ: TIntegerField;
    cdsListaModelosCODIGO_MODELO: TStringField;
    cdsListaModelosDESCRICAO_MODELO: TStringField;
    cdsListaModelosNBM_SQ: TIntegerField;
    cdsListaModelosUN_MODELO: TStringField;
    cdsListaModelosMARCA_MODELO: TStringField;
    cdsListaModelosPRECO_UNIT_MODELO: TBCDField;
    cdsListaAssistenciasEquipASSISTENCIA_EQUIP_SQ: TIntegerField;
    cdsListaAssistenciasEquipASSISTENCIA_SQ: TIntegerField;
    cdsListaAssistenciasEquipMODELO_SQ: TIntegerField;
    cdsListaAssistenciasEquipNR_SERIE_EQUIP: TMemoField;
    cdsListaAssistenciasEquipDEFEITO: TBlobField;
    cdsListaAssistenciasEquipDESCRICAO_MODELO: TStringField;
    cdsBuscaPecasPECA_SQ: TIntegerField;
    cdsBuscaPecasCODIGO_PECA: TStringField;
    cdsBuscaPecasDESCRICAO_PECA: TStringField;
    cdsBuscaPecasQTDE_PECA_LOJA: TIntegerField;
    cdsBuscaPecasQTDE_PECA_ARMAZEM: TIntegerField;
    cdsBuscaPecasQTDE_PECA_DEMO: TIntegerField;
    cdsBuscaPecasQTDE_PECA_DEFEITO: TIntegerField;
    cdsBuscaPecasQTDE_PECA_EM_USO: TIntegerField;
    cdsBuscaPecasQTDE_PECA_BACKUP: TIntegerField;
    cdsBuscaPecasQTDE_PECA_DEMO_CLI: TIntegerField;
    cdsBuscaPecasQTDE_PECA_HLC: TIntegerField;
    cdsBuscaPecasNBM_SQ: TIntegerField;
    cdsBuscaPecasMODELO_SQ: TIntegerField;
    cdsBuscaPecasUN_PECA: TStringField;
    cdsBuscaPecasMARCA_PECA: TStringField;
    cdsBuscaPecasPRECO_UNIT_PECA: TBCDField;
    cdsBuscaPecasTIPO_PECA: TIntegerField;
  private
    { Private declarations }
  public
    procedure AtualizaVariaveis(var cdsLista: TClientDataSet);
    { Public declarations }
  end;

var
  DMLista: TDMLista;

implementation

uses UDM;

{$R *.dfm}

procedure TDMLista.AtualizaVariaveis(var cdsLista: TClientDataSet);
var
  Sql: String;
begin
  Sql := 'SELECT * FROM EMPRESAS';
  cdsLista := TClientDataSet.Create(DMLista);
  cdsLista.RemoteServer := DMLista.SCServerLista;
  cdsLista.ProviderName := 'dspLista';
  cdsLista.Close;
  SCServerLista.Close;
  SCServerLista.Open;
  SCServerLista.AppServer.CriaLista (Sql);
  cdsLista.Open;
  SCServerLista.Close;

  DM.estado          := cdsLista.FieldByName ('ESTADO').Value;
  DM.alt_dtped       := cdsLista.FieldByName ('ALT_DATA_PEDIDO').Value;
  DM.alt_dtnf        := cdsLista.FieldByName ('ALT_DTEMISSAO_NFISCAL').Value;
  DM.alt_nrped       := cdsLista.FieldByName ('ALT_NR_PEDIDO').Value;
  DM.alt_nrnf        := cdsLista.FieldByName ('ALT_NR_NFISCAL').Value;
  DM.aliq_icms_prod1 := cdsLista.FieldByName ('ALIQ_ICMS_PROD1').Value;
  DM.aliq_icms_pec1  := cdsLista.FieldByName ('ALIQ_ICMS_PEC1').Value;
  DM.strib           := cdsLista.FieldByName ('STRIBUT').Value;
  DM.dias_dem        := cdsLista.FieldByName ('DIAS_DEMONSTRACAO').Value;
  DM.aliq_pis        := cdsLista.FieldByName ('ALIQ_PIS').AsCurrency;
  DM.aliq_cofins     := cdsLista.FieldByName ('ALIQ_COFINS').AsCurrency;
  DM.aliq_iss        := cdsLista.FieldByName ('ALIQ_ISS').AsCurrency;
end;

end.
