// Do not edit. This file is machine generated by the Resource DLL Wizard.

library webserver;

{ITE} {LCID:00000416:00000416} {}
{ITE} {RCFileType} {webserver_DRC.rc}

{$R 'webserver_DRC.res' 'webserver_DRC.rc'}

{$E PTB}

begin
end.